(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d'),W=720,H=1280,DURATION=15,FPS=30;
let photos=[],time=0,raf=0,cancelled=false,downloadURL='';
const themes={hero:{top:'#0f3454',bottom:'#277da3',accent:'#79ddff',text:'#fff'},warm:{top:'#6f4a39',bottom:'#d69a69',accent:'#ffe4a8',text:'#fff'},celebrate:{top:'#7b3868',bottom:'#ef87a8',accent:'#ffe277',text:'#fff'},concert:{top:'#09182e',bottom:'#253d83',accent:'#8edaff',text:'#fff'}};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)},lerp=(a,b,t)=>a+(b-a)*t;
const say=s=>$('status').textContent=s;
function roundRect(g,x,y,w,h,r,fill,stroke){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}
function imageRect(im,fit,zoom=1,panX=0,panY=0){if(fit==='contain'){const s=Math.min(W/im.width,H/im.height)*.9;return {sx:0,sy:0,sw:im.width,sh:im.height,dx:(W-im.width*s)/2,dy:(H-im.height*s)/2,dw:im.width*s,dh:im.height*s}}const target=W/H,ratio=im.width/im.height;let sw,sh;if(ratio>target){sh=im.height/zoom;sw=sh*target}else{sw=im.width/zoom;sh=sw/target}return {sx:clamp((im.width-sw)/2+panX*(im.width-sw)/2,0,im.width-sw),sy:clamp((im.height-sh)/2+panY*(im.height-sh)/2,0,im.height-sh),sw,sh,dx:0,dy:0,dw:W,dh:H}}
function drawPhoto(item,progress,alpha=1){const fit=$('fit').value,zoom=1+progress*.055,panX=Math.sin(progress*Math.PI)*.35*(item.seed%2?1:-1),panY=(progress-.5)*.16*(item.seed%3-1),r=imageRect(item.image,fit,zoom,panX,panY);ctx.save();ctx.globalAlpha=alpha;if(fit==='contain'){const t=themes[$('theme').value];const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,t.top);g.addColorStop(1,t.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}ctx.drawImage(item.image,r.sx,r.sy,r.sw,r.sh,r.dx,r.dy,r.dw,r.dh);ctx.restore()}
function sparkle(t,accent){for(let i=0;i<18;i++){const x=(i*137+t*(18+i%3)*7)%760-20,y=(i*83+t*(24+i%5)*5)%1320-20;ctx.globalAlpha=.18+.35*(.5+.5*Math.sin(t*2+i));ctx.fillStyle=i%3?accent:'#fff';ctx.beginPath();ctx.arc(x,y,2+i%3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function wrap(text,maxWidth,maxLines=3){const chars=[...text],lines=[];let line='';for(const ch of chars){const next=line+ch;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=ch;if(lines.length===maxLines-1)break}else line=next}if(line&&lines.length<maxLines)lines.push(line);return lines}
function drawCaption(text,y,t){if(!text)return;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 48px "Nanum Gothic",sans-serif';const lines=wrap(text,570,3),h=lines.length*68+40;roundRect(ctx,58,y-h/2,604,h,28,'rgba(5,25,37,.76)');ctx.lineJoin='round';for(let i=0;i<lines.length;i++){const yy=y+(i-(lines.length-1)/2)*68;ctx.lineWidth=12;ctx.strokeStyle='rgba(5,24,37,.95)';ctx.strokeText(lines[i],W/2,yy);ctx.fillStyle='#fff';ctx.fillText(lines[i],W/2,yy)}ctx.restore()}
function render(t){time=clamp(t,0,DURATION);const theme=themes[$('theme').value];ctx.clearRect(0,0,W,H);if(!photos.length){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,theme.top);g.addColorStop(1,theme.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);sparkle(time,theme.accent);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='400 65px Jua,sans-serif';ctx.fillText('사진을 골라 주세요',W/2,540);ctx.fillStyle='#cde7eb';ctx.font='700 23px "Nanum Gothic",sans-serif';ctx.fillText('최대 8장의 사진이 15초 영상으로 이어집니다',W/2,605)}else{const span=DURATION/photos.length,index=Math.min(photos.length-1,Math.floor(time/span)),local=(time-index*span)/span,item=photos[index];drawPhoto(item,ease(local));if(local>.83&&index<photos.length-1){const a=ease((local-.83)/.17);drawPhoto(photos[index+1],0,a)}const shade=ctx.createLinearGradient(0,0,0,H);shade.addColorStop(0,'rgba(4,19,30,.52)');shade.addColorStop(.35,'rgba(4,19,30,.02)');shade.addColorStop(.7,'rgba(4,19,30,.08)');shade.addColorStop(1,'rgba(4,19,30,.68)');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);sparkle(time,theme.accent);roundRect(ctx,45,45,630,58,29,'rgba(255,255,255,.9)');ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#27546a';ctx.font='800 20px "Nanum Gothic",sans-serif';ctx.fillText($('title').value.trim()||'우리의 소중한 순간',W/2,74);drawCaption(item.caption||'',910,time);ctx.fillStyle='#fff';ctx.font='800 18px "Nanum Gothic",sans-serif';ctx.fillText(`${index+1} / ${photos.length}`,W/2,1193);if(time>DURATION-1.8){const a=ease((time-(DURATION-1.8))/1.1);ctx.fillStyle=`rgba(7,27,40,${a*.72})`;ctx.fillRect(0,0,W,H);ctx.globalAlpha=a;ctx.font='400 112px Jua,sans-serif';ctx.lineWidth=18;ctx.strokeStyle='#133449';ctx.strokeText($('ending').value.trim()||'건행~',W/2,640);ctx.fillStyle=theme.accent;ctx.fillText($('ending').value.trim()||'건행~',W/2,640);ctx.font='700 22px "Nanum Gothic",sans-serif';ctx.fillStyle='#fff';ctx.fillText('우리의 모든 날이 건강하고 행복하기를',W/2,730);ctx.globalAlpha=1}}ctx.fillStyle=theme.accent;ctx.fillRect(0,0,W*time/DURATION,9);ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(W*time/DURATION,0,W,9);$('seek').value=Math.round(time*100);$('clock').textContent=`0:${String(Math.floor(time)).padStart(2,'0')} / 0:15`}
function stop(){cancelAnimationFrame(raf);raf=0;$('play').textContent='▶ 미리보기'}
function play(){if(raf){stop();return}if(time>=DURATION-.02)time=0;const start=performance.now()-time*1000,tick=now=>{render((now-start)/1000);if(time>=DURATION){stop();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);$('play').textContent='Ⅱ 일시정지'}
async function addFiles(files){for(const file of [...files].slice(0,8-photos.length)){if(!file.type.startsWith('image/'))continue;const url=URL.createObjectURL(file),image=new Image();image.src=url;try{await image.decode();photos.push({file,url,image,caption:'',seed:photos.length+1})}catch{URL.revokeObjectURL(url)}}rebuild();render(0);updateButtons()}
function rebuild(){const list=$('photo-list');if(!photos.length){list.innerHTML='<p class="empty">아직 선택한 사진이 없습니다.</p>';return}list.replaceChildren(...photos.map((item,index)=>{const card=document.createElement('div');card.className='photo-item';const img=document.createElement('img');img.src=item.url;img.alt=`선택한 사진 ${index+1}`;const label=document.createElement('label');label.textContent=`${index+1}번 사진 문구`;const input=document.createElement('input');input.maxLength=44;input.placeholder='예: 오늘도 영웅님과 함께';input.value=item.caption;input.oninput=()=>{item.caption=input.value;render(time)};label.append(input);const del=document.createElement('button');del.type='button';del.setAttribute('aria-label',`${index+1}번 사진 삭제`);del.textContent='×';del.onclick=()=>{URL.revokeObjectURL(item.url);photos.splice(index,1);photos.forEach((p,i)=>p.seed=i+1);rebuild();render(0);updateButtons()};card.append(img,label,del);return card}))}
function updateButtons(){for(const id of ['export','thumbnail'])$(id).disabled=!photos.length;say(photos.length?`${photos.length}장의 사진으로 15초 영상을 만들 수 있습니다.`:'사진을 선택하면 영상을 만들 수 있습니다.')}
async function loadMuxer(){if(window.Mp4Muxer)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=resolve;s.onerror=()=>reject(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s)})}
async function encode(){if(!window.VideoEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await loadMuxer();const config={codec:'avc1.42001f',width:W,height:H,bitrate:3300000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(config)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width:W,height:H,frameRate:FPS},fastStart:'in-memory'}),chunks=[];let encodeError,encoder=new VideoEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:e=>encodeError=e});try{encoder.configure(config);const total=DURATION*FPS;for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(encodeError)throw encodeError;render(i/FPS);const stamp=Math.round(i*1e6/FPS),frame=new VideoFrame(canvas,{timestamp:stamp,duration:Math.round(1e6/FPS)});encoder.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||encoder.encodeQueueSize>6){say(`15초 영상을 만들고 있습니다… ${Math.floor(i/total*100)}%`);await new Promise(r=>setTimeout(r,0));while(encoder.encodeQueueSize>6)await new Promise(r=>setTimeout(r,6))}}await encoder.flush();if(encodeError)throw encodeError;chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const entry of chunks){if(entry.chunk.timestamp<=last)continue;mux.addVideoChunk(entry.chunk,entry.meta);last=entry.chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(encoder.state!=='closed')encoder.close()}}
function filename(ext){return (($('title').value.trim()||'나의-팬-영상').replace(/[\\/:*?"<>|]+/g,'').replace(/\s+/g,'-').slice(0,45)||'나의-팬-영상')+ext}
function download(blob,name,remember=false){const url=URL.createObjectURL(blob),a=remember?$('ready-download'):document.createElement('a');a.href=url;a.download=name;if(remember){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;a.hidden=false;a.textContent='완성 영상 다시 저장'}else{document.body.append(a);setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},5000)}a.click()}
function lock(on){for(const id of ['photos','title','ending','theme','fit','play','export','thumbnail','reset','seek'])$(id).disabled=on;$('cancel').hidden=!on}
$('photos').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('play').onclick=play;$('seek').oninput=()=>{stop();render(Number($('seek').value)/100)};
for(const id of ['title','ending','theme','fit'])$(id).oninput=()=>render(time);
$('reset').onclick=()=>{stop();photos.forEach(p=>URL.revokeObjectURL(p.url));photos=[];$('title').value='우리의 소중한 순간';$('ending').value='건행~';$('theme').value='hero';$('fit').value='cover';rebuild();render(0);updateButtons()};
$('cancel').onclick=()=>cancelled=true;
$('export').onclick=async()=>{if(!photos.length)return;stop();cancelled=false;lock(true);try{const blob=await encode();download(blob,filename('-15초-세로영상.mp4'),true);say('15초 MP4를 저장했습니다.')}catch(e){say('영상 저장 오류: '+(e?.message||e))}finally{lock(false);render(0)}};
$('thumbnail').onclick=()=>{if(!photos.length)return;const saved=time;render(Math.min(3,DURATION/photos.length*.55));const out=document.createElement('canvas');out.width=1080;out.height=1920;out.getContext('2d').drawImage(canvas,0,0,1080,1920);out.toBlob(blob=>download(blob,filename('-대표사진.png')),'image/png');render(saved)};
window.addEventListener('beforeunload',()=>{stop();photos.forEach(p=>URL.revokeObjectURL(p.url));if(downloadURL)URL.revokeObjectURL(downloadURL)});
document.fonts.ready.then(()=>render(0));
})();
