(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d'),W=720,H=1280,DURATION=15,FPS=30,INTRO=1.2,OUTRO=2;
let photos=[],time=0,raf=0,cancelled=false,downloadURL='';
const themes={hero:{top:'#0f3454',bottom:'#277da3',accent:'#79ddff',text:'#fff'},warm:{top:'#6f4a39',bottom:'#d69a69',accent:'#ffe4a8',text:'#fff'},celebrate:{top:'#7b3868',bottom:'#ef87a8',accent:'#ffe277',text:'#fff'},concert:{top:'#09182e',bottom:'#253d83',accent:'#8edaff',text:'#fff'}};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)},lerp=(a,b,t)=>a+(b-a)*t;
const say=s=>$('status').textContent=s;
function roundRect(g,x,y,w,h,r,fill,stroke){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}
function imageRect(im,fit,zoom=1,panX=0,panY=0){if(fit==='contain'){const s=Math.min(W/im.width,H/im.height)*.9;return {sx:0,sy:0,sw:im.width,sh:im.height,dx:(W-im.width*s)/2,dy:(H-im.height*s)/2,dw:im.width*s,dh:im.height*s}}const target=W/H,ratio=im.width/im.height;let sw,sh;if(ratio>target){sh=im.height/zoom;sw=sh*target}else{sw=im.width/zoom;sh=sw/target}return {sx:clamp((im.width-sw)/2+panX*(im.width-sw)/2,0,im.width-sw),sy:clamp((im.height-sh)/2+panY*(im.height-sh)/2,0,im.height-sh),sw,sh,dx:0,dy:0,dw:W,dh:H}}
function drawPhoto(item,progress,alpha=1,index=0){const fit=$('fit').value,mode=(item.seed+index)%4,zoom=mode===1?1.085-progress*.045:1.025+progress*(mode===3?.075:.055),panX=mode===0?(progress-.5)*.65:mode===2?Math.sin(progress*Math.PI)*-.42:Math.sin(progress*Math.PI)*.18,panY=mode===2?(progress-.5)*.42:(progress-.5)*.12*(item.seed%3-1),r=imageRect(item.image,fit,zoom,panX,panY),turn=mode===3?(-.012+progress*.024):0;ctx.save();ctx.globalAlpha=alpha;if(fit==='contain'){const t=themes[$('theme').value];const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,t.top);g.addColorStop(1,t.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}ctx.translate(W/2,H/2);ctx.rotate(turn);ctx.scale(1.018,1.018);ctx.translate(-W/2,-H/2);ctx.drawImage(item.image,r.sx,r.sy,r.sw,r.sh,r.dx,r.dy,r.dw,r.dh);ctx.restore()}
function sparkle(t,accent){for(let i=0;i<18;i++){const x=(i*137+t*(18+i%3)*7)%760-20,y=(i*83+t*(24+i%5)*5)%1320-20;ctx.globalAlpha=.18+.35*(.5+.5*Math.sin(t*2+i));ctx.fillStyle=i%3?accent:'#fff';ctx.beginPath();ctx.arc(x,y,2+i%3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function wrap(text,maxWidth,maxLines=3){const chars=[...text],lines=[];let line='';for(const ch of chars){const next=line+ch;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=ch;if(lines.length===maxLines-1)break}else line=next}if(line&&lines.length<maxLines)lines.push(line);return lines}
function drawCaption(text,y,local){if(!text)return;const enter=ease(local/.55),reveal=ease((local-.12)/.9);ctx.save();ctx.translate(W/2,y);ctx.scale(.88+.12*enter,.88+.12*enter);ctx.translate(-W/2,-y);ctx.globalAlpha=enter;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 48px "Nanum Gothic",sans-serif';const lines=wrap(text,570,3),h=lines.length*68+46;roundRect(ctx,55,y-h/2,610,h,28,'rgba(5,25,37,.82)');ctx.fillStyle='rgba(5,25,37,.82)';ctx.beginPath();ctx.moveTo(102,y+h/2-2);ctx.lineTo(143,y+h/2-2);ctx.lineTo(112,y+h/2+30);ctx.closePath();ctx.fill();ctx.save();ctx.beginPath();ctx.rect(72,y-h/2,576*reveal,h+35);ctx.clip();ctx.lineJoin='round';for(let i=0;i<lines.length;i++){const yy=y+(i-(lines.length-1)/2)*68;ctx.lineWidth=12;ctx.strokeStyle='rgba(5,24,37,.96)';ctx.strokeText(lines[i],W/2,yy);ctx.fillStyle='#fff';ctx.fillText(lines[i],W/2,yy)}ctx.restore();ctx.fillStyle='#fff';ctx.globalAlpha=.75*enter;ctx.fillRect(88,y+h/2-18,500*reveal,4);ctx.restore()}
function drawSticker(t,index,accent){ctx.save();const bob=Math.sin(t*3+index)*9,spin=Math.sin(t*1.7+index)*.08;ctx.translate(608,235+bob);ctx.rotate(spin);roundRect(ctx,-72,-34,144,68,22,'rgba(255,255,255,.91)');ctx.fillStyle='#28576a';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='400 28px Jua,sans-serif';ctx.fillText(index%2?'건행 ♥':'FAN MOMENT',0,1);ctx.restore();for(let i=0;i<5;i++){const a=t*1.8+i*1.25,x=85+Math.cos(a)*22,y=270+i*95+Math.sin(a)*18;ctx.fillStyle=i%2?accent:'#fff';ctx.globalAlpha=.55;ctx.font=`400 ${22+i%3*6}px Jua,sans-serif`;ctx.fillText(i%2?'★':'♥',x,y)}ctx.globalAlpha=1}
function drawEmpty(t,theme){const motion=t===0?1.8:t,g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,theme.top);g.addColorStop(1,theme.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);sparkle(motion,theme.accent);for(let i=0;i<3;i++){ctx.save();ctx.translate(W/2+(i-1)*86,400+i*30);ctx.rotate((i-1)*.12+Math.sin(motion*.8+i)*.018);roundRect(ctx,-185,-235,370,470,24,i===1?'#fff':'rgba(255,255,255,.72)');ctx.fillStyle=i===1?'#d5eaf0':'#bdd9e1';roundRect(ctx,-160,-210,320,330,15);ctx.fillStyle='#6ea3b6';ctx.beginPath();ctx.moveTo(-145,96);ctx.lineTo(-25,-40);ctx.lineTo(48,38);ctx.lineTo(105,-18);ctx.lineTo(155,96);ctx.closePath();ctx.fill();ctx.fillStyle=theme.accent;ctx.beginPath();ctx.arc(86,-138,27,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.font='400 62px Jua,sans-serif';ctx.fillText('사진으로 만드는 나만의 15초',W/2,760);ctx.fillStyle='#d7eef2';ctx.font='700 23px "Nanum Gothic",sans-serif';ctx.fillText('사진을 고르면 글씨와 장면이 재미있게 움직여요',W/2,825);const penX=125+(motion*120)%470;ctx.strokeStyle=theme.accent;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(125,870);ctx.lineTo(penX,870);ctx.stroke();ctx.save();ctx.translate(penX+16,860);ctx.rotate(-.65);roundRect(ctx,-7,-32,14,64,7,'#f3d269');ctx.restore()}
function drawIntro(item,t,theme){const p=ease(t/INTRO);drawPhoto(item,p,1,0);ctx.fillStyle='rgba(5,25,38,.55)';ctx.fillRect(0,0,W,H);sparkle(t,theme.accent);ctx.textAlign='center';ctx.textBaseline='middle';ctx.save();ctx.beginPath();ctx.rect(55,360,610*p,300);ctx.clip();ctx.font='400 76px Jua,sans-serif';ctx.lineWidth=18;ctx.strokeStyle='#123448';const lines=wrap($('title').value.trim()||'우리의 소중한 순간',580,3);lines.forEach((line,i)=>{const y=475+i*88;ctx.strokeText(line,W/2,y);ctx.fillStyle='#fff';ctx.fillText(line,W/2,y)});ctx.restore();ctx.strokeStyle=theme.accent;ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(105,720);ctx.lineTo(105+510*p,720);ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 22px "Nanum Gothic",sans-serif';ctx.globalAlpha=p;ctx.fillText('사진으로 만든 나만의 팬 영상',W/2,770);ctx.globalAlpha=1}
function drawOutro(item,t,theme){drawPhoto(item,1,1,photos.length-1);ctx.fillStyle='rgba(7,27,40,.72)';ctx.fillRect(0,0,W,H);const p=ease(t/1.05);sparkle(time*1.7,theme.accent);ctx.save();ctx.translate(W/2,H/2);for(let i=0;i<18;i++){ctx.rotate(Math.PI/9);ctx.fillStyle=i%2?`${theme.accent}55`:'rgba(255,255,255,.15)';ctx.fillRect(90,0,210*p,4)}ctx.restore();ctx.textAlign='center';ctx.textBaseline='middle';ctx.globalAlpha=p;ctx.font='400 122px Jua,sans-serif';ctx.lineWidth=20;ctx.strokeStyle='#133449';ctx.strokeText($('ending').value.trim()||'건행~',W/2,610);ctx.fillStyle=theme.accent;ctx.fillText($('ending').value.trim()||'건행~',W/2,610);ctx.font='700 24px "Nanum Gothic",sans-serif';ctx.fillStyle='#fff';ctx.fillText('우리의 모든 날이 건강하고 행복하기를',W/2,705);ctx.globalAlpha=1}
function render(t){time=clamp(t,0,DURATION);const theme=themes[$('theme').value];ctx.clearRect(0,0,W,H);if(!photos.length)drawEmpty(time,theme);else if(time<INTRO)drawIntro(photos[0],time,theme);else if(time>=DURATION-OUTRO)drawOutro(photos[photos.length-1],time-(DURATION-OUTRO),theme);else{const available=DURATION-INTRO-OUTRO,sceneTime=time-INTRO,span=available/photos.length,index=Math.min(photos.length-1,Math.floor(sceneTime/span)),local=sceneTime-index*span,phase=clamp(local/span),item=photos[index];drawPhoto(item,ease(phase),1,index);if(phase>.76&&index<photos.length-1){const a=ease((phase-.76)/.24);ctx.save();ctx.translate((1-a)*W*.12,0);drawPhoto(photos[index+1],0,a,index+1);ctx.restore()}const shade=ctx.createLinearGradient(0,0,0,H);shade.addColorStop(0,'rgba(4,19,30,.58)');shade.addColorStop(.3,'rgba(4,19,30,.01)');shade.addColorStop(.7,'rgba(4,19,30,.08)');shade.addColorStop(1,'rgba(4,19,30,.7)');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);sparkle(time,theme.accent);drawSticker(time,index,theme.accent);const header=ease(local/.45);ctx.save();ctx.translate(0,-(1-header)*75);ctx.globalAlpha=header;roundRect(ctx,45,45,630,60,30,'rgba(255,255,255,.92)');ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#27546a';ctx.font='800 21px "Nanum Gothic",sans-serif';ctx.fillText($('title').value.trim()||'우리의 소중한 순간',W/2,75);ctx.restore();drawCaption(item.caption||'',905,local);roundRect(ctx,296,1160,128,48,24,'rgba(4,24,37,.68)');ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 18px "Nanum Gothic",sans-serif';ctx.fillText(`${index+1} / ${photos.length}`,W/2,1184)}ctx.fillStyle=theme.accent;ctx.fillRect(0,0,W*time/DURATION,9);ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(W*time/DURATION,0,W,9);$('seek').value=Math.round(time*100);$('clock').textContent=`0:${String(Math.floor(time)).padStart(2,'0')} / 0:15`}
function stop(){cancelAnimationFrame(raf);raf=0;$('play').textContent='▶ 미리보기'}
function play(){if(raf){stop();return}if(time>=DURATION-.02)time=0;const start=performance.now()-time*1000,tick=now=>{render((now-start)/1000);if(time>=DURATION){stop();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);$('play').textContent='Ⅱ 일시정지'}
async function addFiles(files){for(const file of [...files].slice(0,8-photos.length)){if(!file.type.startsWith('image/'))continue;const url=URL.createObjectURL(file),image=new Image();image.src=url;try{await image.decode();photos.push({file,url,image,caption:'',seed:photos.length+1})}catch{URL.revokeObjectURL(url)}}rebuild();render(0);updateButtons()}
function rebuild(){const list=$('photo-list');if(!photos.length){list.innerHTML='<p class="empty">아직 선택한 사진이 없습니다.</p>';return}list.replaceChildren(...photos.map((item,index)=>{const card=document.createElement('div');card.className='photo-item';const img=document.createElement('img');img.src=item.url;img.alt=`선택한 사진 ${index+1}`;const label=document.createElement('label');label.textContent=`${index+1}번 사진 문구`;const input=document.createElement('input');input.maxLength=44;input.placeholder='예: 오늘도 영웅님과 함께';input.value=item.caption;input.oninput=()=>{item.caption=input.value;render(time)};label.append(input);const del=document.createElement('button');del.type='button';del.setAttribute('aria-label',`${index+1}번 사진 삭제`);del.textContent='×';del.onclick=()=>{URL.revokeObjectURL(item.url);photos.splice(index,1);photos.forEach((p,i)=>p.seed=i+1);rebuild();render(0);updateButtons()};card.append(img,label,del);return card}))}
function updateButtons(){for(const id of ['export','thumbnail'])$(id).disabled=!photos.length;say(photos.length?`${photos.length}장의 사진으로 15초 영상을 만들 수 있습니다.`:'사진을 선택하면 영상을 만들 수 있습니다.')}
async function loadMuxer(){if(window.Mp4Muxer)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=resolve;s.onerror=()=>reject(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s)})}
async function encode(){if(!window.VideoEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await loadMuxer();const config={codec:'avc1.42001f',width:W,height:H,bitrate:3300000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(config)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width:W,height:H,frameRate:FPS},fastStart:'in-memory'}),chunks=[];let encodeError,encoder=new VideoEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:e=>encodeError=e});try{encoder.configure(config);const total=DURATION*FPS;for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(encodeError)throw encodeError;render(i/FPS);const stamp=Math.round(i*1e6/FPS),frame=new VideoFrame(canvas,{timestamp:stamp,duration:Math.round(1e6/FPS)});encoder.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||encoder.encodeQueueSize>6){say(`15초 영상을 만들고 있습니다… ${Math.floor(i/total*100)}%`);await new Promise(r=>setTimeout(r,0));while(encoder.encodeQueueSize>6)await new Promise(r=>setTimeout(r,6))}}await encoder.flush();if(encodeError)throw encodeError;chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const entry of chunks){if(entry.chunk.timestamp<=last)continue;mux.addVideoChunk(entry.chunk,entry.meta);last=entry.chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(encoder.state!=='closed')encoder.close()}}
function filename(ext){return (($('title').value.trim()||'나의-팬-영상').replace(/[\\/:*?"<>|]+/g,'').replace(/\s+/g,'-').slice(0,45)||'나의-팬-영상')+ext}
function download(blob,name,remember=false){const url=URL.createObjectURL(blob),a=remember?$('ready-download'):document.createElement('a');a.href=url;a.download=name;if(remember){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;a.hidden=false;a.textContent='완성 영상 다시 저장'}else{document.body.append(a);setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},5000)}a.click()}
function lock(on){for(const id of ['photos','title','ending','theme','fit','play','export','thumbnail','reset','seek'])$(id).disabled=on;$('cancel').hidden=!on}
$('photos').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('play').onclick=play;$('seek').oninput=()=>{stop();render(Number($('seek').value)/100)};
for(const id of ['title','ending','theme','fit'])$(id).oninput=()=>render(time);
$('reset').onclick=()=>{stop();photos.forEach(p=>URL.revokeObjectURL(p.url));photos=[];$('title').value='우리의 소중한 순간';$('ending').value='건행~';$('theme').value='hero';$('fit').value='cover';rebuild();render(0);updateButtons()};
$('cancel').onclick=()=>cancelled=true;
$('export').onclick=async()=>{if(!photos.length)return;stop();cancelled=false;lock(true);try{const blob=await encode();download(blob,filename('-15초-세로영상.mp4'),true);say('15초 MP4를 저장했습니다.')}catch(e){say('영상 저장 오류: '+(e?.message||e))}finally{lock(false);render(0)}};
$('thumbnail').onclick=()=>{if(!photos.length)return;const saved=time;render(Math.min(3,DURATION/photos.length*.55));const out=document.createElement('canvas');out.width=1080;out.height=1920;out.getContext('2d').drawImage(canvas,0,0,1080,1920);out.toBlob(blob=>download(blob,filename('-대표사진.png')),'image/png');render(saved)};
window.addEventListener('beforeunload',()=>{stop();photos.forEach(p=>URL.revokeObjectURL(p.url));if(downloadURL)URL.revokeObjectURL(downloadURL)});
document.fonts.ready.then(()=>render(0));
})();
