(()=>{
'use strict';
const $=id=>document.getElementById(id),FPS=30,RATE=48000,SCENE=8,LONG=72,SHORT=30;
const longTitle='일흔 살 엄마가 처음 임영웅 콘서트에 간 날';
const shortTitle='엄마가 일흔 살에 다시 소녀가 됐습니다';
const longNarration='일흔 살 엄마에게 오늘은 아주 특별한 날입니다. 아침부터 하늘색 가디건을 꺼내고, 응원봉과 휴대전화를 몇 번이나 확인했습니다. 혼자였다면 집을 나서는 것부터 망설였겠지만, 역에서 만난 영웅시대 친구가 환하게 손을 흔들어 주었습니다. 두 사람은 지하철을 타고 고양종합운동장으로 향했습니다. 출구를 잠시 헤매기도 했지만 파란 응원봉을 든 사람들을 따라가니 어느새 거대한 스타디움이 눈앞에 나타났습니다. 입장권을 보여 주고 천천히 자리를 찾아가는 동안 낯선 팬들이 길을 알려 주고 서로 사진을 찍어 주었습니다. 마침내 조명이 꺼지고 수많은 파란빛이 동시에 켜졌습니다. 엄마는 응원봉을 흔들다가 문득 가슴에 손을 얹었습니다. 노래 한 곡에 웃고, 함께 외치고, 끝내 눈물을 닦았습니다. 공연이 끝난 뒤 엄마가 가장 먼저 한 말은 힘들다는 말이 아니었습니다. 다음 콘서트에는 더 예쁘게 입고 와야겠네. 집으로 돌아온 엄마의 얼굴에는 아직도 파란빛이 남아 있었습니다. 일흔 살의 어느 하루, 엄마는 다시 소녀가 되었습니다.';
const shortNarration='일흔 살 엄마가 처음 스타디움 콘서트에 갔습니다. 출구를 잠시 헤매고 입장권을 몇 번이나 확인했지만, 파란빛이 켜지는 순간 모든 걱정은 사라졌습니다. 노래를 따라 부르고 응원봉을 흔들다 눈물을 닦은 엄마. 그날 엄마는 다시 소녀가 됐습니다.';
const scenes=[
 {bg:0,title:'오늘은 아주 특별한 날',tag:'아침부터 설렘 가득'},
 {bg:0,title:'응원봉 챙겼지? 표 챙겼지?',tag:'세 번 확인은 기본'},
 {bg:1,title:'친구를 만나니 용기가 생겼습니다',tag:'함께라서 든든'},
 {bg:2,title:'저기가 맞나? 파란빛을 따라가요!',tag:'잠깐의 길 찾기'},
 {bg:3,title:'입장권을 보여 주는 손이 떨렸습니다',tag:'드디어 입장'},
 {bg:4,title:'하늘빛이 한꺼번에 켜졌습니다',tag:'가슴이 쿵'},
 {bg:4,title:'엄마는 웃다가 결국 눈물을 닦았습니다',tag:'다시 만난 소녀'},
 {bg:4,title:'다음엔 더 예쁘게 입고 와야지!',tag:'벌써 다음 약속'},
 {bg:5,title:'그날의 파란빛은 오래 남았습니다',tag:'평생 잊지 못할 하루'}
];
const bgFiles=['home-morning.webp','subway.webp','stadium-plaza.webp','concourse.webp','stadium-inside.webp','home-night.webp'].map(x=>'assets/first-stadium/backgrounds/'+x),backgrounds=[],mother=[],friend=[];
const canvas=$('render-canvas'),shortCanvas=$('short-canvas');let busy=false,cancelled=false,longURL='',shortURL='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,smooth=t=>{t=clamp(t);return t*t*(3-2*t)},smoother=t=>{t=clamp(t);return t*t*t*(t*(t*6-15)+10)};
async function image(src){const im=new Image();im.src=src;await im.decode();return im}
function extract(im,cols,rows){const s=document.createElement('canvas');s.width=im.width;s.height=im.height;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(im,0,0);const d=c.getImageData(0,0,s.width,s.height).data,out=[];for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){const x0=Math.round(q*s.width/cols),x1=Math.round((q+1)*s.width/cols),y0=Math.round(r*s.height/rows),y1=Math.round((r+1)*s.height/rows);let l=x1,rr=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*s.width+x)*4+3]>20){l=Math.min(l,x);rr=Math.max(rr,x);t=Math.min(t,y);b=Math.max(b,y)}const cc=document.createElement('canvas');cc.width=Math.max(1,rr-l+1);cc.height=Math.max(1,b-t+1);cc.getContext('2d').drawImage(im,l,t,cc.width,cc.height,0,0,cc.width,cc.height);out.push(cc)}return out}
function cover(g,im,w,h,focus=.5,zoom=1,pan=0){const ratio=w/h,src=im.width/im.height;let sw,sh;if(src>ratio){sh=im.height/zoom;sw=sh*ratio}else{sw=im.width/zoom;sh=sw/ratio}const sx=clamp(im.width*focus-sw/2+pan,0,im.width-sw),sy=(im.height-sh)/2;g.drawImage(im,sx,sy,sw,sh,0,0,w,h)}
function draw(g,im,x,bottom,height,opt={}){const width=height*im.width/im.height;g.save();g.globalAlpha=opt.alpha??1;g.translate(x,bottom);g.rotate(opt.rotate||0);if(opt.flip)g.scale(-1,1);g.drawImage(im,-width/2,-height,width,height);g.restore()}
function blend(g,frames,a,b,p,x,bottom,height,opt={}){p=smoother(p);const edge=.42;if(p<=edge)return draw(g,frames[a],x,bottom,height,opt);if(p>=1-edge)return draw(g,frames[b],x,bottom,height,opt);const q=smoother((p-edge)/(1-edge*2)),alpha=opt.alpha??1;draw(g,frames[a],x,bottom,height,{...opt,alpha:alpha*(1-q)});draw(g,frames[b],x,bottom,height,{...opt,alpha:alpha*q})}
function sequence(g,frames,order,t,x,bottom,height,opt={}){const span=2.1,pos=(t/span)%order.length,i=Math.floor(pos),p=pos-i;blend(g,frames,order[i],order[(i+1)%order.length],p,x,bottom,height,opt)}
function walk(g,frames,a,b,t,x0,x1,bottom,height,opt={}){const p=smoother(t/SCENE),step=t*2.1,pose=Math.floor(step)%2?a:b,x=mix(x0,x1,p),bob=Math.abs(Math.sin(step*Math.PI))*7,lean=Math.sin(step*Math.PI*2)*.012;draw(g,frames[pose],x,bottom-bob,height,{...opt,rotate:(opt.rotate||0)+lean})}
function actors(index,t,g,w,h,vertical=false){const bottom=h-(vertical?70:14),mh=vertical?590:455,fh=vertical?520:410,c=w/2,breath=Math.sin(t*2.15)*1.5;
 if(vertical){
  if(index<2)sequence(g,mother,[0,1,2],t,c,bottom,mh);
  else if(index===2){walk(g,mother,4,5,t,40,w*.62,bottom,mh);walk(g,friend,2,3,t,-80,w*.25,bottom,fh)}
  else if(index===3){blend(g,mother,6,7,t/SCENE,c+80,bottom,mh);draw(g,friend[1],115,bottom,fh*.78)}
  else if(index===4){blend(g,mother,7,8,t/SCENE,c+65,bottom,mh);draw(g,friend[4],115,bottom,fh*.78)}
  else if(index<8){sequence(g,mother,[9,10,11],t,c+70,bottom,mh);sequence(g,friend,[5,6,7],t+.7,120,bottom,fh*.76)}
  else blend(g,mother,11,0,t/SCENE,c,bottom,mh);return;
 }
 switch(index){
  case 0:sequence(g,mother,[0,1,2],t,c,bottom+breath,mh);break;
  case 1:{if(t<2.4)blend(g,mother,2,3,t/2.4,c,bottom,mh);else walk(g,mother,4,5,t-2.4,c,w*.82,bottom,mh);break}
  case 2:walk(g,mother,4,5,t,w*.12,w*.64,bottom,mh);walk(g,friend,2,3,t+.15,w*.02,w*.42,bottom,fh);break;
  case 3:blend(g,mother,6,7,(t-1.2)/3.2,w*.53,bottom,mh);blend(g,friend,0,1,(t-.6)/2.5,w*.76,bottom,fh);break;
  case 4:blend(g,mother,7,8,t/3,w*.43,bottom,mh);blend(g,friend,1,4,(t-1)/3,w*.7,bottom,fh);break;
  case 5:sequence(g,mother,[9,10,9],t,w*.46,bottom,mh);sequence(g,friend,[5,6,5],t+.6,w*.72,bottom,fh);break;
  case 6:blend(g,mother,10,11,(t-1.5)/3.5,w*.48,bottom,mh);blend(g,friend,6,7,(t-2)/3,w*.73,bottom,fh);break;
  case 7:sequence(g,mother,[9,10,9],t,w*.43,bottom,mh);sequence(g,friend,[5,6,5],t+.4,w*.69,bottom,fh);break;
  default:blend(g,mother,11,0,(t-1.4)/4,w*.48,bottom,mh);
 }
}
function round(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);g.fill()}
function caption(g,scene,t,w,h,vertical=false){const bw=vertical?w-70:Math.min(890,w*.69),bh=vertical?185:118,x=(w-bw)/2,y=vertical?70:42,enter=smoother(t/.45),scale=.92+.08*enter;g.save();g.translate(w/2,y+bh/2);g.scale(scale,scale);g.translate(-w/2,-y-bh/2);g.globalAlpha=enter;g.shadowColor='rgba(9,31,50,.35)';g.shadowBlur=20;g.shadowOffsetY=8;g.fillStyle='rgba(255,255,255,.96)';round(g,x,y,bw,bh,vertical?30:24);g.shadowColor='transparent';g.lineWidth=5;g.strokeStyle='#244d68';g.stroke();g.fillStyle='#ffcf59';round(g,x+25,y-19,vertical?260:220,42,21);g.fillStyle='#173d56';g.textAlign='center';g.textBaseline='middle';g.font=`800 ${vertical?22:18}px "Nanum Gothic",sans-serif`;g.fillText(scene.tag,x+25+(vertical?130:110),y+2);let size=vertical?50:44;while(size>25){g.font=`800 ${size}px "Nanum Gothic",sans-serif`;if(g.measureText(scene.title).width<bw-45)break;size-=2}g.lineWidth=8;g.strokeStyle='#fff';g.strokeText(scene.title,w/2,y+bh*.61);g.fillStyle='#17384d';g.fillText(scene.title,w/2,y+bh*.61);g.restore()}
function particles(g,w,h,t){for(let i=0;i<22;i++){const x=(i*127+t*21)%w,y=h*.22+(i*67%Math.round(h*.62))+Math.sin(t*1.7+i)*8,a=.08+.18*(.5+.5*Math.sin(t*3+i));g.globalAlpha=a;g.fillStyle=i%4?'#8cddff':'#ffe09a';g.beginPath();g.arc(x,y,1.5+i%3,0,Math.PI*2);g.fill()}g.globalAlpha=1}
function renderGlobal(time,target,vertical=false){const g=target.getContext('2d'),w=target.width,h=target.height,index=Math.min(scenes.length-1,Math.floor(time/SCENE)),local=time-index*SCENE,scene=scenes[index];g.clearRect(0,0,w,h);const zoom=1+.025*smooth(local/SCENE),pan=Math.sin((index+1)*1.7)*backgrounds[scene.bg].width*.015;cover(g,backgrounds[scene.bg],w,h,.5,zoom,pan);if(local<.55&&index>0){g.save();g.globalAlpha=1-smoother(local/.55);cover(g,backgrounds[scenes[index-1].bg],w,h,.5,1.025);g.restore()}const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,25,43,.27)');shade.addColorStop(.58,'rgba(5,25,43,.01)');shade.addColorStop(1,'rgba(4,20,35,.43)');g.fillStyle=shade;g.fillRect(0,0,w,h);actors(index,local,g,w,h,vertical);particles(g,w,h,time);caption(g,scene,local,w,h,vertical);g.fillStyle='rgba(8,34,53,.72)';round(g,w*.25,h-38,w*.5,26,13);g.fillStyle='#fff';g.font=`700 ${vertical?16:13}px "Nanum Gothic",sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText('2026 IM HERO – THE STADIUM 2를 배경으로 한 팬 창작 이야기',w/2,h-25)}
const shortMap=[0,2,3,4,5,6],shortLines=['오늘은 특별한 날','함께라서 용기를 냈고','파란빛을 따라 도착해','떨리는 손으로 입장하고','하늘빛 속에서 웃다가','엄마는 다시 소녀가 됐습니다'];
function renderShort(time,target){const g=target.getContext('2d'),w=target.width,h=target.height,part=Math.min(5,Math.floor(time/5)),local=time-part*5,index=shortMap[part],scene=scenes[index];g.clearRect(0,0,w,h);cover(g,backgrounds[scene.bg],w,h,.5,1.06+.02*smooth(local/5));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(6,27,46,.76)');shade.addColorStop(.35,'rgba(6,27,46,.06)');shade.addColorStop(1,'rgba(5,22,38,.75)');g.fillStyle=shade;g.fillRect(0,0,w,h);actors(index,local,g,w,h,true);particles(g,w,h,time);g.textAlign='center';g.textBaseline='middle';g.lineJoin='round';g.font='800 54px "Nanum Gothic",sans-serif';g.lineWidth=12;g.strokeStyle='rgba(10,37,57,.95)';g.strokeText(shortLines[part],w/2,165);g.fillStyle=part===5?'#ffd25f':'#fff';g.fillText(shortLines[part],w/2,165);g.fillStyle='#65c9f0';g.fillRect(0,0,w*time/SHORT,8);g.fillStyle='rgba(255,255,255,.23)';g.fillRect(w*time/SHORT,0,w,8);g.fillStyle='rgba(10,37,57,.76)';round(g,45,h-78,w-90,46,23);g.fillStyle='#fff';g.font='700 18px "Nanum Gothic",sans-serif';g.fillText('일흔 살 엄마의 첫 스타디움',w/2,h-55)}
function scheduleAudio(ac,dest,duration,offset=0){const master=ac.createGain();master.gain.value=.48;master.connect(dest);const tone=(at,f,d=.5,v=.025,type='sine')=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=begin-offset,remain=at+d-begin,o=ac.createOscillator(),gain=ac.createGain();o.type=type;o.frequency.value=f;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(v,when+.03);gain.gain.exponentialRampToValueAtTime(.0001,when+remain);o.connect(gain).connect(master);o.start(when);o.stop(when+remain+.03)};const roots=[196,220,246.94,261.63];for(let at=0,n=0;at<duration;at+=4,n++){const root=roots[n%4],lift=at>duration*.55?1.12:1;for(const m of [1,1.25,1.5])tone(at,root*m*lift,3.85,.013,'triangle');for(let k=.35;k<3.8;k+=.7)tone(at+k,root*[2,2.5,3,2.25][Math.floor(k*2)%4]*lift,.22,.018,'sine');if(at>duration*.42)tone(at+.1,root*.5,.18,.025,'triangle')}return master}
async function muxer(){if(window.Mp4Muxer)return;await new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=ok;s.onerror=()=>fail(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s)})}
async function audioChunks(duration,config){const ac=new OfflineAudioContext(config.numberOfChannels,Math.ceil(duration*RATE),RATE);scheduleAudio(ac,ac.destination,duration);const b=await ac.startRendering(),chunks=[];let err;const enc=new AudioEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:e=>err=e});enc.configure(config);for(let off=0;off<b.length;off+=4800){const len=Math.min(4800,b.length-off),data=new Float32Array(len*config.numberOfChannels);for(let c=0;c<config.numberOfChannels;c++)data.set(b.getChannelData(c).subarray(off,off+len),c*len);const a=new AudioData({format:'f32-planar',sampleRate:RATE,numberOfFrames:len,numberOfChannels:config.numberOfChannels,timestamp:Math.round(off/RATE*1e6),data});enc.encode(a);a.close();if(enc.encodeQueueSize>14)await enc.flush()}await enc.flush();enc.close();if(err)throw err;return chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp).filter((x,i,a)=>!i||x.chunk.timestamp>a[i-1].chunk.timestamp)}
async function encode({duration,width,height,drawFrame,progress}){if(!window.VideoEncoder||!window.AudioEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await muxer();const vc={codec:'avc1.42001f',width,height,bitrate:height>width?3400000:3200000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(vc)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');let ac;for(const channels of [2,1]){const candidate={codec:'mp4a.40.2',sampleRate:RATE,numberOfChannels:channels,bitrate:128000};if((await AudioEncoder.isConfigSupported(candidate)).supported){ac=candidate;break}}if(!ac)throw Error('이 기기에서 오디오 저장을 지원하지 않습니다.');const out=document.createElement('canvas');out.width=width;out.height=height;const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width,height,frameRate:FPS},audio:{codec:'aac',numberOfChannels:ac.numberOfChannels,sampleRate:RATE},fastStart:'in-memory'}),audios=await audioChunks(duration,ac),videos=[];let err,enc=new VideoEncoder({output:(chunk,meta)=>videos.push({chunk,meta}),error:e=>err=e});try{enc.configure(vc);const total=Math.round(duration*FPS);for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(err)throw err;drawFrame(i/FPS,out);const frame=new VideoFrame(out,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});enc.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||enc.encodeQueueSize>6){progress(i/total);await new Promise(r=>setTimeout(r,0));while(enc.encodeQueueSize>6)await new Promise(r=>setTimeout(r,6))}}await enc.flush();if(err)throw err;videos.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const x of videos){if(x.chunk.timestamp<=last)continue;mux.addVideoChunk(x.chunk,x.meta);last=x.chunk.timestamp}last=-1;for(const x of audios){if(x.chunk.timestamp<=last)continue;mux.addAudioChunk(x.chunk,x.meta);last=x.chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(enc.state!=='closed')enc.close()}}
function textDownload(text,name){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000)}
function blobDownload(blob,name,kind){const u=URL.createObjectURL(blob),a=kind==='short'?$('short-ready'):$('long-ready');if(kind==='short'){if(shortURL)URL.revokeObjectURL(shortURL);shortURL=u}else{if(longURL)URL.revokeObjectURL(longURL);longURL=u}a.href=u;a.download=name;a.hidden=false;a.click()}
function lock(on){busy=on;for(const id of ['download-long','download-long-script','download-thumb','download-short','download-short-script'])$(id).disabled=on;$('cancel-export').hidden=!on}
$('cancel-export').onclick=()=>cancelled=true;
$('download-long-script').onclick=()=>textDownload(`${longTitle}\n\n${longNarration}\n\n※ 2026 IM HERO – THE STADIUM 2 공연 정보를 배경으로 한 팬 창작 이야기입니다.`, '일흔-살-엄마의-첫-스타디움-롱폼-나레이션.txt');
$('download-short-script').onclick=()=>textDownload(`${shortTitle}\n\n${shortNarration}`, '엄마가-다시-소녀가-됐습니다-쇼츠-나레이션.txt');
$('download-long').onclick=async()=>{if(busy)return;cancelled=false;lock(true);try{const blob=await encode({duration:LONG,width:1280,height:720,drawFrame:(t,c)=>renderGlobal(t,c,false),progress:p=>$('long-status').textContent=`롱폼 영상 만드는 중… ${Math.floor(p*100)}%`});blobDownload(blob,'일흔-살-엄마의-첫-스타디움-롱폼.mp4','long');$('long-status').textContent='1분 12초 롱폼 영상이 완성됐습니다.'}catch(e){$('long-status').textContent='롱폼 저장 오류: '+(e?.message||e)}finally{lock(false)}};
$('download-short').onclick=async()=>{if(busy)return;cancelled=false;lock(true);try{const blob=await encode({duration:SHORT,width:720,height:1280,drawFrame:(t,c)=>renderShort(t,c),progress:p=>$('short-status').textContent=`쇼츠 영상 만드는 중… ${Math.floor(p*100)}%`});blobDownload(blob,'엄마가-다시-소녀가-됐습니다-30초-쇼츠.mp4','short');$('short-status').textContent='30초 쇼츠 영상이 완성됐습니다.'}catch(e){$('short-status').textContent='쇼츠 저장 오류: '+(e?.message||e)}finally{lock(false)}};
$('download-thumb').onclick=async()=>{await document.fonts.ready;const c=document.createElement('canvas');c.width=1280;c.height=720;const g=c.getContext('2d');cover(g,backgrounds[4],1280,720,.5,1);const grad=g.createLinearGradient(0,0,930,0);grad.addColorStop(0,'rgba(4,23,40,.98)');grad.addColorStop(.68,'rgba(5,29,50,.68)');grad.addColorStop(1,'rgba(5,29,50,.04)');g.fillStyle=grad;g.fillRect(0,0,1280,720);draw(g,mother[10],1015,705,610);g.textAlign='left';g.textBaseline='middle';g.lineJoin='round';g.font='800 64px "Nanum Gothic",sans-serif';g.lineWidth=13;g.strokeStyle='#102b43';g.strokeText('일흔 살 엄마가',58,185);g.fillStyle='#fff';g.fillText('일흔 살 엄마가',58,185);g.font='800 98px "Nanum Gothic",sans-serif';g.lineWidth=16;g.strokeText('다시 소녀가 됐습니다',52,310);g.fillStyle='#ffd15a';g.fillText('다시 소녀가 됐습니다',52,310);g.fillStyle='#2b7fa9';round(g,60,392,625,72,36);g.fillStyle='#fff';g.font='800 33px "Nanum Gothic",sans-serif';g.fillText('처음 간 스타디움 콘서트',92,428);g.fillStyle='#a9e9ff';g.font='700 27px "Nanum Gothic",sans-serif';g.fillText('설렘 · 길 찾기 · 파란빛 · 눈물',63,548);g.fillStyle='#fff';g.font='700 29px "Nanum Gothic",sans-serif';g.fillText('엄마의 평생 잊지 못할 하루',63,608);c.toBlob(b=>blobDownload(b,'일흔-살-엄마의-첫-스타디움-썸네일.png','long'),'image/png')};
Promise.all([...bgFiles.map(async(f,i)=>backgrounds[i]=await image(f)),(async()=>mother.push(...extract(await image('assets/first-stadium/mother-actions.png'),4,3)))(),(async()=>friend.push(...extract(await image('assets/first-stadium/friend-actions.png'),4,2)))(),document.fonts.ready]).then(()=>{for(const id of ['download-long','download-long-script','download-thumb','download-short','download-short-script'])$(id).disabled=false;$('long-status').textContent='롱폼 영상·나레이션·썸네일을 다운로드할 수 있습니다.';$('short-status').textContent='30초 쇼츠 영상과 전체 나레이션을 다운로드할 수 있습니다.'}).catch(e=>{$('long-status').textContent='불러오기 실패: '+e.message;$('short-status').textContent='불러오기 실패: '+e.message});
window.addEventListener('beforeunload',()=>{if(longURL)URL.revokeObjectURL(longURL);if(shortURL)URL.revokeObjectURL(shortURL)});
})();
