(()=>{
'use strict';
const $=id=>document.getElementById(id),W=1280,H=720,CLIP=10,SHORT=30,FPS=30,RATE=48000;
const canvas=$('hero-stage'),shortCanvas=$('hero-short-stage'),ctx=canvas.getContext('2d'),shortCtx=shortCanvas.getContext('2d');
const sources={mix:'2025~2026년 공개 자료 종합',child:'한국백혈병어린이재단 · 2026.06.10',rice:'안양시 · 2026.06.15',pantry:'영등포쪽방상담소 관련 보도 · 2026.07.23',fire:'사랑의열매 관련 보도 · 2025.03.31',flood:'포천시 관련 보도 · 2025.08.08'};
const stories=[
 {title:'응원봉이 꺼진 뒤',year:'2025~2026',source:'mix',bg:0,summary:'공연이 끝난 뒤에도 계속된 영웅시대의 응원을 따라갑니다.',captions:['좋아해서 모였습니다','그 마음이 세상 밖으로 향했습니다'],tag:['팬심의 시작','더 큰 응원'],narration:'처음에는 한 사람의 노래가 좋아서 모였습니다. 그런데 그 마음은 공연장을 넘어 세상 밖으로 향했습니다.'},
 {title:'파란 봉사 조끼의 불빛',year:'2025~2026',source:'mix',bg:0,summary:'응원봉을 내려놓은 팬들이 도움이 필요한 곳으로 다시 모입니다.',captions:['응원봉을 내려놓고','봉사 조끼를 입었습니다'],tag:['공연은 끝나도','영웅시대 출동'],narration:'응원봉이 꺼진 뒤, 파란 봉사 조끼에 다시 불이 켜졌습니다. 영웅시대의 진짜 이야기는 여기서 시작됩니다.'},
 {title:'아이들의 내일을 응원하다',year:'2026.06',source:'child',bg:1,summary:'소아암 어린이 치료비와 히크만주머니를 전달한 나눔입니다.',captions:['치료비 500만 원 + 주머니 100개','아이들의 내일을 응원했습니다'],tag:['희망 전달','힘내요!'],narration:'2026년 6월, 영웅시대 광주전남은 소아암 어린이 치료비 500만 원과 히크만주머니 100개를 전달했습니다.'},
 {title:'6년 동안 이어진 마음',year:'2020~2026',source:'child',bg:1,summary:'한 번의 기부가 아니라 2020년부터 꾸준히 이어 온 약속입니다.',captions:['2020년부터 꾸준히','누적 후원 8,520만 원'],tag:['한 번이 아닌','6년의 약속'],narration:'이 나눔은 한 번으로 끝나지 않았습니다. 2020년부터 이어진 누적 후원금은 8천520만 원입니다.'},
 {title:'어르신 130가구의 밥상',year:'2026.06',source:'rice',bg:2,summary:'백미 1,300kg이 저소득 어르신 130가구에 전달됐습니다.',captions:['백미 1,300kg','어르신 130가구에 전달'],tag:['든든하게','따뜻한 한 끼'],narration:'2026년 6월에는 백미 1천300킬로그램을 기부했습니다. 쌀은 저소득 어르신 130가구의 따뜻한 밥상이 됐습니다.'},
 {title:'쪽방촌에 채워진 온기',year:'2026.07',source:'pantry',bg:3,summary:'무더위 속 쪽방촌 주민을 위한 식료품과 조미료를 지원했습니다.',captions:['쪽방촌 온기창고에 616만 원','여름 식료품을 채웠습니다'],tag:['온기 가득','시원한 응원'],narration:'2026년 7월에는 영등포 쪽방촌에 616만 원을 전했습니다. 무더운 여름을 날 식료품과 조미료를 채우기 위해서였습니다.'},
 {title:'산불 앞에서 더 크게 모이다',year:'2025.03',source:'fire',bg:4,summary:'대형 산불 피해 복구를 위해 팬들이 한마음으로 모였습니다.',captions:['산불 피해 성금','6억 912만 8,800원'],tag:['한마음','다시 피어날 희망'],narration:'큰 산불이 마을을 덮쳤을 때 영웅시대는 더 크게 모였습니다. 피해 복구를 위해 모은 성금은 6억 912만 8천800원이었습니다.'},
 {title:'수해 이웃의 다시 시작',year:'2025.08',source:'flood',bg:5,summary:'포천 수해 피해 이웃에게 다시 일어설 힘을 보탰습니다.',captions:['포천 수해 이웃에게','성금 1,000만 원'],tag:['함께 일어나요','회복의 힘'],narration:'집중호우로 피해를 입은 포천 이웃에게도 1천만 원을 전달했습니다. 어려운 순간마다 팬들의 마음은 먼저 달려갔습니다.'},
 {title:'전국에서 켜진 파란 불빛',year:'2025~2026',source:'mix',bg:6,summary:'서로 다른 지역의 작은 나눔이 하나의 커다란 빛으로 이어집니다.',captions:['지역은 달라도','나눔의 이름은 영웅시대'],tag:['전국이 반짝','마음은 하나'],narration:'지역도, 방법도, 돕는 이웃도 달랐습니다. 하지만 그 나눔에 적힌 이름은 언제나 영웅시대였습니다.'},
 {title:'이게 바로 영웅시대입니다',year:'2025~2026',source:'mix',bg:6,summary:'무대 위 영웅을 응원하던 사람들이 누군가의 영웅이 된 결말입니다.',captions:['팬으로 시작해','누군가의 영웅이 되었습니다'],tag:['가슴 벅찬 이름','이게 바로!'],narration:'무대 위 영웅을 응원하던 사람들이, 어느새 누군가의 영웅이 되었습니다. 가수의 이름을 빛내는 팬, 팬의 이름을 빛내는 나눔. 이게 바로 영웅시대입니다.'}
];
const shortNarration='가수를 좋아하는 마음이 누군가의 치료비가 되고, 어르신의 따뜻한 한 끼가 되고, 재난 속 이웃이 다시 일어설 힘이 됐습니다. 무대 위 영웅을 응원하던 사람들이, 어느새 누군가의 영웅이 되었습니다. 이게 바로 영웅시대입니다.';
const bgFiles=['assets/woong-rabbit/backgrounds/chapter-03-arena.webp','assets/heroic-age/backgrounds/hospital.webp','assets/heroic-age/backgrounds/rice.webp','assets/heroic-age/backgrounds/pantry.webp','assets/heroic-age/backgrounds/wildfire.webp','assets/heroic-age/backgrounds/flood.webp','assets/heroic-age/backgrounds/finale.webp'];
const backgrounds=[],rabbit={greeting:[],actions:[],walk:[]},fans=[],volunteers=[];
let selected=0,time=0,shortTime=0,raf=0,shortRaf=0,ready=false,busy=false,cancelled=false,audioContext,live={nodes:[],master:null},downloadURL='',shortURL='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>{t=clamp(t);return t*t*(3-2*t);},say=s=>$('hero-status').textContent=s,shortSay=s=>$('hero-short-status').textContent=s;
async function loadImage(src){const im=new Image();im.src=src;await im.decode();return im;}
function extract(im,cols,rows){const scan=document.createElement('canvas');scan.width=im.width;scan.height=im.height;const sg=scan.getContext('2d',{willReadFrequently:true});sg.drawImage(im,0,0);const d=sg.getImageData(0,0,scan.width,scan.height).data,out=[];for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const x0=Math.round(col*im.width/cols),x1=Math.round((col+1)*im.width/cols),y0=Math.round(row*im.height/rows),y1=Math.round((row+1)*im.height/rows);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*im.width+x)*4+3]>24){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}const c=document.createElement('canvas');c.width=Math.max(1,r-l+1);c.height=Math.max(1,b-t+1);c.getContext('2d').drawImage(im,l,t,c.width,c.height,0,0,c.width,c.height);out.push(c);}return out;}
function cover(g,im,w,h,focal=.5,zoom=1){const target=w/h,src=im.width/im.height;let sw,sh;if(src>target){sh=im.height/zoom;sw=sh*target;}else{sw=im.width/zoom;sh=sw/target;}const sx=clamp(im.width*focal-sw/2,0,im.width-sw),sy=(im.height-sh)/2;g.drawImage(im,sx,sy,sw,sh,0,0,w,h);}
function sprite(g,im,x,bottom,height,opt={}){const width=height*im.width/im.height;g.save();g.globalAlpha=opt.alpha??1;g.translate(x,bottom);g.rotate(opt.rotate||0);if(opt.flip)g.scale(-1,1);g.drawImage(im,-width/2,-height,width,height);g.restore();}
function pill(g,x,y,w,h,color){g.fillStyle=color;g.beginPath();g.roundRect(x,y,w,h,h/2);g.fill();}
function fit(g,text,max,width){let size=max;do{g.font=`800 ${size}px "Nanum Gothic", sans-serif`;if(g.measureText(text).width<=width)return size;size-=2;}while(size>28);return size;}
function actorMotion(index,t,g,w,h,vertical=false){const sx=w/W,sy=h/H,bottom=h-(vertical?88:18),finalGreeting=index===stories.length-1&&t>=3.4,bob=finalGreeting?0:Math.sin(t*4.4)*4*sy,walkFrame=Math.floor(t*7)%4,rs=vertical?560:410,vs=vertical?480:370;
 const r=(kind,frame,x,b,hh,flip=false,alpha=1)=>sprite(g,rabbit[kind][frame%rabbit[kind].length],x,b,hh,{flip,alpha,rotate:Math.sin(t*3)*.008});
 const v=(frame,x,b,hh,flip=false,alpha=1)=>sprite(g,volunteers[frame],x,b,hh,{flip,alpha,rotate:Math.sin(t*2.2+frame)*.007});
 const f=(frame,x,b,hh,flip=false,alpha=1)=>sprite(g,fans[frame],x,b,hh,{flip,alpha});
 if(vertical){const center=w/2;if(index===0){r('greeting',Math.floor(t*1.6)%6,center,bottom,rs);f(0,105,bottom,260);f(2,w-105,bottom,250,true);}else if(index===2){v(4,center+110,bottom,vs);r('actions',3,145,bottom,390);}else if(index===4){v(0,center-110,bottom,vs);v(1,center+155,bottom,430);}else if(index===6||index===7){v(index===6?3:1,center,bottom,vs);r('actions',4,130,bottom,350);}else{r('greeting',finalGreeting?4:Math.floor(t*1.8)%5,center,bottom,rs);v(5,115,bottom,360);f(5,w-95,bottom,245,true);}return;}
 switch(index){
  case 0:r('greeting',Math.floor(t*1.8)%6,w*.5,bottom+bob,rs);f(0,w*.16,bottom,270);f(2,w*.84,bottom,260,true);break;
  case 1:{const q=ease((t-3.8)/1.6);f(0,w*.23,bottom,300,false,1-q);f(5,w*.77,bottom,290,true,1-q);v(5,w*.29,bottom,vs,false,q);v(3,w*.72,bottom,vs,true,q);r('walk',4+walkFrame,mix(w*.48,w*.55,ease(t/10)),bottom+bob,rs*.9);break;}
  case 2:v(4,w*.73,bottom,vs);r('actions',3,w*.28,bottom+bob,rs);break;
  case 3:v(4,w*.5,bottom,vs);v(5,w*.18,bottom,vs*.82);v(5,w*.82,bottom,vs*.82,true);break;
  case 4:v(0,mix(w*.12,w*.36,ease(t/7)),bottom+bob,vs);v(1,mix(w*.92,w*.66,ease(t/8)),bottom,vs*1.06,true);r('walk',4+walkFrame,mix(w*.46,w*.54,ease(t/10)),bottom+bob,rs*.82);break;
  case 5:v(2,w*.34,bottom,vs);v(3,w*.69+Math.sin(t*1.6)*16,bottom,vs,true);r('actions',4,w*.52,bottom,rs*.76);break;
  case 6:v(3,mix(w*.18,w*.39,ease(t/7)),bottom+bob,vs);v(1,mix(w*.92,w*.68,ease(t/8)),bottom,vs,true);r('actions',4,w*.52,bottom,rs*.78);break;
  case 7:v(1,mix(w*.12,w*.42,ease(t/8)),bottom+bob,vs*1.08);v(3,w*.75,bottom,vs,true);r('walk',4+walkFrame,mix(w*.85,w*.61,ease(t/8)),bottom+bob,rs*.8,true);break;
  case 8:for(let i=0;i<5;i++)v(5,w*(.16+i*.17),bottom-(i%2)*16,vs*(.68+(i%2)*.08),i%2===1);r('greeting',4,w*.5,bottom-15,rs*.9);break;
  default:r('greeting',finalGreeting?4:Math.floor(t*1.8)%5,w*.5,bottom+bob,rs*1.05);v(5,w*.17,bottom,vs*.84);v(5,w*.83,bottom,vs*.84,true);f(1,w*.31,bottom,245);f(4,w*.69,bottom,245,true);
 }
}
function comicCaption(g,story,t,w,h){const beat=Math.min(1,Math.floor(t/5)),text=story.captions[beat],tag=story.tag[beat],enter=Math.min(1,(t%5)/.22),scale=1+Math.sin(enter*Math.PI)*.05,bw=Math.min(w*.72,920),bh=h*.18,x=(w-bw)/2,y=h*.09;g.save();g.translate(w/2,y+bh/2);g.scale(scale,scale);g.translate(-w/2,-y-bh/2);g.shadowColor='rgba(5,27,45,.3)';g.shadowBlur=18;g.shadowOffsetY=8;g.fillStyle='rgba(255,255,255,.96)';g.beginPath();g.roundRect(x,y,bw,bh,30);g.fill();g.shadowColor='transparent';g.lineWidth=6;g.strokeStyle='#24475d';g.stroke();pill(g,x+28,y-23,Math.min(260,bw*.34),46,beat?'#ffcc54':'#85d9f5');g.fillStyle='#173e58';g.font=`800 ${Math.max(17,h*.032)}px "Nanum Gothic", sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText(tag,x+28+Math.min(260,bw*.34)/2,y);const size=fit(g,text,h*.072,bw-54);g.font=`800 ${size}px "Nanum Gothic", sans-serif`;g.lineWidth=9;g.strokeStyle='#fff';g.strokeText(text,w/2,y+bh*.6);g.fillStyle='#203f53';g.fillText(text,w/2,y+bh*.6);g.restore();}
function sparkles(g,w,h,t,color='#8bdcff'){for(let i=0;i<18;i++){const x=(i*97+t*42)%w,y=h*.35+Math.sin(t*1.8+i*2.1)*h*.25,a=.18+.28*(.5+.5*Math.sin(t*4+i));g.globalAlpha=a;g.fillStyle=i%3?color:'#fff';g.beginPath();g.arc(x,y,2+i%3,0,Math.PI*2);g.fill();}g.globalAlpha=1;}
function renderScene(index,t,target=canvas){const g=target.getContext('2d'),w=target.width,h=target.height,story=stories[index];g.clearRect(0,0,w,h);cover(g,backgrounds[story.bg],w,h,.5,1+.035*ease(t/CLIP));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,25,42,.32)');shade.addColorStop(.58,'rgba(5,25,42,.02)');shade.addColorStop(1,'rgba(4,20,35,.42)');g.fillStyle=shade;g.fillRect(0,0,w,h);actorMotion(index,t,g,w,h,false);sparkles(g,w,h,t,index>7?'#ffd45d':'#8bdcff');if($('hero-captions').checked)comicCaption(g,story,t,w,h);pill(g,w*.26,h-40,w*.48,28,'rgba(7,32,53,.72)');g.fillStyle='#fff';g.font=`700 ${Math.max(12,h*.021)}px "Nanum Gothic", sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText(sources[story.source],w/2,h-26);const fade=Math.max(0,1-(t%5)/.2);if(fade){g.fillStyle=`rgba(255,255,255,${fade*.2})`;g.fillRect(0,0,w,h);}target.dataset.scene=String(index+1);if(target===canvas){$('hero-seek').value=Math.round(t*100);$('hero-clock').textContent=`0:${String(Math.floor(t)).padStart(2,'0')} / 0:10`;}}
const shortMap=[0,2,4,6,9],shortLines=[['좋아하는 마음이','세상 밖으로 향했습니다'],['누군가의 치료비와','아이들의 내일이 되고'],['어르신의 따뜻한','한 끼가 되고'],['재난 속 이웃이','다시 일어설 힘이 되고'],['팬으로 시작해','누군가의 영웅이 되었습니다']];
function renderShort(t,target=shortCanvas){const g=target.getContext('2d'),w=target.width,h=target.height,index=Math.min(4,Math.floor(t/6)),storyIndex=shortMap[index],local=t-index*6,story=stories[storyIndex],lines=shortLines[index];g.clearRect(0,0,w,h);cover(g,backgrounds[story.bg],w,h,.5,1+.05*ease(local/6));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,24,42,.74)');shade.addColorStop(.35,'rgba(5,24,42,.08)');shade.addColorStop(1,'rgba(4,20,35,.78)');g.fillStyle=shade;g.fillRect(0,0,w,h);actorMotion(storyIndex,local,g,w,h,true);sparkles(g,w,h,t,index===4?'#ffd45d':'#8bdcff');pill(g,52,54,w-104,58,'rgba(255,255,255,.94)');g.fillStyle='#285873';g.font='800 24px "Nanum Gothic", sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(index===4?'이게 바로 영웅시대':'좋아하는 마음이 만든 기적',w/2,83);g.lineJoin='round';for(let i=0;i<2;i++){const closing=index===4&&local>3.5&&i===1?'이게 바로 영웅시대':lines[i],size=fit(g,closing,i?62:54,w-70),y=185+i*80;g.font=`800 ${size}px "Nanum Gothic", sans-serif`;g.lineWidth=12;g.strokeStyle='rgba(6,28,47,.92)';g.strokeText(closing,w/2,y);g.fillStyle=i===1?'#ffd45d':'#fff';g.fillText(closing,w/2,y);}pill(g,45,h-80,w-90,48,'rgba(7,32,53,.78)');g.fillStyle='#fff';g.font='700 19px "Nanum Gothic", sans-serif';g.fillText(index===4?'팬의 이름을 빛내는 나눔':sources[story.source],w/2,h-56);g.fillStyle='#8bdcff';g.fillRect(0,0,w*t/SHORT,8);g.fillStyle='rgba(255,255,255,.25)';g.fillRect(w*t/SHORT,0,w,8);const fade=Math.max(0,1-local/.25);if(fade){g.fillStyle=`rgba(255,255,255,${fade*.22})`;g.fillRect(0,0,w,h);}target.dataset.segment=String(index+1);if(target===shortCanvas){$('hero-short-seek').value=Math.round(t*100);$('hero-short-clock').textContent=`0:${String(Math.floor(t)).padStart(2,'0')} / 0:30`;}}
function scheduleAudio(ac,destination,duration,startAt=0,offset=0,seed=0){const master=ac.createGain(),nodes=[];master.gain.value=Number($('hero-volume').value)/100*.82;master.connect(destination);const tone=(at,f,d=.5,g=.035,type='sine')=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=startAt+begin-offset,remain=at+d-begin,o=ac.createOscillator(),v=ac.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,when);v.gain.exponentialRampToValueAtTime(g,when+.025);v.gain.exponentialRampToValueAtTime(.0001,when+remain);o.connect(v).connect(master);o.start(when);o.stop(when+remain+.02);nodes.push(o);};const noise=(at,d=.18,g=.02)=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=startAt+begin-offset,len=Math.ceil((at+d-begin)*ac.sampleRate),b=ac.createBuffer(1,len,ac.sampleRate),data=b.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.sin((i+1)*(seed+3)*71.17)*Math.pow(1-i/len,2);const s=ac.createBufferSource(),f=ac.createBiquadFilter(),v=ac.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=720;v.gain.value=g;s.connect(f).connect(v).connect(master);s.start(when);nodes.push(s);};const roots=[196,220,246.9,261.6,174.6];for(let at=0,part=0;at<duration;at+=5,part++){const root=roots[(part+seed)%roots.length];for(const n of [root,root*1.25,root*1.5])tone(at,n,4.85,.016,'triangle');tone(at+.08,root*3,.4,.05);tone(at+.2,root*4,.45,.025);noise(at,.25,.027);for(let k=.75;k<4.8;k+=.72)tone(at+k,root*[2,2.5,3,2.25][Math.floor(k*2)%4],.18,.018);}return {nodes,master};}
function silence(){for(const n of live.nodes)try{n.stop();}catch{}live={nodes:[],master:null};}
async function sound(from,duration,seed){silence();if(!$('hero-sound').checked)return;const AC=window.AudioContext||window.webkitAudioContext;audioContext??=new AC({sampleRate:RATE});await audioContext.resume();live=scheduleAudio(audioContext,audioContext.destination,duration,audioContext.currentTime+.04,from,seed);}
function stop(){cancelAnimationFrame(raf);raf=0;silence();$('hero-play').textContent='▶ 재생';}
function stopShort(){cancelAnimationFrame(shortRaf);shortRaf=0;silence();$('hero-short-play').textContent='▶ 쇼츠 미리보기';}
function choose(index){stop();selected=index;time=0;document.querySelectorAll('.story-card').forEach((b,i)=>b.classList.toggle('active',i===index));const s=stories[index];$('hero-label').textContent=`SCENE ${String(index+1).padStart(2,'0')} · 10초`;$('hero-heading').textContent=s.title;$('hero-summary').textContent=s.summary;$('hero-year').textContent=s.year;$('hero-source').textContent=sources[s.source];$('hero-narration').textContent=s.narration;renderScene(index,0);say(`${index+1}번 장면이 준비되었습니다.`);}
function cards(){stories.forEach((s,i)=>{const b=document.createElement('button');b.className='story-card';b.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span>${s.title}<small>${s.year} · 10초</small></span>`;b.onclick=()=>choose(i);$('hero-story-list').append(b);});}
$('hero-play').onclick=async()=>{if(raf){stop();return;}if(time>=CLIP-.02)time=0;await sound(time,CLIP,selected);const start=performance.now()-time*1000;const tick=now=>{time=clamp((now-start)/1000,0,CLIP);renderScene(selected,time);if(time>=CLIP){stop();return;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);$('hero-play').textContent='Ⅱ 일시정지';};
$('hero-short-play').onclick=async()=>{if(shortRaf){stopShort();return;}if(shortTime>=SHORT-.02)shortTime=0;await sound(shortTime,SHORT,7);const start=performance.now()-shortTime*1000;const tick=now=>{shortTime=clamp((now-start)/1000,0,SHORT);renderShort(shortTime);if(shortTime>=SHORT){stopShort();return;}shortRaf=requestAnimationFrame(tick);};shortRaf=requestAnimationFrame(tick);$('hero-short-play').textContent='Ⅱ 일시정지';};
$('hero-seek').oninput=()=>{stop();time=Number($('hero-seek').value)/100;renderScene(selected,time);};$('hero-short-seek').oninput=()=>{stopShort();shortTime=Number($('hero-short-seek').value)/100;renderShort(shortTime);};$('hero-captions').onchange=()=>renderScene(selected,time);$('hero-sound').onchange=()=>{stop();stopShort();};$('hero-volume').oninput=()=>{if(live.master&&audioContext)live.master.gain.setTargetAtTime(Number($('hero-volume').value)/100*.82,audioContext.currentTime,.04);};
async function muxer(){if(window.Mp4Muxer)return;await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=r;s.onerror=()=>j(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s);});}
async function audioChunks(duration,config,seed){const ch=config.numberOfChannels,oac=new OfflineAudioContext(ch,Math.ceil(duration*RATE),RATE);scheduleAudio(oac,oac.destination,duration,0,0,seed);const b=await oac.startRendering(),chunks=[];let fail;const e=new AudioEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:x=>fail=x});e.configure(config);for(let off=0,step=4800;off<b.length;off+=step){const len=Math.min(step,b.length-off),data=new Float32Array(len*ch);for(let c=0;c<ch;c++)data.set(b.getChannelData(c).subarray(off,off+len),c*len);const a=new AudioData({format:'f32-planar',sampleRate:RATE,numberOfFrames:len,numberOfChannels:ch,timestamp:Math.round(off/RATE*1e6),data});e.encode(a);a.close();if(e.encodeQueueSize>16)await e.flush();}await e.flush();e.close();if(fail)throw fail;return chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp).filter(({chunk},i,list)=>i===0||chunk.timestamp>list[i-1].chunk.timestamp);}
async function encodeVideo({duration,width,height,draw,seed,onProgress}){if(!window.VideoEncoder||($('hero-sound').checked&&!window.AudioEncoder))throw Error('최신 Chrome 또는 Edge에서 저장해 주세요.');await muxer();const video={codec:'avc1.42001f',width,height,bitrate:height>width?3200000:3000000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(video)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');let audio=null;if($('hero-sound').checked)for(const channels of [2,1]){const c={codec:'mp4a.40.2',sampleRate:RATE,numberOfChannels:channels,bitrate:128000};if((await AudioEncoder.isConfigSupported(c)).supported){audio=c;break;}}const out=document.createElement('canvas');out.width=width;out.height=height;const target=new Mp4Muxer.ArrayBufferTarget(),m=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width,height,frameRate:FPS},...(audio?{audio:{codec:'aac',numberOfChannels:audio.numberOfChannels,sampleRate:RATE}}:{}),fastStart:'in-memory'}),sounds=audio?await audioChunks(duration,audio,seed):[],videos=[];let fail,enc;try{enc=new VideoEncoder({output:(chunk,meta)=>videos.push({chunk,meta}),error:e=>fail=e});enc.configure(video);const total=Math.round(duration*FPS);for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(fail)throw fail;draw(i/FPS,out);const f=new VideoFrame(out,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});enc.encode(f,{keyFrame:i%(FPS*2)===0});f.close();if(i%8===0||enc.encodeQueueSize>6){onProgress(i/total);await new Promise(r=>setTimeout(r,0));while(enc.encodeQueueSize>6)await new Promise(r=>setTimeout(r,8));}}await enc.flush();if(fail)throw fail;videos.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const {chunk,meta} of videos){if(chunk.timestamp<=last)continue;m.addVideoChunk(chunk,meta);last=chunk.timestamp;}last=-1;for(const {chunk,meta} of sounds){if(chunk.timestamp<=last)continue;m.addAudioChunk(chunk,meta);last=chunk.timestamp;}m.finalize();return new Blob([target.buffer],{type:'video/mp4'});}finally{if(enc&&enc.state!=='closed')enc.close();}}
function lock(on){busy=on;for(const id of ['hero-play','hero-export','hero-export-all','hero-short-play','hero-short-export','hero-script','hero-thumbnail','hero-seek','hero-short-seek'])$(id).disabled=on;$('hero-cancel').hidden=!on;}
function download(blob,name,kind='long'){const url=URL.createObjectURL(blob),a=kind==='short'?$('hero-short-download'):$('hero-download');if(kind==='short'){if(shortURL)URL.revokeObjectURL(shortURL);shortURL=url;}else{if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;}a.href=url;a.download=name;a.hidden=false;a.click();}
function restore(message){lock(false);renderScene(selected,0);renderShort(0);say(message);}
$('hero-cancel').onclick=()=>cancelled=true;
$('hero-export').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);const index=selected;try{const blob=await encodeVideo({duration:CLIP,width:1280,height:720,draw:(t,c)=>renderScene(index,t,c),seed:index,onProgress:p=>say(`${index+1}번 장면 저장 중… ${Math.floor(p*100)}%`)});download(blob,`영웅시대-미담-${String(index+1).padStart(2,'0')}-${stories[index].title}.mp4`);restore('선택한 10초 장면을 저장했습니다.');}catch(e){restore('저장 오류: '+(e?.message||e));}};
$('hero-export-all').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);try{const duration=stories.length*CLIP,blob=await encodeVideo({duration,width:1280,height:720,draw:(t,c)=>{const i=Math.min(stories.length-1,Math.floor(t/CLIP));renderScene(i,t-i*CLIP,c);},seed:12,onProgress:p=>say(`1분 40초 롱폼 저장 중… ${Math.floor(p*100)}%`)});download(blob,'이게-바로-영웅시대입니다-롱폼.mp4');restore('음악과 효과음이 포함된 1분 40초 롱폼을 저장했습니다.');}catch(e){restore('롱폼 저장 오류: '+(e?.message||e));}};
$('hero-short-export').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);try{const blob=await encodeVideo({duration:SHORT,width:720,height:1280,draw:(t,c)=>renderShort(t,c),seed:7,onProgress:p=>shortSay(`30초 쇼츠 저장 중… ${Math.floor(p*100)}%`)});download(blob,'이게-바로-영웅시대입니다-30초-쇼츠.mp4','short');restore('30초 쇼츠를 저장했습니다.');shortSay('음악과 효과음이 포함된 30초 세로 쇼츠를 저장했습니다.');}catch(e){restore('쇼츠 저장 오류: '+(e?.message||e));shortSay('쇼츠 저장 오류: '+(e?.message||e));}};
$('hero-script').onclick=()=>{const text=['이게 바로 영웅시대입니다','팬으로 시작해 누군가의 영웅이 된 사람들','','[롱폼 전체 나레이션]',...stories.flatMap((s,i)=>['',`${i+1}. ${s.title} · ${s.year}`,s.narration,`출처: ${sources[s.source]}`]),'','[30초 쇼츠 나레이션]',shortNarration].join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='이게-바로-영웅시대-전체-나레이션.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);};
$('hero-thumbnail').onclick=async()=>{await document.fonts.ready;const c=document.createElement('canvas');c.width=1280;c.height=720;const g=c.getContext('2d');cover(g,backgrounds[6],1280,720,.5,1);const shade=g.createLinearGradient(0,0,900,0);shade.addColorStop(0,'rgba(4,22,39,.96)');shade.addColorStop(.62,'rgba(5,30,51,.72)');shade.addColorStop(1,'rgba(5,30,51,.08)');g.fillStyle=shade;g.fillRect(0,0,1280,720);sprite(g,rabbit.greeting[4],935,705,620);sprite(g,volunteers[5],1160,700,315,{flip:true});g.textAlign='left';g.textBaseline='middle';g.lineJoin='round';g.font='800 72px "Nanum Gothic", sans-serif';g.lineWidth=12;g.strokeStyle='#10263b';g.strokeText('이게 바로',62,208);g.fillStyle='#fff';g.fillText('이게 바로',62,208);g.font='800 112px "Nanum Gothic", sans-serif';g.lineWidth=15;g.strokeText('영웅시대',58,335);g.fillStyle='#ffd45d';g.fillText('영웅시대',58,335);pill(g,62,408,650,72,'#2384b7');g.fillStyle='#fff';g.font='800 34px "Nanum Gothic", sans-serif';g.fillText('팬으로 시작해 누군가의 영웅이 되다',91,445);g.fillStyle='#9fe6ff';g.font='700 25px "Nanum Gothic", sans-serif';g.fillText('치료비 · 따뜻한 한 끼 · 재난 복구',66,550);g.fillStyle='#fff';g.font='700 28px "Nanum Gothic", sans-serif';g.fillText('좋아하는 마음이 만든 기적',66,606);c.toBlob(blob=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='이게-바로-영웅시대-썸네일.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);},'image/png');};
window.addEventListener('beforeunload',()=>{stop();stopShort();if(downloadURL)URL.revokeObjectURL(downloadURL);if(shortURL)URL.revokeObjectURL(shortURL);});
cards();Promise.all([
 ...bgFiles.map(async(file,i)=>backgrounds[i]=await loadImage(file)),
 ...[['greeting','greeting.png',3,2],['actions','actions.png',3,2],['walk','walk-cardinal.png',4,4]].map(async([name,file,cols,rows])=>rabbit[name]=extract(await loadImage(`assets/woong-rabbit/${file}`),cols,rows)),
 (async()=>fans.push(...extract(await loadImage('assets/woong-rabbit/fans-korean-60s.webp'),3,2)))(),
 (async()=>volunteers.push(...extract(await loadImage('assets/heroic-age/volunteer-actions.png'),3,2)))(),document.fonts.ready
]).then(()=>{ready=true;for(const id of ['hero-play','hero-export','hero-export-all','hero-short-play','hero-short-export','hero-script','hero-thumbnail'])$(id).disabled=false;choose(0);renderShort(0);shortSay('30초 쇼츠가 준비되었습니다.');}).catch(e=>{say('불러오기 실패: '+e.message);shortSay('불러오기 실패: '+e.message);});
})();
