(()=>{
'use strict';
const $=id=>document.getElementById(id),W=1280,H=720,CLIP=10,SHORT=30,FPS=30,RATE=48000;
const canvas=$('hero-stage'),shortCanvas=$('hero-short-stage'),ctx=canvas.getContext('2d'),shortCtx=shortCanvas.getContext('2d');
const sources={contest:'교수신문 · 경복대학교 제3회 히어로 콘테스트 · 2026.08.23'};
const stories=[
 {title:'아무도 없는 연습실',year:'2026.08',source:'contest',bg:0,summary:'노래를 좋아하는 한 학생이 늦은 시간까지 혼자 꿈을 준비합니다.',captions:['아무도 없는 연습실','그래도 노래는 멈추지 않았습니다'],tag:['꿈의 시작','오늘도 한 번 더'],narration:'노래가 좋아 매일 연습실에 남는 한 학생이 있었습니다. 들어 주는 사람이 없어도, 언젠가 무대에 설 날을 믿으며 노래했습니다.'},
 {title:'기회가 필요했습니다',year:'2026.08',source:'contest',bg:0,summary:'실력보다 먼저 필요한 것은 자신의 노래를 들려줄 한 번의 기회였습니다.',captions:['꿈은 준비됐지만','무대는 아직 멀었습니다'],tag:['막막한 현실','딱 한 번의 기회'],narration:'하지만 꿈만으로 무대가 생기지는 않았습니다. 이 학생에게 필요했던 것은 거창한 약속이 아니라, 자신의 노래를 들려줄 단 한 번의 기회였습니다.'},
 {title:'팬들이 움직였습니다',year:'2026.08',source:'contest',bg:1,summary:'영웅시대가 청년들의 꿈을 위한 새로운 응원을 준비합니다.',captions:['이번에는 우리가','꿈의 무대를 만들어요!'],tag:['작전 회의','영웅시대 출동'],narration:'그때 영웅시대가 움직였습니다. 한 가수를 향해 보내던 응원을, 이제 가수를 꿈꾸는 청년들에게도 나누기로 했습니다.'},
 {title:'3,500만 원의 응원',year:'2026.08',source:'contest',bg:1,summary:'데뷔 10주년을 기념해 실용음악과 발전기금 3,500만 원을 전달했습니다.',captions:['데뷔 10주년을 기념해','발전기금 3,500만 원'],tag:['마음이 모이면','꿈의 밑거름'],narration:'임영웅의 데뷔 10주년을 기념해 팬들은 실용음악과 발전기금 3천500만 원을 전했습니다. 누군가의 내일을 응원하는 마음이었습니다.'},
 {title:'무대 뒤, 떨리는 순간',year:'2026.08.23',source:'contest',bg:2,summary:'제3회 히어로 콘테스트 당일, 학생은 떨리는 마음으로 순서를 기다립니다.',captions:['심장이 쿵! 쿵!','괜찮아, 네 노래를 들려줘'],tag:['무대 10초 전','따뜻한 한마디'],narration:'드디어 히어로 콘테스트가 열렸습니다. 무대 뒤 학생의 심장은 빠르게 뛰었습니다. 팬들은 조용히 말했습니다. 괜찮아, 네 노래를 들려줘.'},
 {title:'꿈이 노래가 된 순간',year:'2026.08.23',source:'contest',bg:3,summary:'학생들이 자신의 목소리로 무대를 채우고 관객은 끝까지 귀를 기울입니다.',captions:['마침내 시작된 노래','객석이 조용히 귀를 기울였습니다'],tag:['첫 소절','꿈이 빛나는 순간'],narration:'첫 소절이 울리자 떨림은 노래가 되었습니다. 참가 학생들은 저마다의 목소리로 무대를 채웠고, 팬들은 그 꿈을 끝까지 들어 주었습니다.'},
 {title:'새로운 영웅의 탄생',year:'2026.08.23',source:'contest',bg:4,summary:'모래 알갱이를 부른 학생이 대상을 받고 모든 참가자의 도전에 박수가 쏟아집니다.',captions:['대상은 ‘모래 알갱이’ 무대','모든 도전에 박수를 보냈습니다'],tag:['가슴 벅찬 결과','오늘의 주인공'],narration:'대상은 임영웅의 모래 알갱이를 부른 학생에게 돌아갔습니다. 그러나 이날의 박수는 수상자 한 명이 아니라, 무대에 오른 모든 꿈을 향했습니다.'},
 {title:'이게 영웅시대의 응원법',year:'2026.08.23',source:'contest',bg:5,summary:'한 영웅을 응원하던 빛이 또 다른 꿈들의 시작을 밝힙니다.',captions:['한 영웅을 향했던 응원이','또 다른 꿈을 밝혔습니다'],tag:['응원의 확장','이게 영웅시대'],narration:'한 영웅을 응원하던 파란빛이 이제 또 다른 꿈의 시작을 비춥니다. 좋아하는 마음으로 사람을 키우는 것. 이게 영웅시대의 응원법입니다.'}
];
const shortNarration='노래가 좋아 매일 혼자 연습하던 한 학생. 영웅시대는 그 꿈이 세상 밖으로 나올 무대를 만들었습니다. 한 영웅을 응원하던 마음이 또 다른 꿈의 시작을 밝혔습니다. 이게 영웅시대의 응원법입니다.';
const bgFiles=['assets/hero-contest/backgrounds/practice.webp','assets/hero-contest/backgrounds/planning.webp','assets/hero-contest/backgrounds/backstage.webp','assets/hero-contest/backgrounds/stage.webp','assets/hero-contest/backgrounds/award.webp','assets/hero-contest/backgrounds/finale.webp'];
const backgrounds=[],students=[],fans=[];
let selected=0,time=0,shortTime=0,raf=0,shortRaf=0,ready=false,busy=false,cancelled=false,audioContext,live={nodes:[],master:null},downloadURL='',shortURL='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>{t=clamp(t);return t*t*(3-2*t);},say=s=>$('hero-status').textContent=s,shortSay=s=>$('hero-short-status').textContent=s;
async function loadImage(src){const im=new Image();im.src=src;await im.decode();return im;}
function extract(im,cols,rows){const scan=document.createElement('canvas');scan.width=im.width;scan.height=im.height;const sg=scan.getContext('2d',{willReadFrequently:true});sg.drawImage(im,0,0);const d=sg.getImageData(0,0,scan.width,scan.height).data,out=[];for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const x0=Math.round(col*im.width/cols),x1=Math.round((col+1)*im.width/cols),y0=Math.round(row*im.height/rows),y1=Math.round((row+1)*im.height/rows);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*im.width+x)*4+3]>24){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}const c=document.createElement('canvas');c.width=Math.max(1,r-l+1);c.height=Math.max(1,b-t+1);c.getContext('2d').drawImage(im,l,t,c.width,c.height,0,0,c.width,c.height);out.push(c);}return out;}
function cover(g,im,w,h,focal=.5,zoom=1){const target=w/h,src=im.width/im.height;let sw,sh;if(src>target){sh=im.height/zoom;sw=sh*target;}else{sw=im.width/zoom;sh=sw/target;}const sx=clamp(im.width*focal-sw/2,0,im.width-sw),sy=(im.height-sh)/2;g.drawImage(im,sx,sy,sw,sh,0,0,w,h);}
function sprite(g,im,x,bottom,height,opt={}){const width=height*im.width/im.height;g.save();g.globalAlpha=opt.alpha??1;g.translate(x,bottom);g.rotate(opt.rotate||0);if(opt.flip)g.scale(-1,1);g.drawImage(im,-width/2,-height,width,height);g.restore();}
function pill(g,x,y,w,h,color){g.fillStyle=color;g.beginPath();g.roundRect(x,y,w,h,h/2);g.fill();}
function fit(g,text,max,width){let size=max;do{g.font=`800 ${size}px "Nanum Gothic", sans-serif`;if(g.measureText(text).width<=width)return size;size-=2;}while(size>28);return size;}
function actorMotion(index,t,g,w,h,vertical=false){
 const bottom=h-(vertical?94:18),bob=Math.sin(t*3.8)*3,studentH=vertical?560:470,fanH=vertical?480:400;
 const s=(frame,x,b=bottom,hh=studentH,opt={})=>sprite(g,students[frame],x,b+Math.sin(t*3.2+frame)*2,hh,{...opt,rotate:(opt.rotate||0)+Math.sin(t*2.5+frame)*.006});
 const f=(frame,x,b=bottom,hh=fanH,opt={})=>sprite(g,fans[frame],x,b+Math.sin(t*2.7+frame)*2,hh,{...opt,rotate:(opt.rotate||0)+Math.sin(t*2.1+frame)*.005});
 const center=w/2;
 if(vertical){
  if(index<2)s(index?1:0,center);
  else if(index<4){f(index===2?0:2,center+100);f(1,115,bottom,330);}
  else if(index===4){s(1,center+70);f(2,110,bottom,350);}
  else if(index===5)s(3,center);
  else if(index===6){s(5,center+65);f(3,120,bottom,350);}
  else{s(5,center+70);f(5,120,bottom,370);}
  return;
 }
 switch(index){
  case 0:s(0,center,bottom+bob);break;
  case 1:s(1,center,bottom+bob);break;
  case 2:f(0,w*.34);f(2,w*.68,bottom,fanH,{flip:true});break;
  case 3:f(0,w*.25);f(2,w*.5);f(3,w*.76,bottom,fanH,{flip:true});break;
  case 4:{const p=ease(t/8);s(2,mix(w*.18,w*.52,p),bottom+bob,studentH,{flip:false});f(2,w*.76);break;}
  case 5:s(3,center,bottom+bob,studentH*1.05);f(3,w*.16,bottom,fanH*.72);f(3,w*.84,bottom,fanH*.72,{flip:true});break;
  case 6:s(t<5?4:5,center,bottom+bob);f(3,w*.2,bottom,fanH*.82);f(4,w*.8,bottom,fanH*.82,{flip:true});break;
  default:s(5,w*.57,bottom+bob);f(5,w*.28,bottom,fanH*.95);f(3,w*.82,bottom,fanH*.76,{flip:true});
 }
}
function comicCaption(g,story,t,w,h){const beat=Math.min(1,Math.floor(t/5)),text=story.captions[beat],tag=story.tag[beat],enter=Math.min(1,(t%5)/.22),scale=1+Math.sin(enter*Math.PI)*.05,bw=Math.min(w*.72,920),bh=h*.18,x=(w-bw)/2,y=h*.09;g.save();g.translate(w/2,y+bh/2);g.scale(scale,scale);g.translate(-w/2,-y-bh/2);g.shadowColor='rgba(5,27,45,.3)';g.shadowBlur=18;g.shadowOffsetY=8;g.fillStyle='rgba(255,255,255,.96)';g.beginPath();g.roundRect(x,y,bw,bh,30);g.fill();g.shadowColor='transparent';g.lineWidth=6;g.strokeStyle='#24475d';g.stroke();pill(g,x+28,y-23,Math.min(260,bw*.34),46,beat?'#ffcc54':'#85d9f5');g.fillStyle='#173e58';g.font=`800 ${Math.max(17,h*.032)}px "Nanum Gothic", sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText(tag,x+28+Math.min(260,bw*.34)/2,y);const size=fit(g,text,h*.072,bw-54);g.font=`800 ${size}px "Nanum Gothic", sans-serif`;g.lineWidth=9;g.strokeStyle='#fff';g.strokeText(text,w/2,y+bh*.6);g.fillStyle='#203f53';g.fillText(text,w/2,y+bh*.6);g.restore();}
function sparkles(g,w,h,t,color='#8bdcff'){for(let i=0;i<18;i++){const x=(i*97+t*42)%w,y=h*.35+Math.sin(t*1.8+i*2.1)*h*.25,a=.18+.28*(.5+.5*Math.sin(t*4+i));g.globalAlpha=a;g.fillStyle=i%3?color:'#fff';g.beginPath();g.arc(x,y,2+i%3,0,Math.PI*2);g.fill();}g.globalAlpha=1;}
function renderScene(index,t,target=canvas){const g=target.getContext('2d'),w=target.width,h=target.height,story=stories[index];g.clearRect(0,0,w,h);cover(g,backgrounds[story.bg],w,h,.5,1+.035*ease(t/CLIP));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,25,42,.32)');shade.addColorStop(.58,'rgba(5,25,42,.02)');shade.addColorStop(1,'rgba(4,20,35,.42)');g.fillStyle=shade;g.fillRect(0,0,w,h);actorMotion(index,t,g,w,h,false);sparkles(g,w,h,t,index>7?'#ffd45d':'#8bdcff');if($('hero-captions').checked)comicCaption(g,story,t,w,h);pill(g,w*.26,h-40,w*.48,28,'rgba(7,32,53,.72)');g.fillStyle='#fff';g.font=`700 ${Math.max(12,h*.021)}px "Nanum Gothic", sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText(sources[story.source],w/2,h-26);const fade=Math.max(0,1-(t%5)/.2);if(fade){g.fillStyle=`rgba(255,255,255,${fade*.2})`;g.fillRect(0,0,w,h);}target.dataset.scene=String(index+1);if(target===canvas){$('hero-seek').value=Math.round(t*100);$('hero-clock').textContent=`0:${String(Math.floor(t)).padStart(2,'0')} / 0:10`;}}
const shortMap=[0,2,4,5,7],shortLines=[['아무도 없는 연습실','그래도 꿈은 멈추지 않았습니다'],['팬들이 움직였습니다','꿈의 무대를 만들기 위해'],['떨리는 무대 뒤','괜찮아, 네 노래를 들려줘'],['첫 소절이 울리자','꿈이 노래가 됐습니다'],['한 영웅을 향했던 응원이','또 다른 꿈을 밝혔습니다']];
function renderShort(t,target=shortCanvas){const g=target.getContext('2d'),w=target.width,h=target.height,index=Math.min(4,Math.floor(t/6)),storyIndex=shortMap[index],local=t-index*6,story=stories[storyIndex],lines=shortLines[index];g.clearRect(0,0,w,h);cover(g,backgrounds[story.bg],w,h,.5,1+.05*ease(local/6));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,24,42,.74)');shade.addColorStop(.35,'rgba(5,24,42,.08)');shade.addColorStop(1,'rgba(4,20,35,.78)');g.fillStyle=shade;g.fillRect(0,0,w,h);actorMotion(storyIndex,local,g,w,h,true);sparkles(g,w,h,t,index===4?'#ffd45d':'#8bdcff');pill(g,52,54,w-104,58,'rgba(255,255,255,.94)');g.fillStyle='#285873';g.font='800 24px "Nanum Gothic", sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(index===4?'이게 영웅시대의 응원법':'팬들이 만든 꿈의 무대',w/2,83);g.lineJoin='round';for(let i=0;i<2;i++){const closing=index===4&&local>3.5&&i===1?'이게 바로 영웅시대':lines[i],size=fit(g,closing,i?62:54,w-70),y=185+i*80;g.font=`800 ${size}px "Nanum Gothic", sans-serif`;g.lineWidth=12;g.strokeStyle='rgba(6,28,47,.92)';g.strokeText(closing,w/2,y);g.fillStyle=i===1?'#ffd45d':'#fff';g.fillText(closing,w/2,y);}pill(g,45,h-80,w-90,48,'rgba(7,32,53,.78)');g.fillStyle='#fff';g.font='700 19px "Nanum Gothic", sans-serif';g.fillText(index===4?'한 사람의 응원이 또 다른 꿈으로':sources[story.source],w/2,h-56);g.fillStyle='#8bdcff';g.fillRect(0,0,w*t/SHORT,8);g.fillStyle='rgba(255,255,255,.25)';g.fillRect(w*t/SHORT,0,w,8);const fade=Math.max(0,1-local/.25);if(fade){g.fillStyle=`rgba(255,255,255,${fade*.22})`;g.fillRect(0,0,w,h);}target.dataset.segment=String(index+1);if(target===shortCanvas){$('hero-short-seek').value=Math.round(t*100);$('hero-short-clock').textContent=`0:${String(Math.floor(t)).padStart(2,'0')} / 0:30`;}}
function scheduleAudio(ac,destination,duration,startAt=0,offset=0,seed=0){const master=ac.createGain(),nodes=[];master.gain.value=Number($('hero-volume').value)/100*.82;master.connect(destination);const tone=(at,f,d=.5,g=.035,type='sine')=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=startAt+begin-offset,remain=at+d-begin,o=ac.createOscillator(),v=ac.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,when);v.gain.exponentialRampToValueAtTime(g,when+.025);v.gain.exponentialRampToValueAtTime(.0001,when+remain);o.connect(v).connect(master);o.start(when);o.stop(when+remain+.02);nodes.push(o);};const noise=(at,d=.18,g=.02)=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=startAt+begin-offset,len=Math.ceil((at+d-begin)*ac.sampleRate),b=ac.createBuffer(1,len,ac.sampleRate),data=b.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.sin((i+1)*(seed+3)*71.17)*Math.pow(1-i/len,2);const s=ac.createBufferSource(),f=ac.createBiquadFilter(),v=ac.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=720;v.gain.value=g;s.connect(f).connect(v).connect(master);s.start(when);nodes.push(s);};const roots=[196,220,246.9,261.6,174.6];for(let at=0,part=0;at<duration;at+=5,part++){const root=roots[(part+seed)%roots.length];for(const n of [root,root*1.25,root*1.5])tone(at,n,4.85,.016,'triangle');tone(at+.08,root*3,.4,.05);tone(at+.2,root*4,.45,.025);noise(at,.25,.027);for(let k=.75;k<4.8;k+=.72)tone(at+k,root*[2,2.5,3,2.25][Math.floor(k*2)%4],.18,.018);}return {nodes,master};}
function silence(){for(const n of live.nodes)try{n.stop();}catch{}live={nodes:[],master:null};}
async function sound(from,duration,seed){silence();if(!$('hero-sound').checked)return;const AC=window.AudioContext||window.webkitAudioContext;audioContext??=new AC({sampleRate:RATE});await audioContext.resume();live=scheduleAudio(audioContext,audioContext.destination,duration,audioContext.currentTime+.04,from,seed);}
function stop(){cancelAnimationFrame(raf);raf=0;silence();$('hero-play').textContent='▶ 재생';}
function stopShort(){cancelAnimationFrame(shortRaf);shortRaf=0;silence();$('hero-short-play').textContent='▶ 쇼츠 미리보기';}
function choose(index){stop();selected=index;time=0;document.querySelectorAll('.story-card').forEach((b,i)=>b.classList.toggle('active',i===index));const s=stories[index];$('hero-label').textContent=`SCENE ${String(index+1).padStart(2,'0')} · 10초`;$('hero-heading').textContent=s.title;$('hero-summary').textContent=s.summary;$('hero-year').textContent=s.year;$('hero-source').textContent=sources[s.source];$('hero-narration').textContent=s.narration;renderScene(index,0);say(`${index+1}번 장면이 준비되었습니다.`);}
function cards(){stories.forEach((s,i)=>{const b=document.createElement('button');b.className='story-card';b.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span>${s.title}<small>${s.year} · 10초</small></span>`;b.onclick=()=>choose(i);$('hero-story-list').append(b);});}
$('hero-play').onclick=async()=>{if(raf){stop();return;}if(time>=CLIP-.02)time=0;await sound(time,CLIP,selected);const start=performance.now()-time*1000;const tick=now=>{time=clamp((now-start)/1000,0,CLIP);renderScene(selected,time);if(time>=CLIP){stop();return;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);$('hero-play').textContent='Ⅱ 일시정지';};
$('hero-short-play').onclick=async()=>{if(shortRaf){stopShort();return;}if(shortTime>=SHORT-.02)shortTime=0;await sound(shortTime,SHORT,7);const start=performance.now()-shortTime*1000;const tick=now=>{shortTime=clamp((now-start)/1000,0,SHORT);renderShort(shortTime);if(shortTime>=SHORT){stopShort();return;}shortRaf=requestAnimationFrame(tick);};shortRaf=requestAnimationFrame(tick);$('hero-short-play').textContent='Ⅱ 일시정지';};
$('hero-seek').oninput=()=>{stop();time=Number($('hero-seek').value)/100;renderScene(selected,time);};$('hero-short-seek').oninput=()=>{stopShort();shortTime=Number($('hero-short-seek').value)/100;renderShort(shortTime);};$('hero-captions').onchange=()=>renderScene(selected,time);$('hero-sound').onchange=()=>{stop();stopShort();};$('hero-volume').oninput=()=>{if(live.master&&audioContext)live.master.gain.setTargetAtTime(Number($('hero-volume').value)/100*.82,audioContext.currentTime,.04);};
async function muxer(){if(window.Mp4Muxer)return;await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=r;s.onerror=()=>j(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s);});}
async function audioChunks(duration,config,seed){const ch=config.numberOfChannels,oac=new OfflineAudioContext(ch,Math.ceil(duration*RATE),RATE);scheduleAudio(oac,oac.destination,duration,0,0,seed);const b=await oac.startRendering(),chunks=[];let fail;const e=new AudioEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:x=>fail=x});e.configure(config);for(let off=0,step=4800;off<b.length;off+=step){const len=Math.min(step,b.length-off),data=new Float32Array(len*ch);for(let c=0;c<ch;c++)data.set(b.getChannelData(c).subarray(off,off+len),c*len);const a=new AudioData({format:'f32-planar',sampleRate:RATE,numberOfFrames:len,numberOfChannels:ch,timestamp:Math.round(off/RATE*1e6),data});e.encode(a);a.close();if(e.encodeQueueSize>16)await e.flush();}await e.flush();e.close();if(fail)throw fail;return chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp).filter(({chunk},i,list)=>i===0||chunk.timestamp>list[i-1].chunk.timestamp);}
async function encodeVideo({duration,width,height,draw,seed,onProgress}){if(!window.VideoEncoder||($('hero-sound').checked&&!window.AudioEncoder))throw Error('최신 Chrome 또는 Edge에서 저장해 주세요.');await muxer();const video={codec:'avc1.42001f',width,height,bitrate:height>width?3200000:3000000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(video)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');let audio=null;if($('hero-sound').checked)for(const channels of [2,1]){const c={codec:'mp4a.40.2',sampleRate:RATE,numberOfChannels:channels,bitrate:128000};if((await AudioEncoder.isConfigSupported(c)).supported){audio=c;break;}}const out=document.createElement('canvas');out.width=width;out.height=height;const target=new Mp4Muxer.ArrayBufferTarget(),m=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width,height,frameRate:FPS},...(audio?{audio:{codec:'aac',numberOfChannels:audio.numberOfChannels,sampleRate:RATE}}:{}),fastStart:'in-memory'}),sounds=audio?await audioChunks(duration,audio,seed):[],videos=[];let fail,enc;try{enc=new VideoEncoder({output:(chunk,meta)=>videos.push({chunk,meta}),error:e=>fail=e});enc.configure(video);const total=Math.round(duration*FPS);for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(fail)throw fail;draw(i/FPS,out);const f=new VideoFrame(out,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});enc.encode(f,{keyFrame:i%(FPS*2)===0});f.close();if(i%8===0||enc.encodeQueueSize>6){onProgress(i/total);await new Promise(r=>setTimeout(r,0));while(enc.encodeQueueSize>6)await new Promise(r=>setTimeout(r,8));}}await enc.flush();if(fail)throw fail;videos.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const {chunk,meta} of videos){if(chunk.timestamp<=last)continue;m.addVideoChunk(chunk,meta);last=chunk.timestamp;}last=-1;for(const {chunk,meta} of sounds){if(chunk.timestamp<=last)continue;m.addAudioChunk(chunk,meta);last=chunk.timestamp;}m.finalize();return new Blob([target.buffer],{type:'video/mp4'});}finally{if(enc&&enc.state!=='closed')enc.close();}}
function lock(on){busy=on;for(const id of ['hero-play','hero-export','hero-export-all','hero-short-play','hero-short-export','hero-script','hero-thumbnail','hero-seek','hero-short-seek'])$(id).disabled=on;$('hero-cancel').hidden=!on;}
function download(blob,name,kind='long'){const url=URL.createObjectURL(blob),a=kind==='short'?$('hero-short-download'):$('hero-download');if(kind==='short'){if(shortURL)URL.revokeObjectURL(shortURL);shortURL=url;}else{if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;}a.href=url;a.download=name;a.hidden=false;a.click();}
function restore(message){lock(false);renderScene(selected,0);renderShort(0);say(message);}
$('hero-cancel').onclick=()=>cancelled=true;
$('hero-export').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);const index=selected;try{const blob=await encodeVideo({duration:CLIP,width:1280,height:720,draw:(t,c)=>renderScene(index,t,c),seed:index,onProgress:p=>say(`${index+1}번 장면 저장 중… ${Math.floor(p*100)}%`)});download(blob,`히어로-콘테스트-${String(index+1).padStart(2,'0')}-${stories[index].title}.mp4`);restore('선택한 10초 장면을 저장했습니다.');}catch(e){restore('저장 오류: '+(e?.message||e));}};
$('hero-export-all').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);try{const duration=stories.length*CLIP,blob=await encodeVideo({duration,width:1280,height:720,draw:(t,c)=>{const i=Math.min(stories.length-1,Math.floor(t/CLIP));renderScene(i,t-i*CLIP,c);},seed:12,onProgress:p=>say(`1분 20초 롱폼 저장 중… ${Math.floor(p*100)}%`)});download(blob,'팬들이-이번엔-꿈을-키웠습니다-롱폼.mp4');restore('음악과 효과음이 포함된 1분 20초 롱폼을 저장했습니다.');}catch(e){restore('롱폼 저장 오류: '+(e?.message||e));}};
$('hero-short-export').onclick=async()=>{stop();stopShort();cancelled=false;lock(true);try{const blob=await encodeVideo({duration:SHORT,width:720,height:1280,draw:(t,c)=>renderShort(t,c),seed:7,onProgress:p=>shortSay(`30초 쇼츠 저장 중… ${Math.floor(p*100)}%`)});download(blob,'팬들이-이번엔-꿈을-키웠습니다-30초-쇼츠.mp4','short');restore('30초 쇼츠를 저장했습니다.');shortSay('음악과 효과음이 포함된 30초 세로 쇼츠를 저장했습니다.');}catch(e){restore('쇼츠 저장 오류: '+(e?.message||e));shortSay('쇼츠 저장 오류: '+(e?.message||e));}};
$('hero-script').onclick=()=>{const music=$('music-prompt-text').textContent.trim(),text=['팬들이 이번엔 꿈을 키웠습니다','이게 영웅시대의 응원법입니다','','[롱폼 전체 나레이션]',...stories.flatMap((s,i)=>['',`${i+1}. ${s.title} · ${s.year}`,s.narration]),'','[30초 쇼츠 나레이션]',shortNarration,'','[AI 배경음악 생성 프롬프트]',music,'','출처: 교수신문 · 경복대학교 제3회 히어로 콘테스트 보도'].join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='팬들이-이번엔-꿈을-키웠습니다-나레이션과-음악프롬프트.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);};
$('music-copy').onclick=async()=>{const value=$('music-prompt-text').textContent.trim();try{await navigator.clipboard.writeText(value);$('music-copy-status').textContent='복사했습니다.';}catch{$('music-copy-status').textContent='길게 눌러 직접 복사해 주세요.';}};
$('hero-thumbnail').onclick=async()=>{await document.fonts.ready;const c=document.createElement('canvas');c.width=1280;c.height=720;const g=c.getContext('2d');cover(g,backgrounds[3],1280,720,.5,1);const shade=g.createLinearGradient(0,0,930,0);shade.addColorStop(0,'rgba(5,20,38,.98)');shade.addColorStop(.66,'rgba(8,30,52,.72)');shade.addColorStop(1,'rgba(8,30,52,.05)');g.fillStyle=shade;g.fillRect(0,0,1280,720);sprite(g,students[5],1000,705,610);sprite(g,fans[5],1180,705,390,{flip:true});g.textAlign='left';g.textBaseline='middle';g.lineJoin='round';g.font='800 66px "Nanum Gothic", sans-serif';g.lineWidth=13;g.strokeStyle='#10263b';g.strokeText('팬들이 이번엔',58,190);g.fillStyle='#fff';g.fillText('팬들이 이번엔',58,190);g.font='800 108px "Nanum Gothic", sans-serif';g.lineWidth=16;g.strokeText('꿈을 키웠습니다',54,315);g.fillStyle='#ffd45d';g.fillText('꿈을 키웠습니다',54,315);pill(g,60,395,635,72,'#2d78a2');g.fillStyle='#fff';g.font='800 34px "Nanum Gothic",sans-serif';g.fillText('이게 영웅시대의 응원법입니다',88,431);g.fillStyle='#a9e8ff';g.font='700 26px "Nanum Gothic",sans-serif';g.fillText('빈 연습실에서 꿈의 무대까지',62,548);g.fillStyle='#fff';g.font='700 29px "Nanum Gothic",sans-serif';g.fillText('3,500만 원이 만든 새로운 기회',62,605);c.toBlob(blob=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='팬들이-이번엔-꿈을-키웠습니다-썸네일.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);},'image/png');};
window.addEventListener('beforeunload',()=>{stop();stopShort();if(downloadURL)URL.revokeObjectURL(downloadURL);if(shortURL)URL.revokeObjectURL(shortURL);});
cards();Promise.all([
 ...bgFiles.map(async(file,i)=>backgrounds[i]=await loadImage(file)),
 (async()=>students.push(...extract(await loadImage('assets/hero-contest/student-actions.png'),3,2)))(),
 (async()=>fans.push(...extract(await loadImage('assets/hero-contest/fan-actions.png'),3,2)))(),document.fonts.ready
]).then(()=>{ready=true;for(const id of ['hero-play','hero-export','hero-export-all','hero-short-play','hero-short-export','hero-script','hero-thumbnail'])$(id).disabled=false;choose(0);renderShort(0);shortSay('30초 쇼츠가 준비되었습니다.');}).catch(e=>{say('불러오기 실패: '+e.message);shortSay('불러오기 실패: '+e.message);});
})();
