(()=>{
'use strict';
const $=id=>document.getElementById(id),canvas=$('stage');
if(!canvas)return;
const ctx=canvas.getContext('2d'),W=720,H=1280,FPS=30;
const supplied=window.WOONG_OFFICIAL_NEWS||{};
const defaults={
 title:'Baila 공식 라이브 공개!',
 subtitle:'IM HERO · THE STADIUM 2',
 search:'임영웅 Baila 공식 라이브',
 video:'https://youtu.be/-wGXnDzPovw',
 cafe:'https://cafe.daum.net/hero0616/g7aK/945',
 publicUrl:'https://hero.openallstudio.com/renewal/news-baila.html',
 image:'assets/official-news/baila-official.png',
 duration:25,
 uploadTitle:'임영웅 ‘Baila’ 공식 라이브 공개｜웅토끼 공식소식',
 uploadSummary:'임영웅의 ‘Baila’ 라이브 클립이 공식 유튜브에 공개됐습니다. 웅토끼 영상으로 소식을 확인하고, 공식 영상에서 좋아요와 응원을 남겨 주세요.',
 narration:''
};
const data={...defaults,...supplied};
const DURATION=Math.max(12,Math.min(60,Number(data.duration)||25));
const cuts=[0,.12,.32,.52,.76,1].map(value=>value*DURATION);
let time=0,raf=0,cancelled=false,downloadURL='';
const backgrounds=[],sprites={greeting:[],actions:[],singDance:[]};let officialPhoto;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)},lerp=(a,b,t)=>a+(b-a)*t;
const say=value=>{if($('status'))$('status').textContent=value};
const secondsLabel=value=>`${Math.round(value)}초`;
const clockLabel=value=>{const whole=Math.max(0,Math.floor(value));return `${Math.floor(whole/60)}:${String(whole%60).padStart(2,'0')}`};
async function loadImage(src){const image=new Image();image.src=src;await image.decode();return image}
function frames(image,cols,rows){const scan=document.createElement('canvas');scan.width=image.width;scan.height=image.height;const g=scan.getContext('2d',{willReadFrequently:true});g.drawImage(image,0,0);const pixels=g.getImageData(0,0,image.width,image.height).data,out=[];for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const x0=Math.round(col*image.width/cols),x1=Math.round((col+1)*image.width/cols),y0=Math.round(row*image.height/rows),y1=Math.round((row+1)*image.height/rows);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(pixels[(y*image.width+x)*4+3]>28){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const c=document.createElement('canvas');c.width=Math.max(1,r-l+1);c.height=Math.max(1,b-t+1);c.getContext('2d').drawImage(image,l,t,c.width,c.height,0,0,c.width,c.height);out.push(c)}return out}
function cover(image,focus=.5,zoom=1,target=ctx,width=W,height=H,x=0,y=0){const ratio=width/height,source=image.width/image.height;let sw,sh;if(source>ratio){sh=image.height/zoom;sw=sh*ratio}else{sw=image.width/zoom;sh=sw/ratio}const sx=clamp(image.width*focus-sw/2,0,image.width-sw),sy=clamp((image.height-sh)/2,0,image.height-sh);target.drawImage(image,sx,sy,sw,sh,x,y,width,height)}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawSprite(image,x,bottom,height,{flip=false,alpha=1,rotate=0,scaleX=1,scaleY=1}={}){const width=height*image.width/image.height;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,bottom);ctx.rotate(rotate);ctx.scale((flip?-1:1)*scaleX,scaleY);ctx.drawImage(image,-width/2,-height,width,height);ctx.restore()}
function drawMotion(name,at,x,bottom,height,{flip=false,alpha=1,speed=1,intensity=1,offset=0}={}){if(!sprites.singDance.length||!window.WoongMotionLibrary)return;const motion=window.WoongMotionLibrary.sample(name,at,{speed,intensity,offset});drawSprite(sprites.singDance[motion.frame],x+motion.x,bottom+motion.y,height,{flip,alpha,rotate:motion.rotate,scaleX:motion.scaleX,scaleY:motion.scaleY})}
function fit(text,max,width,min=30,target=ctx,weight=800){let size=max;while(size>min){target.font=`${weight} ${size}px "Nanum Gothic",sans-serif`;if(target.measureText(text).width<=width)break;size-=2}return size}
function headline(text,y,max=68,color='#fff'){const size=fit(text,max,630);ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.font=`800 ${size}px "Nanum Gothic",sans-serif`;ctx.lineWidth=14;ctx.strokeStyle='rgba(7,28,45,.9)';ctx.strokeText(text,W/2,y);ctx.fillStyle=color;ctx.fillText(text,W/2,y)}
function badge(text){roundRect(58,58,604,58,29,'rgba(255,255,255,.94)');ctx.fillStyle='#235a78';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 22px "Nanum Gothic",sans-serif';ctx.fillText(text,W/2,87)}
function sparkles(t,color='#8be3ff'){for(let i=0;i<26;i++){const seed=i*71.37,x=(seed*19+t*(16+i%4)*8)%760-20,y=(seed*31+t*(28+i%5)*5)%1340-30,a=.25+.55*(.5+.5*Math.sin(t*3+i));ctx.globalAlpha=a;ctx.fillStyle=i%3?color:'#fff';ctx.beginPath();ctx.arc(x,y,2+(i%4),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function darkOverlay(top=.72,bottom=.72){const gradient=ctx.createLinearGradient(0,0,0,H);gradient.addColorStop(0,`rgba(5,23,39,${top})`);gradient.addColorStop(.45,'rgba(7,31,49,.12)');gradient.addColorStop(1,`rgba(5,21,36,${bottom})`);ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H)}
function segmentAt(value){for(let i=0;i<cuts.length-1;i++)if(value<cuts[i+1])return i;return 4}
function render(value){
 time=clamp(value,0,DURATION);const segment=segmentAt(time),local=time-cuts[segment],segmentLength=cuts[segment+1]-cuts[segment],p=local/segmentLength;ctx.clearRect(0,0,W,H);
 if(segment===0){const gradient=ctx.createRadialGradient(360,500,40,360,500,760);gradient.addColorStop(0,'#287da5');gradient.addColorStop(.55,'#153f67');gradient.addColorStop(1,'#071e38');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);sparkles(time,'#80dcff');const q=ease(local/Math.max(1,segmentLength*.42));if(data.motion==='sing-dance')drawMotion('sing-close',local,360,1180,lerp(300,650,q),{speed:.82,intensity:.75,offset:.2});else{const bob=Math.sin(time*7)*8;drawSprite(sprites.actions[Math.floor(time*3)%6],360,1180+bob,lerp(280,670,q))}badge('웅토끼가 전하는 공식 새 소식');headline('잠깐!',192,82,'#ffe16c');headline('공식 영상이 나왔어요',285,56,'#fff')}
 if(segment===1){ctx.save();ctx.filter='blur(18px) brightness(.5) saturate(1.25)';cover(officialPhoto,.5,1.15);ctx.restore();darkOverlay(.74,.84);sparkles(time,'#83d8ff');badge('공식 채널 공개 이미지');headline(data.title,175,60,'#ffe16c');ctx.save();ctx.beginPath();ctx.roundRect(40,245,640,356,24);ctx.clip();ctx.drawImage(officialPhoto,40,245,640,356);ctx.restore();ctx.lineWidth=5;ctx.strokeStyle='rgba(255,255,255,.88)';ctx.beginPath();ctx.roundRect(40,245,640,356,24);ctx.stroke();if(data.motion==='sing-dance')drawMotion('sing-close',local,360,1178,505,{speed:.72,intensity:.6,offset:1.5});else{const wave=Math.sin(local*3)*7;drawSprite(sprites.actions[[5,4,3,4,5][Math.floor(local*2)%5]],360,1178+wave,510,{flip:Math.floor(local*2)%4===1})}roundRect(72,1128,576,62,31,'rgba(9,35,56,.88)');ctx.fillStyle='#d9eff7';ctx.font='700 18px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('이미지: 임영웅 공식 YouTube',360,1161)}
 if(segment===2){cover(backgrounds[1],.5,1.06+.035*p);darkOverlay(.78,.76);sparkles(time,'#ffe988');if(data.motion==='sing-dance')drawMotion('sing-stage',local,360,1185,660,{speed:1.08,intensity:1,offset:.7});else{const frame=Math.floor(local*2.4)%6,hop=Math.abs(Math.sin(local*2.5))*12;drawSprite(sprites.actions[frame],360,1185-hop,660,{flip:Math.floor(local/1.25)%2===1})}badge('스타디움의 뜨거운 무대');headline(data.subtitle,205,52,'#fff');headline('다시 만날 시간!',292,66,'#8de5ff');ctx.fillStyle='#fff';ctx.font='800 25px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('무대의 감동은 공식 영상에서',360,1135)}
 if(segment===3){const gradient=ctx.createLinearGradient(0,0,W,H);gradient.addColorStop(0,'#eaf6f8');gradient.addColorStop(.52,'#b9dfe9');gradient.addColorStop(1,'#73abc2');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);sparkles(time,'#fff');badge('공식 영상 찾는 방법');headline('유튜브에서 검색하세요',190,54,'#fff');const grow=ease(p*1.8);ctx.save();ctx.translate(360,485);ctx.scale(.82+.18*grow,.82+.18*grow);roundRect(-310,-72,620,144,30,'#fff','#9abdc8');ctx.lineWidth=5;ctx.strokeStyle='#244d65';ctx.beginPath();ctx.arc(-244,-3,22,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-228,14);ctx.lineTo(-207,35);ctx.stroke();ctx.fillStyle='#1e3742';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font=`800 ${fit(data.search,35,480,24)}px "Nanum Gothic",sans-serif`;ctx.fillText(data.search,-180,3);ctx.restore();const pulse=.5+.5*Math.sin(local*4);roundRect(115,605,490,72,36,`rgba(31,94,126,${.85+.1*pulse})`);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='800 27px "Nanum Gothic",sans-serif';ctx.fillText('검색 후 공식 채널을 확인해 주세요',360,643);if(data.motion==='sing-dance')drawMotion('sing-close',local,510,1195,540,{flip:true,speed:.58,intensity:.45,offset:4.2});else drawSprite(sprites.actions[3],510,1195,555,{flip:true,rotate:-.02});ctx.fillStyle='#22475c';ctx.font='800 24px "Nanum Gothic",sans-serif';ctx.fillText('좋아요 · 댓글 · 끝까지 시청',330,1115)}
 if(segment===4){cover(backgrounds[2],.5,1.04+.035*p);darkOverlay(.75,.82);sparkles(time,'#7fe1ff');const frame=Math.min(5,Math.floor(local/segmentLength*6)),bob=Math.sin(local*3)*5;drawSprite(sprites.greeting[frame],360,1188+bob,690);badge('응원은 공식 영상에 남겨 주세요');headline('공식 영상 보러 출발!',202,57,'#fff');headline(p>.6?'건행~':'좋아요와 응원은 공식 영상에',292,p>.6?90:46,'#ffe16c');roundRect(90,1120,540,72,36,'rgba(7,30,50,.84)');ctx.fillStyle='#cfeefa';ctx.textAlign='center';ctx.font=`800 ${fit(data.search,25,480,18)}px "Nanum Gothic",sans-serif`;ctx.fillText(`검색: ${data.search}`,360,1158)}
 ctx.fillStyle='#8fe4ff';ctx.fillRect(0,0,W*time/DURATION,9);ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(W*time/DURATION,0,W,9);ctx.fillStyle='rgba(4,20,31,.7)';ctx.fillRect(0,H-35,W,35);ctx.fillStyle='#fff';ctx.font='700 13px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('팬 제작 홍보 영상 · 공식 채널을 사칭하지 않습니다',W/2,H-14);
 const fade=Math.max(0,1-local/.28);if(fade){ctx.fillStyle=`rgba(255,255,255,${fade*.32})`;ctx.fillRect(0,0,W,H)}if($('seek'))$('seek').value=Math.round(time*100);if($('clock'))$('clock').textContent=`${clockLabel(time)} / ${clockLabel(DURATION)}`;canvas.dataset.segment=String(segment+1);canvas.dataset.title=data.title
}
function narrationText(){return data.narration||`임영웅 공식 유튜브에 ${data.title.replace(/!+$/,'')} 소식이 공개됐습니다. 스타디움의 뜨거운 무대는 꼭 공식 영상에서 만나 보세요. 유튜브에서 '${data.search}'를 검색하고, 좋아요와 응원도 공식 영상에 남겨 주세요. 건행!`}
function linkText(){return `공식 영상\n${data.video}\n\n공식 카페 공지\n${data.cafe}\n\n웅토끼 공개 소식\n${data.publicUrl}`}
function setText(id,value){if($(id))$(id).textContent=value}
function refreshText(){setText('script-preview',narrationText());setText('upload-title',data.uploadTitle);setText('upload-summary',data.uploadSummary);setText('official-url',data.video);setText('cafe-url-view',data.cafe);setText('public-url',data.publicUrl);setText('duration-label',secondsLabel(DURATION));for(const link of document.querySelectorAll('.official-video-link'))link.href=data.video;for(const link of document.querySelectorAll('.official-cafe-link'))link.href=data.cafe;for(const link of document.querySelectorAll('.public-news-link'))link.href=data.publicUrl;if($('seek'))$('seek').max=Math.round(DURATION*100)}
async function copyValue(key,button){const values={title:data.uploadTitle,summary:data.uploadSummary,narration:narrationText(),links:linkText()},value=values[key]||'';try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}const original=button.textContent;button.textContent='복사 완료';setTimeout(()=>button.textContent=original,1400)}
function stop(){cancelAnimationFrame(raf);raf=0;if($('play'))$('play').textContent='▶ 미리보기'}
if($('play'))$('play').onclick=()=>{if(raf){stop();return}if(time>=DURATION-.02)time=0;const start=performance.now()-time*1000,tick=now=>{render((now-start)/1000);if(time>=DURATION){stop();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);$('play').textContent='Ⅱ 일시정지'};
if($('seek'))$('seek').oninput=()=>{stop();render(Number($('seek').value)/100)};
for(const button of document.querySelectorAll('[data-copy]'))button.onclick=()=>copyValue(button.dataset.copy,button);
async function loadMuxer(){if(window.Mp4Muxer)return;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';script.onload=resolve;script.onerror=()=>reject(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(script)})}
async function encode(){if(!window.VideoEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await loadMuxer();const config={codec:'avc1.42001f',width:W,height:H,bitrate:3400000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(config)).supported)throw Error('이 기기에서 세로 MP4 저장을 지원하지 않습니다.');const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width:W,height:H,frameRate:FPS},fastStart:'in-memory'}),chunks=[];let error,encoder=new VideoEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:value=>error=value});try{encoder.configure(config);const total=Math.round(DURATION*FPS);for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(error)throw error;render(i/FPS);const frame=new VideoFrame(canvas,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});encoder.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||encoder.encodeQueueSize>6){say(`MP4를 만들고 있습니다… ${Math.floor(i/total*100)}%`);await new Promise(resolve=>setTimeout(resolve,0));while(encoder.encodeQueueSize>6)await new Promise(resolve=>setTimeout(resolve,7))}}await encoder.flush();if(error)throw error;chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const {chunk,meta} of chunks){if(chunk.timestamp<=last)continue;mux.addVideoChunk(chunk,meta);last=chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(encoder.state!=='closed')encoder.close()}}
function safeName(value){return value.replace(/[\\/:*?"<>|!]+/g,'').replace(/\s+/g,'-').slice(0,48)||'웅토끼-공식소식'}
function downloadBlob(blob,name,remember=false){const url=URL.createObjectURL(blob),anchor=remember?$('ready-download'):document.createElement('a');anchor.href=url;anchor.download=name;if(remember){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;anchor.hidden=false;anchor.textContent='완성 영상 다시 저장'}else{document.body.append(anchor);setTimeout(()=>{anchor.remove();URL.revokeObjectURL(url)},5000)}anchor.click()}
function lock(on){for(const id of ['play','export','thumbnail','seek'])if($(id))$(id).disabled=on;if($('cancel'))$('cancel').hidden=!on}
if($('cancel'))$('cancel').onclick=()=>cancelled=true;
if($('export'))$('export').onclick=async()=>{stop();cancelled=false;lock(true);try{const blob=await encode();downloadBlob(blob,`${safeName(data.title)}-웅토끼-공식소식.mp4`,true);say(`${secondsLabel(DURATION)} 무음 MP4를 저장했습니다. YouTube 앱에서 공식 리믹스 음원을 붙여 주세요.`)}catch(error){say('영상 저장 오류: '+(error?.message||error))}finally{lock(false);render(0)}};
function drawThumbnail(){const thumb=document.createElement('canvas');thumb.width=1080;thumb.height=1920;const g=thumb.getContext('2d');g.fillStyle='#dff1f6';g.fillRect(0,0,1080,860);g.fillStyle='#1b516c';g.font='800 34px "Nanum Gothic",sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText('WOONG RABBIT · OFFICIAL NEWS',540,65);const imageHeight=607.5;g.drawImage(officialPhoto,0,0,officialPhoto.width,officialPhoto.height,0,126,1080,imageHeight);g.strokeStyle='#fff';g.lineWidth=14;g.strokeRect(7,119,1066,imageHeight+14);g.fillStyle='#071f35';g.fillRect(0,860,1080,1060);g.fillStyle='#7fdef9';g.fillRect(76,970,185,10);g.textAlign='left';g.textBaseline='middle';g.lineJoin='round';const title=data.title.replace(/!+$/,'');const titleSize=fit(title,88,920,54,g);g.font=`800 ${titleSize}px "Nanum Gothic",sans-serif`;g.lineWidth=16;g.strokeStyle='#071f35';g.strokeText(title,76,1130);g.fillStyle='#ffe16c';g.fillText(title,76,1130);g.font='800 48px "Nanum Gothic",sans-serif';g.fillStyle='#fff';g.fillText('웅토끼 공식소식',76,1245);g.font='700 34px "Nanum Gothic",sans-serif';g.fillStyle='#bfeaf7';const words=data.uploadSummary.split(' ');let line='',lines=[];for(const word of words){const trial=line?`${line} ${word}`:word;if(g.measureText(trial).width>900&&line){lines.push(line);line=word}else line=trial}if(line)lines.push(line);lines.slice(0,3).forEach((value,index)=>g.fillText(value,76,1365+index*55));g.fillStyle='#173f59';g.beginPath();g.roundRect(70,1640,940,130,28);g.fill();g.fillStyle='#fff';g.font='800 34px "Nanum Gothic",sans-serif';g.textAlign='center';g.fillText(`검색: ${data.search}`,540,1705);g.fillStyle='#8fdff5';g.font='700 26px "Nanum Gothic",sans-serif';g.fillText('공식 영상에서 좋아요와 응원을 남겨 주세요',540,1830);return thumb}
if($('thumbnail'))$('thumbnail').onclick=()=>{const thumb=drawThumbnail();thumb.toBlob(blob=>downloadBlob(blob,`${safeName(data.title)}-세로-썸네일.png`),'image/png')};
window.addEventListener('beforeunload',()=>{stop();if(downloadURL)URL.revokeObjectURL(downloadURL)});
Promise.all([
 loadImage('assets/first-stadium/backgrounds/stadium-plaza.webp').then(image=>backgrounds[0]=image),
 loadImage('assets/woong-rabbit/backgrounds/chapter-03-arena.webp').then(image=>backgrounds[1]=image),
 loadImage('assets/woong-rabbit/backgrounds/chapter-06-finale.webp').then(image=>backgrounds[2]=image),
 loadImage(data.image).then(image=>officialPhoto=image),
 loadImage('assets/woong-rabbit/greeting.png').then(image=>sprites.greeting=frames(image,3,2)),
 loadImage('assets/woong-rabbit/actions.png').then(image=>sprites.actions=frames(image,3,2)),
 ...(data.motion==='sing-dance'?[Promise.all([loadImage('assets/woong-rabbit/sing-dance-v1.png'),loadImage('assets/woong-rabbit/sing-dance-transitions-v1.png')]).then(([keys,transitions])=>{const keyFrames=frames(keys,3,2),transitionFrames=frames(transitions,3,2);sprites.singDance=window.WoongMotionLibrary.interleave(keyFrames,transitionFrames)})]:[]),
 document.fonts.ready
]).then(()=>{for(const id of ['play','export','thumbnail'])if($(id))$(id).disabled=false;refreshText();render(0);say(`${secondsLabel(DURATION)} 웅토끼 공식소식 영상이 준비되었습니다.`)}).catch(error=>say('장면을 불러오지 못했습니다: '+error.message));
})();
