(()=>{
'use strict';
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d'),W=720,H=1280,DURATION=25,FPS=30;
const defaults={title:'Baila 공식 라이브 공개!',subtitle:'IM HERO · THE STADIUM 2',search:'임영웅 Baila 공식 라이브',video:'https://youtu.be/-wGXnDzPovw',cafe:'https://cafe.daum.net/hero0616/g7aK/945'};
let data={...defaults},ready=false,time=0,raf=0,cancelled=false,downloadURL='';
const backgrounds=[],sprites={greeting:[],actions:[]};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)},lerp=(a,b,t)=>a+(b-a)*t;
const say=s=>$('status').textContent=s;
async function loadImage(src){const im=new Image();im.src=src;await im.decode();return im}
function frames(im,cols,rows){const scan=document.createElement('canvas');scan.width=im.width;scan.height=im.height;const g=scan.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const pixels=g.getImageData(0,0,im.width,im.height).data,out=[];for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const x0=Math.round(col*im.width/cols),x1=Math.round((col+1)*im.width/cols),y0=Math.round(row*im.height/rows),y1=Math.round((row+1)*im.height/rows);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(pixels[(y*im.width+x)*4+3]>28){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const c=document.createElement('canvas');c.width=Math.max(1,r-l+1);c.height=Math.max(1,b-t+1);c.getContext('2d').drawImage(im,l,t,c.width,c.height,0,0,c.width,c.height);out.push(c)}return out}
function cover(im,focus=.5,zoom=1){const ratio=W/H,src=im.width/im.height;let sw,sh;if(src>ratio){sh=im.height/zoom;sw=sh*ratio}else{sw=im.width/zoom;sh=sw/ratio}const sx=clamp(im.width*focus-sw/2,0,im.width-sw),sy=clamp((im.height-sh)/2,0,im.height-sh);ctx.drawImage(im,sx,sy,sw,sh,0,0,W,H)}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawSprite(im,x,bottom,height,{flip=false,alpha=1,rotate=0}={}){const width=height*im.width/im.height;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,bottom);ctx.rotate(rotate);if(flip)ctx.scale(-1,1);ctx.drawImage(im,-width/2,-height,width,height);ctx.restore()}
function fit(text,max,width,min=30){let size=max;while(size>min){ctx.font=`800 ${size}px "Nanum Gothic",sans-serif`;if(ctx.measureText(text).width<=width)break;size-=2}return size}
function headline(text,y,max=68,color='#fff'){const size=fit(text,max,630);ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.font=`800 ${size}px "Nanum Gothic",sans-serif`;ctx.lineWidth=14;ctx.strokeStyle='rgba(7,28,45,.9)';ctx.strokeText(text,W/2,y);ctx.fillStyle=color;ctx.fillText(text,W/2,y)}
function badge(text){roundRect(58,58,604,58,29,'rgba(255,255,255,.94)');ctx.fillStyle='#235a78';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 22px "Nanum Gothic",sans-serif';ctx.fillText(text,W/2,87)}
function sparkles(t,color='#8be3ff'){for(let i=0;i<26;i++){const seed=i*71.37,x=(seed*19+t*(16+i%4)*8)%760-20,y=(seed*31+t*(28+i%5)*5)%1340-30,a=.25+.55*(.5+.5*Math.sin(t*3+i));ctx.globalAlpha=a;ctx.fillStyle=i%3?color:'#fff';ctx.beginPath();ctx.arc(x,y,2+(i%4),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function darkOverlay(top=.72,bottom=.72){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,`rgba(5,23,39,${top})`);g.addColorStop(.45,'rgba(7,31,49,.12)');g.addColorStop(1,`rgba(5,21,36,${bottom})`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function segmentAt(t){return t<3?0:t<8?1:t<13?2:t<19?3:4}
function render(t){
 time=clamp(t,0,DURATION);const segment=segmentAt(time),starts=[0,3,8,13,19],ends=[3,8,13,19,25],local=time-starts[segment],p=local/(ends[segment]-starts[segment]);ctx.clearRect(0,0,W,H);
 if(segment===0){const g=ctx.createRadialGradient(360,500,40,360,500,760);g.addColorStop(0,'#287da5');g.addColorStop(.55,'#153f67');g.addColorStop(1,'#071e38');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);sparkles(time,'#80dcff');const q=ease(time/1.25),bob=Math.sin(time*7)*8;drawSprite(sprites.actions[Math.floor(time*3)%6],360,1180+bob,lerp(280,670,q));badge('웅토끼가 전하는 공식 새 소식');headline('잠깐!',192,82,'#ffe16c');headline('공식 영상이 나왔어요',285,56,'#fff')}
 if(segment===1){cover(backgrounds[0],.52,1.08+.04*p);darkOverlay(.82,.8);sparkles(time,'#83d8ff');drawSprite(sprites.actions[[5,4,3,4,5][Math.floor(local*2)%5]],365,1190,650,{flip:Math.floor(local*2)%4===1});badge('임영웅 공식 유튜브');headline(data.title,205,62,'#ffe16c');headline('새 영상 공개',290,68,'#fff');roundRect(72,1128,576,62,31,'rgba(9,35,56,.82)');ctx.fillStyle='#d9eff7';ctx.font='700 19px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('화면은 웅토끼 팬 창작 영상입니다',360,1161)}
 if(segment===2){cover(backgrounds[1],.5,1.06+.035*p);darkOverlay(.78,.76);sparkles(time,'#ffe988');const seq=[0,1,2,3,4,5],frame=seq[Math.floor(local*2.4)%seq.length],hop=Math.abs(Math.sin(local*2.5))*12;drawSprite(sprites.actions[frame],360,1185-hop,660,{flip:Math.floor(local/1.25)%2===1});badge('그날의 뜨거운 무대');headline(data.subtitle,205,52,'#fff');headline('다시 만날 시간!',292,66,'#8de5ff');ctx.fillStyle='#fff';ctx.font='800 25px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('무대의 감동은 공식 영상에서',360,1135)}
 if(segment===3){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#eaf6f8');g.addColorStop(.52,'#b9dfe9');g.addColorStop(1,'#73abc2');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);sparkles(time,'#fff');badge('공식 영상 찾는 방법');headline('유튜브에서 검색하세요',190,54,'#fff');const grow=ease(p*1.8);ctx.save();ctx.translate(360,485);ctx.scale(.82+.18*grow,.82+.18*grow);roundRect(-310,-72,620,144,30,'#fff','#9abdc8');ctx.lineWidth=5;ctx.strokeStyle='#244d65';ctx.beginPath();ctx.arc(-244,-3,22,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-228,14);ctx.lineTo(-207,35);ctx.stroke();const phrase=data.search;ctx.fillStyle='#1e3742';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font=`800 ${fit(phrase,35,480,24)}px "Nanum Gothic",sans-serif`;ctx.fillText(phrase,-180,3);ctx.restore();const pulse=.5+.5*Math.sin(local*4);roundRect(115,605,490,72,36,`rgba(31,94,126,${.85+.1*pulse})`);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='800 27px "Nanum Gothic",sans-serif';ctx.fillText('검색 후 공식 채널을 확인해 주세요',360,643);drawSprite(sprites.actions[3],510,1195,555,{flip:true,rotate:-.02});ctx.fillStyle='#22475c';ctx.font='800 24px "Nanum Gothic",sans-serif';ctx.fillText('좋아요 · 댓글 · 끝까지 시청',330,1115)}
 if(segment===4){cover(backgrounds[2],.5,1.04+.035*p);darkOverlay(.75,.82);sparkles(time,'#7fe1ff');const seq=[0,1,2,3,4,5],frame=seq[Math.min(5,Math.floor(local*1.45))],bob=Math.sin(local*3)*5;drawSprite(sprites.greeting[frame],360,1188+bob,690);badge('응원은 공식 영상에 남겨 주세요');headline('공식 영상 보러 출발!',202,57,'#fff');headline(local>3.6?'건행~':'좋아요와 응원은 공식 영상에',292,local>3.6?90:46,'#ffe16c');roundRect(90,1120,540,72,36,'rgba(7,30,50,.84)');ctx.fillStyle='#cfeefa';ctx.textAlign='center';ctx.font=`800 ${fit(data.search,25,480,18)}px "Nanum Gothic",sans-serif`;ctx.fillText(`검색: ${data.search}`,360,1158)}
 ctx.fillStyle='#8fe4ff';ctx.fillRect(0,0,W*time/DURATION,9);ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(W*time/DURATION,0,W,9);ctx.fillStyle='rgba(4,20,31,.7)';ctx.fillRect(0,H-35,W,35);ctx.fillStyle='#fff';ctx.font='700 13px "Nanum Gothic",sans-serif';ctx.textAlign='center';ctx.fillText('팬 제작 홍보 영상 · 공식 채널을 사칭하지 않습니다',W/2,H-14);
 const fade=Math.max(0,1-local/.28);if(fade){ctx.fillStyle=`rgba(255,255,255,${fade*.32})`;ctx.fillRect(0,0,W,H)}$('seek').value=Math.round(time*100);$('clock').textContent=`0:${String(Math.floor(time)).padStart(2,'0')} / 0:25`;canvas.dataset.segment=String(segment+1);canvas.dataset.title=data.title
}
function narrationText(){return `웅토끼가 급하게 달려왔어요! 임영웅 공식 유튜브에 ${data.subtitle}의 ${data.title.replace(/!+$/,'')} 소식이 공개됐습니다. 그날의 뜨거운 무대는 꼭 공식 영상에서 만나 보세요. 유튜브에서 '${data.search}'를 검색하고, 좋아요와 응원도 공식 영상에 남겨 주세요. 건행!`}
function descriptionText(){return `임영웅 공식 유튜브에\n‘${data.title.replace(/!+$/,'')}’ 소식이 공개됐습니다.\n\n이 쇼츠는 공식 영상을 알리기 위해 만든 팬 제작 홍보 영상입니다.\n화면은 웅토끼 창작 영상이며 공식 채널을 사칭하지 않습니다.\n\n공식 영상\n${data.video}\n\n공식 카페 공지\n${data.cafe}\n\n유튜브 검색: ${data.search}\n\n#임영웅 #Baila #IMHERO #영웅시대 #웅토끼`}
function refreshText(){const script=narrationText();$('script-preview').textContent=script;document.querySelector('.silent-box a').href=data.video}
function field(id,key){return $(id)?.value.trim()||defaults[key]}
function applyInputs(message='이 작품의 내용을 영상에 적용했습니다.'){data={title:field('news-title','title'),subtitle:field('news-subtitle','subtitle'),search:field('search-phrase','search'),video:field('video-url','video'),cafe:field('cafe-url','cafe')};refreshText();render(time);if($('input-status'))$('input-status').textContent=message}
function reset(){for(const [id,key] of [['news-title','title'],['news-subtitle','subtitle'],['search-phrase','search'],['video-url','video'],['cafe-url','cafe']])if($(id))$(id).value=defaults[key];applyInputs('Baila 공식소식 작품으로 되돌렸습니다.')}
function stop(){cancelAnimationFrame(raf);raf=0;$('play').textContent='▶ 미리보기'}
$('play').onclick=()=>{if(raf){stop();return}if(time>=DURATION-.02)time=0;const start=performance.now()-time*1000,tick=now=>{render((now-start)/1000);if(time>=DURATION){stop();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);$('play').textContent='Ⅱ 일시정지'};
$('seek').oninput=()=>{stop();render(Number($('seek').value)/100)};if($('apply'))$('apply').onclick=()=>applyInputs();if($('reset'))$('reset').onclick=reset;
async function loadMuxer(){if(window.Mp4Muxer)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=resolve;s.onerror=()=>reject(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s)})}
async function encode(){if(!window.VideoEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await loadMuxer();const config={codec:'avc1.42001f',width:W,height:H,bitrate:3400000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(config)).supported)throw Error('이 기기에서 세로 MP4 저장을 지원하지 않습니다.');const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width:W,height:H,frameRate:FPS},fastStart:'in-memory'}),chunks=[];let error,encoder=new VideoEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:e=>error=e});try{encoder.configure(config);const total=DURATION*FPS;for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(error)throw error;render(i/FPS);const frame=new VideoFrame(canvas,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});encoder.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||encoder.encodeQueueSize>6){say(`25초 쇼츠를 만들고 있습니다… ${Math.floor(i/total*100)}%`);await new Promise(r=>setTimeout(r,0));while(encoder.encodeQueueSize>6)await new Promise(r=>setTimeout(r,7))}}await encoder.flush();if(error)throw error;chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const {chunk,meta} of chunks){if(chunk.timestamp<=last)continue;mux.addVideoChunk(chunk,meta);last=chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(encoder.state!=='closed')encoder.close()}}
function safeName(v){return v.replace(/[\\/:*?"<>|!]+/g,'').replace(/\s+/g,'-').slice(0,48)||'웅토끼-공식소식'}
function downloadBlob(blob,name,remember=false){const url=URL.createObjectURL(blob),a=remember?$('ready-download'):document.createElement('a');a.href=url;a.download=name;if(remember){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=url;a.hidden=false;a.textContent='완성 영상 다시 저장'}else{document.body.append(a);setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},5000)}a.click()}
function lock(on){for(const id of ['play','export','narration','thumbnail','description','apply','reset','seek','news-title','news-subtitle','search-phrase','video-url','cafe-url'])if($(id))$(id).disabled=on;$('cancel').hidden=!on}
$('cancel').onclick=()=>cancelled=true;
$('export').onclick=async()=>{stop();applyInputs('현재 입력 내용을 영상에 적용했습니다.');cancelled=false;lock(true);try{const blob=await encode();downloadBlob(blob,`${safeName(data.title)}-웅토끼-25초-쇼츠.mp4`,true);say('무음 25초 MP4를 저장했습니다. YouTube 앱에서 공식 리믹스 음원을 붙여 주세요.')}catch(e){say('영상 저장 오류: '+(e?.message||e))}finally{lock(false);render(0)}};
$('narration').onclick=()=>{applyInputs();downloadBlob(new Blob([`${data.title} · 25초 쇼츠 나레이션\n\n${narrationText()}\n\n화면 검색 문구\n${data.search}\n`],{type:'text/plain;charset=utf-8'}),`${safeName(data.title)}-나레이션.txt`)};
$('description').onclick=()=>{applyInputs();downloadBlob(new Blob([descriptionText()],{type:'text/plain;charset=utf-8'}),`${safeName(data.title)}-업로드-설명.txt`)};
$('thumbnail').onclick=()=>{applyInputs();const saved=time;render(4.8);const thumb=document.createElement('canvas');thumb.width=1080;thumb.height=1920;const g=thumb.getContext('2d');g.drawImage(canvas,0,0,1080,1920);g.fillStyle='#071e32';g.fillRect(0,0,1080,560);g.textAlign='center';g.textBaseline='middle';g.lineJoin='round';g.font='800 86px "Nanum Gothic",sans-serif';g.lineWidth=16;g.strokeStyle='#0a263c';g.strokeText(data.title,540,210);g.fillStyle='#ffe16c';g.fillText(data.title,540,210);g.font='800 50px "Nanum Gothic",sans-serif';g.fillStyle='#fff';g.fillText('웅토끼 공식소식',540,355);g.fillStyle='#79dfff';g.fillRect(370,430,340,8);thumb.toBlob(blob=>downloadBlob(blob,`${safeName(data.title)}-세로-썸네일.png`),'image/png');render(saved)};
window.addEventListener('beforeunload',()=>{stop();if(downloadURL)URL.revokeObjectURL(downloadURL)});
Promise.all([
 loadImage('assets/first-stadium/backgrounds/stadium-plaza.webp').then(im=>backgrounds[0]=im),
 loadImage('assets/woong-rabbit/backgrounds/chapter-03-arena.webp').then(im=>backgrounds[1]=im),
 loadImage('assets/woong-rabbit/backgrounds/chapter-06-finale.webp').then(im=>backgrounds[2]=im),
 loadImage('assets/woong-rabbit/greeting.png').then(im=>sprites.greeting=frames(im,3,2)),
 loadImage('assets/woong-rabbit/actions.png').then(im=>sprites.actions=frames(im,3,2)),document.fonts.ready
]).then(()=>{ready=true;for(const id of ['play','export','narration','thumbnail','description'])$(id).disabled=false;refreshText();render(0);say('25초 웅토끼 공식소식 쇼츠가 준비되었습니다.')}).catch(e=>say('장면을 불러오지 못했습니다: '+e.message));
})();
