'use strict';
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d'),duration=10;
let sheet,bg,frames=[],ready=false,busy=false,playing=0,time=0,cancelled=false,downloadURL='';
const poseCanvas=document.createElement('canvas');poseCanvas.width=1920;poseCanvas.height=1080;const poseCtx=poseCanvas.getContext('2d');
const say=t=>$('status').textContent=t;
async function imageAt(src){const im=new Image();im.src=src;await im.decode();return im;}
// Determine tight alpha bounds separately in each grid cell; keep the original sheet intact.
function measureFrames(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const data=g.getImageData(0,0,c.width,c.height).data,result=[];for(let row=0;row<2;row++)for(let col=0;col<3;col++){const y0=Math.round(row*c.height/2),y1=Math.round((row+1)*c.height/2);const boundary=k=>{if(k===0)return 0;if(k===3)return c.width;const center=k*c.width/3,start=Math.floor(center-c.width*.065),end=Math.ceil(center+c.width*.065);let best=center,score=Infinity;for(let x=start;x<=end;x++){let count=0;for(let y=y0;y<y1;y++)if(data[(y*c.width+x)*4+3]>32)count++;const cost=count*10000+Math.abs(x-center);if(cost<score){score=cost;best=x;}}return best;};const x0=boundary(col),x1=boundary(col+1);let l=x1,r=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){if(data[(y*c.width+x)*4+3]>32){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}}if(r<=l||b<=t)throw Error('스프라이트에 비어 있는 칸이 있습니다.');let hl=r,hr=l;for(let yy=t;yy<t+(b-t)*.2;yy++)for(let xx=l;xx<=r;xx++)if(data[(yy*c.width+xx)*4+3]>32){hl=Math.min(hl,xx);hr=Math.max(hr,xx);}result.push({x:l,y:t,w:r-l+1,h:b-t+1,headX:(hl+hr)/2});}return result;}
function frameImage(index,x,y,h,opacity=1){const f=frames[index],w=h*f.w/f.h;poseCtx.save();poseCtx.globalAlpha=opacity;poseCtx.drawImage(sheet,f.x,f.y,f.w,f.h,x-(f.headX-f.x)*h/f.h,y-h,w,h);poseCtx.restore();}
function render(t){if(!ready)return;const w=canvas.width,h=canvas.height,phase=t/duration;ctx.clearRect(0,0,w,h);const zoom=1+.025*phase,bw=w*zoom,bh=bw*bg.height/bg.width;ctx.drawImage(bg,(w-bw)/2,(h-bh)/2,bw,bh);
 if($('effects').checked){ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<4;i++){const x=w*(.12+i*.25),end=x+Math.sin(t*.42+i)*150;const grad=ctx.createLinearGradient(x,0,end,h*.88);grad.addColorStop(0,'rgba(175,213,255,.11)');grad.addColorStop(1,'rgba(175,213,255,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(x-16,0);ctx.lineTo(x+16,0);ctx.lineTo(end+150,h*.88);ctx.lineTo(end-150,h*.88);ctx.fill();}for(let i=0;i<36;i++){const x=(i*347.3+Math.sin(t*.6+i)*20)%w,y=((i*113.7-t*(12+i%9))%h+h)%h;ctx.fillStyle=`rgba(255,226,171,${.13+.17*(.5+.5*Math.sin(t+i))})`;ctx.beginPath();ctx.arc(x,y,1+i%3,0,Math.PI*2);ctx.fill();}ctx.restore();}
 const rate=Number($('speed').value),cycle=[0,1,2,3,4,5,4,3,2,1],p=t*2.2*rate,idx=Math.floor(p)%cycle.length,frame=$('animate').checked?cycle[idx]:0;
 const height=h*.81*(1+.012*phase),x=w*.58+Math.sin(t*.65)*7,y=h*1.035+Math.sin(t*1.2)*2;
 // A short premultiplied-alpha dissolve softens pose changes without darkening overlap.
 const blend=$('animate').checked?Math.max(0,((p%1)-.7)/.3):0,mix=blend*blend*(3-2*blend);
 poseCtx.clearRect(0,0,w,h);poseCtx.save();poseCtx.translate(x,y);poseCtx.rotate(Math.sin(t*.55)*.006);poseCtx.globalCompositeOperation='lighter';frameImage(frame,0,0,height,1-mix);if(mix)frameImage(cycle[(idx+1)%cycle.length],0,0,height,mix);poseCtx.restore();ctx.drawImage(poseCanvas,0,0);
 const shade=ctx.createLinearGradient(0,h*.85,0,h);shade.addColorStop(0,'rgba(4,10,17,0)');shade.addColorStop(1,'rgba(4,10,17,.74)');ctx.fillStyle=shade;ctx.fillRect(0,h*.85,w,h*.15);
 if($('effects').checked){ctx.save();ctx.strokeStyle='rgba(177,219,236,.13)';ctx.lineWidth=1.5;for(let i=0;i<9;i++){const r=30+((t*24+i*43)%360);ctx.beginPath();ctx.ellipse(w*.15,h*.9,r,r*.095,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(w*.86,h*.92,r,r*.095,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
 ctx.textAlign='left';ctx.font='700 24px "Nanum Gothic",sans-serif';ctx.fillStyle='#e5edf5';ctx.fillText('AI 창작 장면 · 실제 공연 영상 아님',52,h-40);ctx.textAlign='right';ctx.fillStyle='#b8c7d7';ctx.font='18px "Nanum Gothic",sans-serif';ctx.fillText('SPRITE MOTION STUDY',w-52,h-40);
}
function stop(){cancelAnimationFrame(playing);playing=0;$('play').textContent='▶ 재생';}
$('play').onclick=()=>{if(playing){stop();return;}const start=performance.now()-time*1000;const tick=now=>{time=Math.max(0,(now-start)/1000)%duration;render(time);$('seek').value=time/duration*1000;playing=requestAnimationFrame(tick);};playing=requestAnimationFrame(tick);$('play').textContent='■ 정지';};
$('seek').oninput=()=>{stop();time=Number($('seek').value)/1000*duration;render(time);};for(const id of ['speed','effects','animate'])$(id).oninput=()=>render(time);
function lock(on){busy=on;for(const id of ['play','export','seek','speed','effects','animate'])$(id).disabled=on;$('cancel').hidden=!on;}
async function muxer(){if(window.Mp4Muxer)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=resolve;s.onerror=()=>reject(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s);});}
$('export').onclick=async()=>{stop();lock(true);cancelled=false;let encoder;try{if(!window.VideoEncoder)throw Error('MP4 저장은 최신 Chrome 또는 Edge에서 이용해 주세요.');await muxer();await document.fonts.ready;const config={codec:'avc1.420028',width:1920,height:1080,bitrate:6500000,framerate:30};if(!(await VideoEncoder.isConfigSupported(config)).supported)throw Error('이 브라우저는 MP4 인코딩을 지원하지 않습니다.');const target=new Mp4Muxer.ArrayBufferTarget(),m=new Mp4Muxer.Muxer({target,video:{codec:'avc',width:1920,height:1080},fastStart:'in-memory'});let failure;encoder=new VideoEncoder({output:(c,meta)=>m.addVideoChunk(c,meta),error:e=>failure=e});encoder.configure(config);for(let i=0;i<300;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(failure)throw failure;render(i/30);const f=new VideoFrame(canvas,{timestamp:Math.round(i*1e6/30),duration:Math.round(1e6/30)});encoder.encode(f,{keyFrame:i%60===0});f.close();if(i%10===0||encoder.encodeQueueSize>6){say(`10초 무음 영상을 만들고 있습니다… ${Math.floor(i/3)}%`);await new Promise(r=>setTimeout(r,0));while(encoder.encodeQueueSize>6){if(failure)throw failure;if(cancelled)throw Error('저장을 취소했습니다.');await new Promise(r=>setTimeout(r,10));}}}await encoder.flush();if(failure)throw failure;if(cancelled)throw Error('저장을 취소했습니다.');m.finalize();if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=URL.createObjectURL(new Blob([target.buffer],{type:'video/mp4'}));const a=$('download');a.href=downloadURL;a.download='움직이는무대-10초.mp4';a.hidden=false;a.click();say('10초 무음 MP4를 저장했습니다.');}catch(e){say(e.message);}finally{if(encoder&&encoder.state!=='closed')encoder.close();lock(false);render(time);}};
$('cancel').onclick=()=>cancelled=true;
window.addEventListener('beforeunload',()=>{if(downloadURL)URL.revokeObjectURL(downloadURL);});
Promise.all([imageAt('assets/sprite-stage/performer.png'),imageAt('assets/sprite-stage/background.png'),document.fonts.ready]).then(([a,b])=>{sheet=a;bg=b;frames=measureFrames(sheet);ready=true;render(0);$('play').disabled=$('export').disabled=false;say('준비되었습니다. 재생을 눌러 움직임을 확인해 보세요.');}).catch(e=>say('불러오기 실패: '+e.message));
