'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),g=canvas.getContext('2d');
let photos=[],scenes=[],raf=0,busy=false,cancelled=false,downloadURL='',position=0;
const pause=()=>new Promise(r=>setTimeout(r,0)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const say=t=>$('status').textContent=t;
const total=()=>scenes.reduce((n,s)=>n+s.seconds,0);
function stop(){cancelAnimationFrame(raf);raf=0;$('play').textContent='▶ 미리보기';}
function lock(on){busy=on;document.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=on);$('cancel').disabled=false;$('cancel').hidden=!on;}
function invalidate(){stop();if(downloadURL){URL.revokeObjectURL(downloadURL);downloadURL='';}$('download').hidden=true;}
function sync(){const ready=!!scenes.length&&photos.length>0;$('play').disabled=$('export').disabled=$('srt').disabled=!ready||busy;$('total').textContent=scenes.length?`${scenes.length}장면 · 총 ${total().toFixed(1)}초`:'아직 만든 장면이 없습니다.';position=clamp(position,0,total());draw(position);}
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
async function picture(src,name){const im=new Image();im.src=src;await im.decode();return {src,name,im};}
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('파일을 읽을 수 없습니다.'));r.readAsDataURL(file);});}
function photoUI(){const box=$('photoList');box.replaceChildren();photos.forEach((p,i)=>{const fig=element('figure'),im=element('img');im.src=p.src;im.alt=p.name;const btn=element('button','삭제');btn.onclick=()=>{invalidate();photos.splice(i,1);scenes.forEach(s=>s.photo=s.photo===i?0:s.photo>i?s.photo-1:s.photo);photoUI();sceneUI();sync();};fig.append(im,element('figcaption',`${i+1}. ${p.name}`),btn);box.append(fig);});}
function sceneUI(){const box=$('scenes');box.replaceChildren();scenes.forEach((s,i)=>{const card=element('article');card.className='scene';const row=element('div');row.className='row';row.append(element('b',`장면 ${i+1}`));for(const [label,d] of [['↑',-1],['↓',1],['삭제',0]]){const b=element('button',label);b.setAttribute('aria-label',`장면 ${i+1} ${label}`);b.disabled=d<0?i===0:d>0?i===scenes.length-1:false;b.onclick=()=>{if(d&&(i+d<0||i+d>=scenes.length))return;invalidate();if(d)[scenes[i],scenes[i+d]]=[scenes[i+d],scenes[i]];else scenes.splice(i,1);sceneUI();sync();};row.append(b);}card.append(row);
 const select=element('select');select.setAttribute('aria-label',`장면 ${i+1} 사진`);photos.forEach((p,k)=>{const o=element('option',`${k+1}. ${p.name}`);o.value=k;select.append(o);});select.value=s.photo;select.onchange=()=>{invalidate();s.photo=Number(select.value);sync();};card.append(select);
 const speaker=element('input');speaker.value=s.speaker;speaker.maxLength=20;speaker.placeholder='말하는 사람 (없으면 비워 두세요)';speaker.setAttribute('aria-label',`장면 ${i+1} 화자`);speaker.oninput=()=>{invalidate();s.speaker=speaker.value;sync();};card.append(speaker);
 const text=element('textarea');text.value=s.text;text.maxLength=160;text.setAttribute('aria-label',`장면 ${i+1} 대사`);text.oninput=()=>{invalidate();s.text=text.value;sync();};card.append(text);
 const controls=element('div');controls.className='row';const lab=element('label','표시 시간 (초)'),time=element('input');time.type='number';time.min=2;time.max=30;time.step=.5;time.value=s.seconds;time.onchange=()=>{invalidate();s.seconds=clamp(Number(time.value)||5,2,30);s.delay=Math.min(s.delay,s.seconds-1);time.value=s.seconds;sync();};lab.append(time);
 const delayLab=element('label','대사 전 뜸 (초)'),delay=element('input');delay.type='number';delay.min=0;delay.max=3;delay.step=.5;delay.value=s.delay;delay.onchange=()=>{invalidate();s.delay=clamp(Number(delay.value)||0,0,Math.min(3,s.seconds-1));delay.value=s.delay;sync();};delayLab.append(delay);controls.append(lab,delayLab);card.append(controls);box.append(card);
 });}
function parseScript(text){return text.trim().split(/\n\s*\n/).filter(Boolean).map((part,i)=>{const m=part.match(/^([^:\n：]{1,20})[:：]\s*([\s\S]*)$/);const words=(m?m[2]:part).trim();if(words.length>160)throw Error(`장면 ${i+1} 대사를 160자 이내로 나눠 주세요.`);return {speaker:m?m[1].trim():'',text:words,photo:i%photos.length,seconds:clamp(Math.ceil(words.length/5),4,12),delay:0};});}
$('build').onclick=()=>{try{if(!photos.length)throw Error('사진을 먼저 추가해 주세요.');const next=parseScript($('script').value);if(!next.length||next.length>12)throw Error('대본을 1~12개의 문단으로 입력해 주세요.');invalidate();scenes=next;position=0;sceneUI();sync();say('장면을 만들었습니다. 사진과 시간을 확인한 뒤 미리보기를 눌러 주세요.');}catch(e){say(e.message);}};
$('photos').onchange=async e=>{const files=[...e.target.files];lock(true);say('사진을 불러오고 있습니다…');try{if(photos.length+files.length>12)throw Error('사진은 최대 12장까지 넣을 수 있습니다.');const added=[];for(const f of files){if(f.size>15e6)throw Error('사진 한 장은 15MB 이하로 넣어 주세요.');added.push(await picture(await fileData(f),f.name));}invalidate();photos.push(...added);photoUI();sceneUI();say('사진을 추가했습니다. 대본을 넣고 장면 만들기를 눌러 주세요.');}catch(e){say(e.message);}finally{e.target.value='';lock(false);sync();}};
function lines(text,max){const out=[];for(const paragraph of text.split('\n')){let line='';for(const c of paragraph){if(g.measureText(line+c).width>max&&line){out.push(line);line=c;}else line+=c;}out.push(line);}return out;}
function fitted(text,x,y,width,height,size,color){let list;do{g.font=`800 ${size}px "Nanum Gothic",sans-serif`;list=lines(text,width);if(list.length*size*1.45<=height)break;size-=2;}while(size>16);g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';list.forEach((line,i)=>g.fillText(line,x,y+(i-(list.length-1)/2)*size*1.45));}
function sceneAt(t){let start=0;for(let i=0;i<scenes.length;i++){const s=scenes[i];if(t<start+s.seconds||i===scenes.length-1)return {s,i,start,u:clamp((t-start)/s.seconds,0,1)};start+=s.seconds;}return null;}
function draw(t){const w=canvas.width,h=canvas.height,wide=w>h,pal=$('mood').value==='night'?['#172e32','#f9f4e8','#b8d5cc']:$('mood').value==='calm'?['#e8edf0','#253c48','#7996a2']:['#f4eddf','#2b4439','#ad7555'];g.fillStyle=pal[0];g.fillRect(0,0,w,h);const hit=sceneAt(t);if(!hit||!photos.length){fitted('사진에서 이야기로',w/2,h/2,w*.8,h*.2,58,pal[1]);return;}
 const {s,i,u}=hit,p=photos[s.photo]||photos[0],x=w*.055,y=h*.17,iw=wide?w*.52:w*.89,ih=wide?h*.72:h*.59;
 g.save();g.beginPath();g.roundRect(x,y,iw,ih,24);g.clip();g.fillStyle=pal[0];g.fillRect(x,y,iw,ih);const scale=Math.min(iw/p.im.width,ih/p.im.height)*(1+.025*(i%2?1-u:u)),dw=p.im.width*scale,dh=p.im.height*scale;g.drawImage(p.im,x+(iw-dw)/2,y+(ih-dh)/2,dw,dh);g.restore();
 fitted($('title').value||'우리의 작은 이야기',w/2,h*.08,w*.86,h*.12,wide?58:64,pal[1]);
 const cx=wide?w*.78:w/2,cy=wide?h*.51:h*.865,cw=wide?w*.34:w*.86,ch=wide?h*.45:h*.16,local=t-hit.start;
 if(local>=s.delay){if(s.speaker){g.fillStyle=pal[2];g.font=`800 ${wide?32:36}px "Nanum Gothic",sans-serif`;g.textAlign='center';g.fillText(s.speaker,cx,cy-ch*.52);}fitted(s.text,cx,cy,cw,ch*.78,wide?46:54,pal[1]);}else fitted('…',cx,cy,cw,ch,64,pal[2]);
 g.textAlign='left';g.fillStyle=pal[2];g.font=`700 ${wide?22:25}px "Nanum Gothic",sans-serif`;g.fillText($('fiction').checked?'창작 상황극':'사진 이야기',w*.06,h*.965);g.textAlign='right';g.fillText(`${i+1} / ${scenes.length}`,w*.94,h*.965);
 if(u<.045&&i>0){g.globalAlpha=1-u/.045;g.fillStyle=pal[0];g.fillRect(0,0,w,h);g.globalAlpha=1;}
}
function resize(){canvas.width=$('orientation').value==='landscape'?1920:1080;canvas.height=$('orientation').value==='landscape'?1080:1920;sync();}
for(const id of ['title','orientation','mood','fiction'])$(id).addEventListener(id==='title'?'input':'change',()=>{invalidate();resize();});
$('seek').oninput=()=>{stop();position=total()*Number($('seek').value)/1000;draw(position);};
$('play').onclick=async()=>{if(raf){stop();return;}await document.fonts.ready;const start=performance.now();position=0;$('play').textContent='■ 정지';const tick=()=>{position=Math.min(total(),(performance.now()-start)/1000);draw(position);$('seek').value=position/total()*1000;if(position<total())raf=requestAnimationFrame(tick);else stop();};raf=requestAnimationFrame(tick);};
function save(blob,name){const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function stamp(t){const ms=Math.round(t*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;}
$('srt').onclick=()=>{let at=0;const text=scenes.map((s,i)=>{const x=`${i+1}\n${stamp(at+s.delay)} --> ${stamp(at+s.seconds)}\n${s.speaker?s.speaker+': ':''}${s.text}\n`;at+=s.seconds;return x;}).join('\n');save(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}),'사진이야기-자막.srt');};
async function applyPack(pack){if(pack.version!==1||!Array.isArray(pack.photos)||!Array.isArray(pack.scenes)||!pack.photos.length||pack.photos.length>12||!pack.scenes.length||pack.scenes.length>12)throw Error('사진 이야기 묶음 형식이 올바르지 않습니다.');const next=[];for(const p of pack.photos){if(typeof p.src!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(p.src))throw Error('묶음에는 PNG·JPG·WEBP 이미지가 포함되어야 합니다.');next.push(await picture(p.src,String(p.name||'사진').slice(0,80)));}const ss=pack.scenes.map(s=>{if(!Number.isInteger(s.photo)||s.photo<0||s.photo>=next.length||typeof s.text!=='string'||s.text.length>160||!Number.isFinite(s.seconds)||s.seconds<2||s.seconds>30)throw Error('장면의 사진 번호·대사·시간을 확인해 주세요.');return {photo:s.photo,text:s.text,speaker:String(s.speaker||'').slice(0,20),seconds:s.seconds,delay:clamp(Number(s.delay)||0,0,Math.min(3,s.seconds-1))};});invalidate();photos=next;scenes=ss;$('title').value=String(pack.title||'').slice(0,60);$('orientation').value=pack.orientation==='landscape'?'landscape':'portrait';$('mood').value=['warm','calm','night'].includes(pack.mood)?pack.mood:'warm';$('fiction').checked=pack.fiction!==false;$('script').value=scenes.map(s=>(s.speaker?s.speaker+': ':'')+s.text).join('\n\n');position=0;photoUI();sceneUI();resize();}
function pack(){return {version:1,title:$('title').value,orientation:$('orientation').value,mood:$('mood').value,fiction:$('fiction').checked,photos:photos.map(({src,name})=>({src,name})),scenes};}
$('savePack').onclick=()=>{if(!photos.length||!scenes.length){say('사진과 장면을 먼저 만들어 주세요.');return;}save(new Blob([JSON.stringify(pack())],{type:'application/json'}),'사진이야기-재료.json');};
$('loadPack').onchange=async e=>{const file=e.target.files[0];if(!file)return;lock(true);try{if(file.size>80e6)throw Error('묶음 파일은 80MB 이하로 넣어 주세요.');await applyPack(JSON.parse(await file.text()));say('재료 묶음을 불러왔습니다.');}catch(err){say(`불러오기 실패: ${err.message}`);}finally{e.target.value='';lock(false);sync();}};
$('example').onclick=async()=>{lock(true);say('엄마의 콘서트 준비 예제를 불러오고 있습니다…');try{const r=await fetch('assets/story/mom-concert/project.json');if(!r.ok)throw Error('예제 파일을 불러오지 못했습니다.');const p=await r.json();for(const photo of p.photos){const r=await fetch(photo.src);if(!r.ok)throw Error('예제 이미지를 불러오지 못했습니다.');photo.src=await fileData(await r.blob());}await applyPack(p);say('24초 예제를 준비했습니다. 미리보기로 확인해 보세요.');}catch(e){say(e.message);}finally{lock(false);sync();}};
$('reset').onclick=()=>{invalidate();photos=[];scenes=[];position=0;$('title').value=$('script').value='';photoUI();sceneUI();sync();say('새 작업을 시작합니다.');};
let muxerLoading;
function loadMuxer(){if(window.Mp4Muxer)return Promise.resolve();return muxerLoading??=(new Promise((resolve,reject)=>{const s=element('script');const timer=setTimeout(()=>reject(Error('영상 저장 도구 연결 시간이 초과됐습니다. 다시 시도해 주세요.')),20000);s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=()=>{clearTimeout(timer);resolve();};s.onerror=()=>{clearTimeout(timer);reject(Error('영상 저장 도구를 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.'));};document.head.append(s);})).catch(e=>{muxerLoading=null;throw e;});}
async function exportMovie(){if(!scenes.length||!photos.length)return;invalidate();cancelled=false;lock(true);let encoder;try{if(!window.VideoEncoder)throw Error('MP4 저장은 최신 Chrome 또는 Edge에서 이용해 주세요.');if(total()>180)throw Error('한 번에 3분까지 저장할 수 있습니다. 장면 시간을 줄여 주세요.');say('MP4 저장을 준비합니다…');await document.fonts.ready;await loadMuxer();let config;for(const codec of ['avc1.640028','avc1.420028']){const candidate={codec,width:canvas.width,height:canvas.height,bitrate:6000000,framerate:30};if((await VideoEncoder.isConfigSupported(candidate)).supported){config=candidate;break;}}if(!config)throw Error('이 브라우저에서 MP4 인코딩을 지원하지 않습니다. Chrome 또는 Edge를 사용해 주세요.');const target=new Mp4Muxer.ArrayBufferTarget(),muxer=new Mp4Muxer.Muxer({target,video:{codec:'avc',width:canvas.width,height:canvas.height},fastStart:'in-memory'});let failure;encoder=new VideoEncoder({output:(chunk,meta)=>muxer.addVideoChunk(chunk,meta),error:e=>failure=e});encoder.configure(config);const frames=Math.ceil(total()*30);for(let i=0;i<frames;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(failure)throw failure;draw(i/30);const frame=new VideoFrame(canvas,{timestamp:Math.round(i*1e6/30),duration:Math.round(1e6/30)});encoder.encode(frame,{keyFrame:i%60===0});frame.close();if(i%10===0||encoder.encodeQueueSize>8){say(`무음 MP4를 만들고 있습니다… ${Math.floor(i/frames*100)}%`);await pause();while(encoder.encodeQueueSize>8){if(cancelled)throw Error('저장을 취소했습니다.');if(failure)throw failure;await new Promise(r=>setTimeout(r,10));}}}await encoder.flush();if(failure)throw failure;if(cancelled)throw Error('저장을 취소했습니다.');muxer.finalize();const blob=new Blob([target.buffer],{type:'video/mp4'});downloadURL=URL.createObjectURL(blob);const a=$('download');a.href=downloadURL;a.download='사진이야기.mp4';a.hidden=false;a.textContent='완성 영상 다시 다운로드';a.click();say(`${total()}초 무음 MP4를 저장했습니다. 편집 프로그램에서 TTS를 추가해 주세요.`);}catch(e){say(e.message);}finally{if(encoder&&encoder.state!=='closed')encoder.close();lock(false);sync();}}
$('export').onclick=exportMovie;$('cancel').onclick=()=>{cancelled=true;};
window.addEventListener('beforeunload',()=>{if(downloadURL)URL.revokeObjectURL(downloadURL);});document.fonts.ready.then(()=>draw(position));sync();
