const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({chromium,server,root})=>{
 const out=path.join(root,'.test-output/process');fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/atelier.html`);await page.locator('.settings summary').click();await page.selectOption('#framing','closeup');
 await page.setInputFiles('#photo',process.env.SKETCH_TEST_IMAGE||path.join(process.env.USERPROFILE,'Desktop','ai테스트','임영웅1.jpg'));await page.waitForFunction(()=>photos.length&&!photoInput.disabled);await page.click('#createArtwork');await page.waitForFunction(()=>plan&&!photoInput.disabled,null,{timeout:240000});await page.evaluate(async()=>{await atelierReady;await DrawingHand.ready;});
 const choreography=await page.evaluate(()=>({intro:plan.intro,chapters:plan.chapters,count:plan.strokes.length,marks:StudioGraphite.marks(analysis).length,firstShade:plan.strokes.find(s=>s.kind==='hatch').tDown,drawEnd:plan.drawEndMs}));console.log(choreography);assert(!choreography.intro);assert.equal(choreography.count,choreography.marks);assert(choreography.firstShade/choreography.drawEnd>.49);
 const fidelity=await page.evaluate(()=>{handToggle.checked=false;renderFrame(plan.totalMs);const actual=ctx.getImageData(0,0,VIEW_W,VIEW_H).data,saved=plan;plan={...saved,strokes:StudioGraphite.marks(analysis).map(s=>({...s,tLift:0,tDown:0,tUp:1,alpha:s.alpha*(.8+Number(strength.value)/200)}))};resetInk();renderFrame(plan.totalMs);const expected=ctx.getImageData(0,0,VIEW_W,VIEW_H).data;let sum=0,max=0;for(let i=0;i<actual.length;i++){const d=Math.abs(actual[i]-expected[i]);sum+=d;max=Math.max(max,d);}plan=saved;resetInk();handToggle.checked=true;return {mean:sum/actual.length,max};});console.log('finished appearance difference',fidelity);assert(fidelity.mean<.12&&fidelity.max<=8);
 const frames=[];for(const fraction of [0,.12,.26,.40,.58,.75,1]){await page.evaluate(f=>renderFrame(plan.totalMs*f),fraction);const name=`frame-${Math.round(fraction*100)}.jpg`;fs.writeFileSync(path.join(out,name),Buffer.from(await page.evaluate(()=>canvas.toDataURL('image/jpeg',.9).split(',')[1]),'base64'));frames.push({name,time:fraction*20});}
 fs.writeFileSync(path.join(out,'review.html'),`<!doctype html><meta charset="utf-8"><style>body{font:16px sans-serif;background:#eae7df;margin:20px}.frames{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}img{width:100%}figure{margin:0}video{width:600px}</style><h1>백지에서 완성까지 · 실제 영상의 중간 장면</h1><div class="frames">${frames.map(f=>`<figure><img src="${f.name}"><figcaption>${f.time.toFixed(1)}초</figcaption></figure>`).join('')}</div><video src="drawing-process.mp4" poster="frame-100.jpg" controls preload="none"></video>`);
 await page.evaluate(()=>{handToggle.checked=true;});const download=page.waitForEvent('download',{timeout:240000});await page.click('#export');await(await download).saveAs(path.join(out,'drawing-process.mp4'));assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: blank opening, line-first chronology, all marks preserved, finished fidelity, actual MP4');
 await page.goto(`http://127.0.0.1:${server.address().port}/.test-output/process/review.html`);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.locator('.frames').screenshot({path:path.join(out,'review.jpg'),type:'jpeg',quality:85});
 }finally{await browser.close();server.close();}
};
