const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({chromium,server,root})=>{
 const out=path.join(root,'.test-output/story');fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=`http://127.0.0.1:${server.address().port}`;await page.goto(url+'/story.html');assert.equal(await page.inputValue('#orientation'),'landscape');assert.equal(await page.evaluate(()=>canvas.width),1920);await page.evaluate(()=>loadStory({id:'mom-concert',title:'엄마가 운동을 시작한 진짜 이유'}));await page.waitForFunction(()=>scenes.length===4&&!busy);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>total()),24);
 for(const t of [2,8,13,16.5,19]){await page.evaluate(t=>draw(t),t);fs.writeFileSync(path.join(out,`frame-${t}.png`),Buffer.from(await page.evaluate(()=>canvas.toDataURL().split(',')[1]),'base64'));}
 const bundle=await page.evaluate(()=>pack());await page.click('#reset');assert.equal(await page.evaluate(()=>scenes.length),0);await page.evaluate(p=>applyPack(p),bundle);assert.equal(await page.evaluate(()=>total()),24);
 await assert.rejects(()=>page.evaluate(p=>applyPack({...p,scenes:[{...p.scenes[0],photo:99}]}),bundle));assert.equal(await page.evaluate(()=>scenes.length),4);
 const srtEvent=page.waitForEvent('download');await page.click('#srt');await(await srtEvent).saveAs(path.join(out,'episode-01.srt'));assert(fs.readFileSync(path.join(out,'episode-01.srt'),'utf8').includes('00:00:17,000'));
 const packEvent=page.waitForEvent('download');await page.click('#savePack');await(await packEvent).saveAs(path.join(out,'episode-01.story.json'));
 await page.selectOption('#orientation','landscape');assert(await page.evaluate(()=>{const s={text:'가나다라 '.repeat(30),seconds:30,delay:0};return captionLayout(s,5,1920,1080).pages>1&&captionLayout(s,5,1920,1080).font===88;}));await page.evaluate(()=>draw(19));fs.writeFileSync(path.join(out,'landscape.png'),Buffer.from(await page.evaluate(()=>canvas.toDataURL().split(',')[1]),'base64'));await page.selectOption('#orientation','portrait');
 if(!process.argv.includes('--ui-only')){const movie=page.waitForEvent('download',{timeout:600000});await page.click('#export');await(await movie).saveAs(path.join(out,'episode-01.mp4'));await page.waitForFunction(()=>!busy);assert((await page.textContent('#status')).includes('저장했습니다'));}
 const metadata=await page.evaluate(async url=>{const v=document.createElement('video');v.src=url;await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=reject;});return {duration:v.duration,width:v.videoWidth,height:v.videoHeight};},url+'/.test-output/story/episode-01.mp4');console.log(metadata);assert(Math.abs(metadata.duration-24)<.1);assert.equal(metadata.width,1080);assert.equal(metadata.height,1920);
 if(process.argv.includes('--long')){await page.selectOption('#orientation','landscape');await page.evaluate(()=>{scenes=Array.from({length:7},(_,i)=>({...scenes[i%4],seconds:i===6?2:30,delay:0}));sync();});const event=page.waitForEvent('download',{timeout:600000});await page.click('#export');await(await event).saveAs(path.join(out,'longform-182.mp4'));await page.waitForFunction(()=>!busy);const m=await page.evaluate(async url=>{const v=document.createElement('video');v.src=url;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j;});return {seconds:v.duration,w:v.videoWidth,h:v.videoHeight};},url+'/.test-output/story/longform-182.mp4');assert(Math.abs(m.seconds-182)<.1);assert.equal(m.w,1920);assert.equal(m.h,1080);console.log('PASS: disk-backed longform export',m);await page.evaluate(p=>applyPack(p),bundle);}
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 await page.locator('#photoList button').first().click();assert.equal(await page.evaluate(()=>photos.length),3);assert(await page.evaluate(()=>scenes.every(s=>s.photo<photos.length)));
 await page.fill('#script','엄마: 첫 장면\n\n딸: 다음 장면');await page.click('#build');assert.equal(await page.evaluate(()=>scenes.length),2);await page.click('#export');await page.click('#cancel');await page.waitForFunction(()=>!busy);assert((await page.textContent('#status')).includes('취소'));assert.deepEqual(errors,[]);console.log('PASS: sample, bundle roundtrip, validation, SRT timing, orientations, 24-second MP4, mobile, removal, script parsing, cancel');
 }finally{await browser.close();server.close();}
};
