const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({chromium,server,root})=>{const out=path.join(root,'.test-output/woong-rabbit');fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=`http://127.0.0.1:${server.address().port}`;await page.goto(base+'/woong-rabbit.html');await page.waitForFunction(()=>ready,{},{timeout:30000});const info=await page.evaluate(()=>Object.fromEntries(Object.entries(sheets).map(([k,v])=>[k,{count:v.frames.length,transparent:v.transparent,frames:v.frames}])));for(const v of Object.values(info)){assert.equal(v.count,6);assert(v.transparent>.2);}console.log(JSON.stringify(info));
await page.context().grantPermissions(['clipboard-read','clipboard-write']);
const script=await page.inputValue('#narration-text');assert(script.startsWith('건행!'));assert(!script.includes('00:'));await page.click('#narration-copy');assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,"\n"),script);
await page.fill('#narration-text','테스트 문장입니다.\n건행!');const txtEvent=page.waitForEvent('download');await page.click('#narration-save');const txtDownload=await txtEvent;const txtPath=path.join(out,'tts-test.txt');await txtDownload.saveAs(txtPath);assert.equal(fs.readFileSync(txtPath,'utf8').replace(/^\uFEFF/,''),'테스트 문장입니다.\n건행!');await page.fill('#narration-text',script);
const home=await browser.newPage();await home.setViewportSize({width:390,height:844});await home.goto(base+'/index.html');assert(await home.locator('nav a[href="woong-rabbit.html"]').isVisible());assert(await home.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await home.close();
for(const t of [2,6,10,14,16,19,25,30,34]){await page.evaluate(t=>render(t),t);fs.writeFileSync(path.join(out,`frame-${t}.png`),Buffer.from(await page.evaluate(()=>canvas.toDataURL().split(',')[1]),'base64'));}
await page.click('#play');await page.waitForFunction(()=>time>.3);await page.click('#play');assert.equal(await page.evaluate(()=>playing),0);await page.click('#chapters button:last-child');assert.equal(await page.evaluate(()=>time),32);await page.uncheck('#captions');await page.check('#captions');
if(!process.argv.includes('--ui-only')){const event=page.waitForEvent('download',{timeout:240000});await page.click('#export');await(await event).saveAs(path.join(out,'episode-01.mp4'));await page.waitForFunction(()=>!busy);const meta=await page.evaluate(async src=>{const v=document.createElement('video');v.src=src;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j;});return {duration:v.duration,width:v.videoWidth,height:v.videoHeight};},base+'/.test-output/woong-rabbit/episode-01.mp4');assert.equal(meta.width,1920);assert.equal(meta.height,1080);assert(Math.abs(meta.duration-36)<.1);console.log(meta);await page.click('#export');await page.click('#cancel');await page.waitForFunction(()=>!busy);assert.match(await page.textContent('#status'),/취소/);}
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: 18 alpha poses, scene navigation, playback, captions, mobile, MP4 export and cancellation');}finally{await browser.close();server.close();}};
