const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({chromium,server,root})=>{
 const out=path.join(root,'.test-output/ny-travel');fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=`http://127.0.0.1:${server.address().port}`;await page.goto(url+'/story.html');await page.click('#example');await page.waitForFunction(()=>scenes.length===25&&!busy);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>total()),200);assert.equal(await page.inputValue('#orientation'),'landscape');assert.equal(await page.locator('#storySources a').count(),3);
 const bundle=await page.evaluate(()=>pack());assert(bundle.scenes.every(s=>s.credit));await page.click('#reset');assert(await page.locator('#storySources').isHidden());await page.evaluate(p=>applyPack(p),bundle);assert.deepEqual(await page.evaluate(()=>pack().sources),bundle.sources);
 for(const t of [2,34,74,114,146,194]){await page.evaluate(t=>draw(t),t);fs.writeFileSync(path.join(out,`frame-${t}.png`),Buffer.from(await page.evaluate(()=>canvas.toDataURL().split(',')[1]),'base64'));}
 for(const [button,file] of [['#srt','ny-travel.srt'],['#tts','TTS.txt'],['#savePack','ny-travel.story.json']]){const event=page.waitForEvent('download');await page.click(button);await(await event).saveAs(path.join(out,file));}
 assert(fs.readFileSync(path.join(out,'ny-travel.srt'),'utf8').includes('00:03:20,000'));
 if(!process.argv.includes('--ui-only')){const movie=page.waitForEvent('download',{timeout:600000});await page.click('#export');await(await movie).saveAs(path.join(out,'ny-travel.mp4'));await page.waitForFunction(()=>!busy);const m=await page.evaluate(async url=>{const v=document.createElement('video');v.src=url;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j;});return {seconds:v.duration,w:v.videoWidth,h:v.videoHeight};},url+'/.test-output/ny-travel/ny-travel.mp4');assert(Math.abs(m.seconds-200)<.1);assert.equal(m.w,1920);assert.equal(m.h,1080);console.log('MP4 verified',m);}
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(out,'mobile.png')});assert.deepEqual(errors,[]);console.log('PASS: news library, 25 scenes, 200 seconds, source and credit roundtrip, TTS/SRT downloads, mobile');
 }finally{await browser.close();server.close();}
};
