const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async({chromium,server,root})=>{
 const out=path.join(root,'.test-output/renewal');fs.mkdirSync(out,{recursive:true});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForSelector('.news-card');await page.evaluate(()=>document.fonts.ready);
  assert.match(await page.locator('.fan-brand').first().innerText(),/웅토끼 팬 스튜디오/);assert.equal(await page.locator('.fan-header nav a').count(),4);assert.equal(await page.locator('.quick-menu a').count(),4);assert.equal(await page.locator('.create-card').count(),2);assert.equal(await page.locator('.news-card').count(),1);assert.equal(await page.locator('.work-card').count(),5);assert.equal(await page.locator('.gallery-grid>a').count(),3);assert.equal(await page.locator('.featured-film .button').count(),0);assert.equal(await page.locator('.work-card').first().getAttribute('href'),'work-view.html?id=warm-meal');assert.equal(await page.locator('#latest-hero-link').getAttribute('href'),'news-baila.html');assert.match(await page.locator('#latest-hero-bubble-text').innerText(),/Baila/);
  const links=await page.locator('a').evaluateAll(as=>as.map(a=>a.getAttribute('href')||''));for(const forbidden of ['woong-studio.html','official-promo-baila.html','story.html','woong-rabbit-series.html'])assert(!links.some(h=>h.includes(forbidden)),forbidden);
  const images=await page.evaluate(async()=>{const ims=[...document.images];ims.forEach(im=>im.loading='eager');await Promise.all(ims.map(im=>im.decode()));return ims.every(im=>im.naturalWidth>0)});assert(images);
  for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);await page.screenshot({path:path.join(out,`fan-home-${width}.png`),fullPage:true})}
  await page.goto(`http://127.0.0.1:${server.address().port}/fan-maker.html`);assert.equal(await page.locator('#export').isDisabled(),true);assert.equal(await page.locator('#thumbnail').isDisabled(),true);await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.goto(`http://127.0.0.1:${server.address().port}/atelier.html`);assert.equal(await page.inputValue('#style'),'graphite');assert.equal(await page.inputValue('#framing'),'face');assert.equal(await page.locator('#programMode').count(),0);assert.match(await page.locator('.studio-brand').innerText(),/웅토끼 팬 스튜디오/);await page.setViewportSize({width:1440,height:1000});assert(await page.evaluate(()=>Math.abs(document.querySelector('#stage').getBoundingClientRect().width-document.querySelector('.layout').getBoundingClientRect().width)<2));await page.click('#expandCanvas');assert.equal(await page.getAttribute('#expandCanvas','aria-pressed'),'true');await page.click('#expandCanvas');await page.screenshot({path:path.join(out,'studio-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.goto(`http://127.0.0.1:${server.address().port}/classic.html`);await page.waitForURL('**/atelier.html');assert.equal(await page.inputValue('#style'),'graphite');
  assert.deepEqual(errors,[]);console.log('PASS: public fan home, public creation menu, responsive widths and sketch studio navigation');
 }finally{await browser.close();server.close()}
};
