(()=>{
'use strict';
const $=id=>document.getElementById(id),FPS=30,RATE=48000,SCENE=7,LONG=63,SHORT=30;
const longTitle='영웅시대가 차린 따뜻한 한 끼';
const shortTitle='880만 원보다 더 따뜻했던 것';
const longNarration='2026년 8월, 임영웅의 데뷔 10주년을 맞아 성남영웅건행국 회원들이 안나의집 주방에 모였습니다. 880만 원을 후원한 데 이어, 채소를 씻고 썰고 큰 솥을 저어 따뜻한 한 끼를 만들었습니다. 정성껏 담은 식판을 건네자 기다리던 이웃의 얼굴에 미소가 번졌습니다. 좋아하는 가수의 기념일을 이웃의 따뜻한 하루로 바꾼 팬들. 웅토끼도 마음을 보탭니다. 오늘도 건강하고 행복하세요. 건행~';
const shortNarration='팬들은 880만 원만 전하고 돌아서지 않았습니다. 채소를 씻고, 국을 끓이고, 따뜻한 식판을 직접 건넸습니다. 좋아하는 마음이 이웃의 한 끼가 된 날. 오늘도 건강하고 행복하세요. 건행~';
const scenes=[
 {bg:2,title:'오늘은 특별한 기념일 선물을 준비합니다',tag:'데뷔 10주년'},
 {bg:0,title:'채소를 씻고, 하나씩 정성껏',tag:'이른 아침 주방'},
 {bg:0,title:'썰고, 끓이고, 맛을 더합니다',tag:'직접 만든 한 끼'},
 {bg:0,title:'따뜻한 식판에 마음까지 담았습니다',tag:'웅토끼도 살짝 등장'},
 {bg:1,title:'기다리던 이웃에게 한 상씩',tag:'배식 시작'},
 {bg:1,title:'따뜻한 국 한 숟갈에 번진 미소',tag:'맛있게 드세요'},
 {bg:1,title:'880만 원보다 더 따뜻했던 땀',tag:'후원과 봉사'},
 {bg:1,title:'좋아하는 마음이 이웃의 한 끼로',tag:'함께 만든 하루'},
 {bg:2,title:'오늘도 건강하고 행복하세요. 건행~',tag:'손목을 꺾은 건행 인사'}
];
const bgFiles=['kitchen.webp','dining-hall.webp','center-exterior.webp'].map(x=>'assets/warm-meal/backgrounds/'+x),backgrounds=[],volunteer=[],guest=[];let rabbit;
const canvas=$('render-canvas'),shortCanvas=$('short-canvas');let busy=false,cancelled=false,longURL='',shortURL='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,smooth=t=>{t=clamp(t);return t*t*(3-2*t)},smoother=t=>{t=clamp(t);return t*t*t*(t*(t*6-15)+10)};
async function image(src){const im=new Image();im.src=src;await im.decode();return im}
function extract(im,cols,rows){const s=document.createElement('canvas');s.width=im.width;s.height=im.height;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(im,0,0);const d=c.getImageData(0,0,s.width,s.height).data,out=[];for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){const x0=Math.round(q*s.width/cols),x1=Math.round((q+1)*s.width/cols),y0=Math.round(r*s.height/rows),y1=Math.round((r+1)*s.height/rows);let l=x1,rr=x0,t=y1,b=y0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(d[(y*s.width+x)*4+3]>20){l=Math.min(l,x);rr=Math.max(rr,x);t=Math.min(t,y);b=Math.max(b,y)}const cc=document.createElement('canvas');cc.width=Math.max(1,rr-l+1);cc.height=Math.max(1,b-t+1);cc.getContext('2d').drawImage(im,l,t,cc.width,cc.height,0,0,cc.width,cc.height);out.push(cc)}return out}
function cover(g,im,w,h,focus=.5,zoom=1,pan=0){const ratio=w/h,src=im.width/im.height;let sw,sh;if(src>ratio){sh=im.height/zoom;sw=sh*ratio}else{sw=im.width/zoom;sh=sw/ratio}const sx=clamp(im.width*focus-sw/2+pan,0,im.width-sw),sy=(im.height-sh)/2;g.drawImage(im,sx,sy,sw,sh,0,0,w,h)}
function draw(g,im,x,bottom,height,opt={}){const width=height*im.width/im.height;g.save();g.globalAlpha=opt.alpha??1;g.translate(x,bottom);g.rotate(opt.rotate||0);if(opt.flip)g.scale(-1,1);g.drawImage(im,-width/2,-height,width,height);g.restore()}
function blend(g,frames,a,b,p,x,bottom,height,opt={}){p=smoother(p);draw(g,frames[p<.5?a:b],x,bottom,height,{...opt,rotate:(opt.rotate||0)+Math.sin(p*Math.PI)*.008})}
function sequence(g,frames,order,t,x,bottom,height,opt={}){const span=2.1,pos=(t/span)%order.length,i=Math.floor(pos),p=pos-i;blend(g,frames,order[i],order[(i+1)%order.length],p,x,bottom,height,opt)}
function walk(g,frames,a,b,t,x0,x1,bottom,height,opt={}){const p=smoother(t/SCENE),step=t*2.1,pose=Math.floor(step)%2?a:b,x=mix(x0,x1,p),bob=Math.abs(Math.sin(step*Math.PI))*7,lean=Math.sin(step*Math.PI*2)*.012;draw(g,frames[pose],x,bottom-bob,height,{...opt,rotate:(opt.rotate||0)+lean})}
function actors(index,t,g,w,h,vertical=false){const bottom=h-(vertical?58:8),vh=vertical?650:515,gh=vertical?620:485,rh=vertical?355:300,c=w/2,bob=Math.sin(t*2.4)*2,pose=(frames,n,x,b=bottom,height=vh,opt={})=>draw(g,frames[n],x,b+bob,height,{...opt,rotate:(opt.rotate||0)+Math.sin(t*1.9+n)*.006});
 if(vertical){
  if(index===0){pose(volunteer,7,c,bottom,vh);pose(rabbit?[rabbit]:volunteer,0,115,bottom,rabbit?rh:vh*.58)}
  else if(index===1)pose(volunteer,0,c,bottom,vh);
  else if(index===2)pose(volunteer,t<3.4?1:2,c,bottom,vh);
  else if(index===3){pose(volunteer,t<3.2?3:4,c+75,bottom,vh);pose([rabbit],0,105,bottom,rh)}
  else if(index===4){pose(volunteer,5,c+110,bottom,vh);pose(guest,t<3.3?1:2,105,bottom,gh*.72)}
  else if(index===5)pose(guest,t<3.5?4:5,c,bottom,gh);
  else if(index===6){pose(volunteer,7,c+90,bottom,vh);pose(guest,6,110,bottom,gh*.72)}
  else if(index===7){pose(volunteer,6,c+90,bottom,vh);pose(guest,7,110,bottom,gh*.72)}
  else{pose([rabbit],0,c,bottom,rh*1.55);pose(volunteer,7,95,bottom,vh*.67);pose(guest,7,w-95,bottom,gh*.65,true)}return;
 }
 switch(index){
  case 0:pose(volunteer,7,w*.48,bottom,vh);pose([rabbit],0,w*.72,bottom,rh);break;
  case 1:pose(volunteer,0,w*.42,bottom,vh);pose(volunteer,1,w*.69,bottom,vh*.82,{flip:true});break;
  case 2:pose(volunteer,t<3.4?1:2,w*.48,bottom,vh);pose(volunteer,0,w*.73,bottom,vh*.78,{flip:true});break;
  case 3:pose(volunteer,t<3.2?3:4,w*.43,bottom,vh);pose([rabbit],0,w*.74,bottom,rh);break;
  case 4:pose(volunteer,5,w*.4,bottom,vh);pose(guest,t<3.3?1:2,w*.68,bottom,gh);break;
  case 5:pose(guest,t<3.5?4:5,w*.57,bottom,gh);pose(volunteer,7,w*.31,bottom,vh*.78);break;
  case 6:pose(volunteer,7,w*.4,bottom,vh);pose(guest,6,w*.69,bottom,gh);break;
  case 7:pose(volunteer,6,w*.38,bottom,vh);pose(guest,7,w*.67,bottom,gh);break;
  default:pose([rabbit],0,w*.5,bottom,rh*1.42);pose(volunteer,7,w*.22,bottom,vh*.73);pose(guest,7,w*.78,bottom,gh*.72,true);
 }
}
function round(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);g.fill()}
function caption(g,scene,t,w,h,vertical=false){const bw=vertical?w-70:Math.min(890,w*.69),bh=vertical?185:118,x=(w-bw)/2,y=vertical?70:42,enter=smoother(t/.45),scale=.92+.08*enter;g.save();g.translate(w/2,y+bh/2);g.scale(scale,scale);g.translate(-w/2,-y-bh/2);g.globalAlpha=enter;g.shadowColor='rgba(9,31,50,.35)';g.shadowBlur=20;g.shadowOffsetY=8;g.fillStyle='rgba(255,255,255,.96)';round(g,x,y,bw,bh,vertical?30:24);g.shadowColor='transparent';g.lineWidth=5;g.strokeStyle='#244d68';g.stroke();g.fillStyle='#ffcf59';round(g,x+25,y-19,vertical?260:220,42,21);g.fillStyle='#173d56';g.textAlign='center';g.textBaseline='middle';g.font=`800 ${vertical?22:18}px "Nanum Gothic",sans-serif`;g.fillText(scene.tag,x+25+(vertical?130:110),y+2);let size=vertical?50:44;while(size>25){g.font=`800 ${size}px "Nanum Gothic",sans-serif`;if(g.measureText(scene.title).width<bw-45)break;size-=2}g.lineWidth=8;g.strokeStyle='#fff';g.strokeText(scene.title,w/2,y+bh*.61);g.fillStyle='#17384d';g.fillText(scene.title,w/2,y+bh*.61);g.restore()}
function particles(g,w,h,t){for(let i=0;i<22;i++){const x=(i*127+t*21)%w,y=h*.22+(i*67%Math.round(h*.62))+Math.sin(t*1.7+i)*8,a=.08+.18*(.5+.5*Math.sin(t*3+i));g.globalAlpha=a;g.fillStyle=i%4?'#8cddff':'#ffe09a';g.beginPath();g.arc(x,y,1.5+i%3,0,Math.PI*2);g.fill()}g.globalAlpha=1}
function renderGlobal(time,target,vertical=false){const g=target.getContext('2d'),w=target.width,h=target.height,index=Math.min(scenes.length-1,Math.floor(time/SCENE)),local=time-index*SCENE,scene=scenes[index];g.clearRect(0,0,w,h);const zoom=1+.025*smooth(local/SCENE),pan=Math.sin((index+1)*1.7)*backgrounds[scene.bg].width*.015;cover(g,backgrounds[scene.bg],w,h,.5,zoom,pan);if(local<.55&&index>0){g.save();g.globalAlpha=1-smoother(local/.55);cover(g,backgrounds[scenes[index-1].bg],w,h,.5,1.025);g.restore()}const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,25,43,.27)');shade.addColorStop(.58,'rgba(5,25,43,.01)');shade.addColorStop(1,'rgba(4,20,35,.43)');g.fillStyle=shade;g.fillRect(0,0,w,h);actors(index,local,g,w,h,vertical);particles(g,w,h,time);caption(g,scene,local,w,h,vertical);g.fillStyle='rgba(8,34,53,.72)';round(g,w*.2,h-38,w*.6,26,13);g.fillStyle='#fff';g.font=`700 ${vertical?15:13}px "Nanum Gothic",sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText('2026 성남영웅건행국 무료급식 봉사 보도를 바탕으로 한 창작 재구성',w/2,h-25)}
const shortMap=[0,1,2,4,5,8],shortLines=['특별한 기념일에','팬들이 주방에 모여','큰 솥에 마음을 끓여','따뜻한 식판을 건네자','이웃의 얼굴에 미소가','오늘도 건행~'];
function renderShort(time,target){const g=target.getContext('2d'),w=target.width,h=target.height,part=Math.min(5,Math.floor(time/5)),local=time-part*5,index=shortMap[part],scene=scenes[index];g.clearRect(0,0,w,h);cover(g,backgrounds[scene.bg],w,h,.5,1.06+.02*smooth(local/5));const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(6,27,46,.76)');shade.addColorStop(.35,'rgba(6,27,46,.06)');shade.addColorStop(1,'rgba(5,22,38,.75)');g.fillStyle=shade;g.fillRect(0,0,w,h);actors(index,local,g,w,h,true);particles(g,w,h,time);g.textAlign='center';g.textBaseline='middle';g.lineJoin='round';let size=54;while(size>34){g.font=`800 ${size}px "Nanum Gothic",sans-serif`;if(g.measureText(shortLines[part]).width<w-80)break;size-=2}g.lineWidth=12;g.strokeStyle='rgba(10,37,57,.95)';g.strokeText(shortLines[part],w/2,165);g.fillStyle=part===5?'#ffd25f':'#fff';g.fillText(shortLines[part],w/2,165);g.fillStyle='#65c9f0';g.fillRect(0,0,w*time/SHORT,8);g.fillStyle='rgba(255,255,255,.23)';g.fillRect(w*time/SHORT,0,w,8);g.fillStyle='rgba(10,37,57,.76)';round(g,45,h-78,w-90,46,23);g.fillStyle='#fff';g.font='700 18px "Nanum Gothic",sans-serif';g.fillText('영웅시대가 차린 따뜻한 한 끼',w/2,h-55)}
function scheduleAudio(ac,dest,duration,offset=0){const master=ac.createGain();master.gain.value=.48;master.connect(dest);const tone=(at,f,d=.5,v=.025,type='sine')=>{if(at+d<=offset)return;const begin=Math.max(at,offset),when=begin-offset,remain=at+d-begin,o=ac.createOscillator(),gain=ac.createGain();o.type=type;o.frequency.value=f;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(v,when+.03);gain.gain.exponentialRampToValueAtTime(.0001,when+remain);o.connect(gain).connect(master);o.start(when);o.stop(when+remain+.03)};const roots=[196,220,246.94,261.63];for(let at=0,n=0;at<duration;at+=4,n++){const root=roots[n%4],lift=at>duration*.55?1.12:1;for(const m of [1,1.25,1.5])tone(at,root*m*lift,3.85,.013,'triangle');for(let k=.35;k<3.8;k+=.7)tone(at+k,root*[2,2.5,3,2.25][Math.floor(k*2)%4]*lift,.22,.018,'sine');if(at>duration*.42)tone(at+.1,root*.5,.18,.025,'triangle')}return master}
async function muxer(){if(window.Mp4Muxer)return;await new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mp4-muxer@5.2.2/build/mp4-muxer.min.js';s.onload=ok;s.onerror=()=>fail(Error('영상 저장 도구를 불러오지 못했습니다.'));document.head.append(s)})}
async function audioChunks(duration,config){const ac=new OfflineAudioContext(config.numberOfChannels,Math.ceil(duration*RATE),RATE);scheduleAudio(ac,ac.destination,duration);const b=await ac.startRendering(),chunks=[];let err;const enc=new AudioEncoder({output:(chunk,meta)=>chunks.push({chunk,meta}),error:e=>err=e});enc.configure(config);for(let off=0;off<b.length;off+=4800){const len=Math.min(4800,b.length-off),data=new Float32Array(len*config.numberOfChannels);for(let c=0;c<config.numberOfChannels;c++)data.set(b.getChannelData(c).subarray(off,off+len),c*len);const a=new AudioData({format:'f32-planar',sampleRate:RATE,numberOfFrames:len,numberOfChannels:config.numberOfChannels,timestamp:Math.round(off/RATE*1e6),data});enc.encode(a);a.close();if(enc.encodeQueueSize>14)await enc.flush()}await enc.flush();enc.close();if(err)throw err;return chunks.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp).filter((x,i,a)=>!i||x.chunk.timestamp>a[i-1].chunk.timestamp)}
async function encode({duration,width,height,drawFrame,progress}){if(!window.VideoEncoder||!window.AudioEncoder)throw Error('최신 Chrome 또는 Edge에서 이용해 주세요.');await muxer();const vc={codec:'avc1.42001f',width,height,bitrate:height>width?3400000:3200000,framerate:FPS,hardwareAcceleration:'prefer-hardware',latencyMode:'realtime'};if(!(await VideoEncoder.isConfigSupported(vc)).supported)throw Error('이 기기에서 MP4 저장을 지원하지 않습니다.');let ac;for(const channels of [2,1]){const candidate={codec:'mp4a.40.2',sampleRate:RATE,numberOfChannels:channels,bitrate:128000};if((await AudioEncoder.isConfigSupported(candidate)).supported){ac=candidate;break}}if(!ac)throw Error('이 기기에서 오디오 저장을 지원하지 않습니다.');const out=document.createElement('canvas');out.width=width;out.height=height;const target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,firstTimestampBehavior:'offset',video:{codec:'avc',width,height,frameRate:FPS},audio:{codec:'aac',numberOfChannels:ac.numberOfChannels,sampleRate:RATE},fastStart:'in-memory'}),audios=await audioChunks(duration,ac),videos=[];let err,enc=new VideoEncoder({output:(chunk,meta)=>videos.push({chunk,meta}),error:e=>err=e});try{enc.configure(vc);const total=Math.round(duration*FPS);for(let i=0;i<total;i++){if(cancelled)throw Error('저장을 취소했습니다.');if(err)throw err;drawFrame(i/FPS,out);const frame=new VideoFrame(out,{timestamp:Math.round(i/FPS*1e6),duration:Math.round(1e6/FPS)});enc.encode(frame,{keyFrame:i%(FPS*2)===0});frame.close();if(i%8===0||enc.encodeQueueSize>6){progress(i/total);await new Promise(r=>setTimeout(r,0));while(enc.encodeQueueSize>6)await new Promise(r=>setTimeout(r,6))}}await enc.flush();if(err)throw err;videos.sort((a,b)=>a.chunk.timestamp-b.chunk.timestamp);let last=-1;for(const x of videos){if(x.chunk.timestamp<=last)continue;mux.addVideoChunk(x.chunk,x.meta);last=x.chunk.timestamp}last=-1;for(const x of audios){if(x.chunk.timestamp<=last)continue;mux.addAudioChunk(x.chunk,x.meta);last=x.chunk.timestamp}mux.finalize();return new Blob([target.buffer],{type:'video/mp4'})}finally{if(enc.state!=='closed')enc.close()}}
function textDownload(text,name){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000)}
function blobDownload(blob,name,kind){const u=URL.createObjectURL(blob),a=kind==='short'?$('short-ready'):$('long-ready');if(kind==='short'){if(shortURL)URL.revokeObjectURL(shortURL);shortURL=u}else{if(longURL)URL.revokeObjectURL(longURL);longURL=u}a.href=u;a.download=name;a.hidden=false;a.click()}
function lock(on){busy=on;for(const id of ['download-long','download-long-script','download-thumb','download-short','download-short-script'])$(id).disabled=on;$('cancel-export').hidden=!on}
$('cancel-export').onclick=()=>cancelled=true;
$('download-long-script').onclick=()=>textDownload(`${longTitle}\n\n${longNarration}\n\n※ 2026년 8월 공개 보도를 바탕으로 인물과 장면을 창작 재구성했습니다.`, '영웅시대가-차린-따뜻한-한-끼-롱폼-나레이션.txt');
$('download-short-script').onclick=()=>textDownload(`${shortTitle}\n\n${shortNarration}`, '880만-원보다-더-따뜻했던-것-쇼츠-나레이션.txt');
$('download-long').onclick=async()=>{if(busy)return;cancelled=false;lock(true);try{const blob=await encode({duration:LONG,width:1280,height:720,drawFrame:(t,c)=>renderGlobal(t,c,false),progress:p=>$('long-status').textContent=`롱폼 영상 만드는 중… ${Math.floor(p*100)}%`});blobDownload(blob,'영웅시대가-차린-따뜻한-한-끼-롱폼.mp4','long');$('long-status').textContent='1분 3초 롱폼 영상이 완성됐습니다.'}catch(e){$('long-status').textContent='롱폼 저장 오류: '+(e?.message||e)}finally{lock(false)}};
$('download-short').onclick=async()=>{if(busy)return;cancelled=false;lock(true);try{const blob=await encode({duration:SHORT,width:720,height:1280,drawFrame:(t,c)=>renderShort(t,c),progress:p=>$('short-status').textContent=`쇼츠 영상 만드는 중… ${Math.floor(p*100)}%`});blobDownload(blob,'880만-원보다-더-따뜻했던-것-30초-쇼츠.mp4','short');$('short-status').textContent='30초 쇼츠 영상이 완성됐습니다.'}catch(e){$('short-status').textContent='쇼츠 저장 오류: '+(e?.message||e)}finally{lock(false)}};
$('download-thumb').onclick=async()=>{await document.fonts.ready;const c=document.createElement('canvas');c.width=1280;c.height=720;const g=c.getContext('2d');cover(g,backgrounds[1],1280,720,.5,1);const grad=g.createLinearGradient(0,0,1030,0);grad.addColorStop(0,'rgba(4,23,40,.98)');grad.addColorStop(.69,'rgba(5,29,50,.72)');grad.addColorStop(1,'rgba(5,29,50,.04)');g.fillStyle=grad;g.fillRect(0,0,1280,720);draw(g,volunteer[4],1045,710,610);g.textAlign='left';g.textBaseline='middle';g.lineJoin='round';g.font='800 70px "Nanum Gothic",sans-serif';g.lineWidth=14;g.strokeStyle='#102b43';g.strokeText('880만 원보다',58,174);g.fillStyle='#fff';g.fillText('880만 원보다',58,174);g.font='800 92px "Nanum Gothic",sans-serif';g.lineWidth=16;g.strokeText('더 따뜻했던 것',52,298);g.fillStyle='#ffd15a';g.fillText('더 따뜻했던 것',52,298);g.fillStyle='#2b7fa9';round(g,60,382,650,72,36);g.fillStyle='#fff';g.font='800 31px "Nanum Gothic",sans-serif';g.fillText('영웅시대가 차린 따뜻한 한 끼',90,418);g.fillStyle='#a9e9ff';g.font='700 27px "Nanum Gothic",sans-serif';g.fillText('후원금 · 조리 봉사 · 무료급식',63,540);g.fillStyle='#fff';g.font='700 29px "Nanum Gothic",sans-serif';g.fillText('좋아하는 마음이 한 끼가 된 날',63,601);c.toBlob(b=>blobDownload(b,'영웅시대가-차린-따뜻한-한-끼-썸네일.png','long'),'image/png')};
const number=n=>String(n).padStart(2,'0');
Promise.all([
 ...bgFiles.map(async(f,i)=>backgrounds[i]=await image(f)),
 ...Array.from({length:8},(_,i)=>(async()=>volunteer[i]=await image(`assets/warm-meal/characters/volunteer-${number(i+1)}.png`))()),
 ...Array.from({length:8},(_,i)=>(async()=>guest[i]=await image(`assets/warm-meal/characters/guest-${number(i+1)}.png`))()),
 (async()=>rabbit=await image('assets/warm-meal/characters/woong-rabbit-geonhaeng.png'))(),
 document.fonts.ready
]).then(()=>{for(const id of ['download-long','download-long-script','download-thumb','download-short','download-short-script'])$(id).disabled=false;$('long-status').textContent='롱폼 영상·나레이션·썸네일을 다운로드할 수 있습니다.';$('short-status').textContent='30초 쇼츠 영상과 전체 나레이션을 다운로드할 수 있습니다.'}).catch(e=>{$('long-status').textContent='불러오기 실패: '+e.message;$('short-status').textContent='불러오기 실패: '+e.message});
window.addEventListener('beforeunload',()=>{if(longURL)URL.revokeObjectURL(longURL);if(shortURL)URL.revokeObjectURL(shortURL)});
window.__warmMealTest={renderGlobal,renderShort};
})();
